// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: invalid.proto
// Protobuf Java Version: 4.33.3

package com.codebinge.firestore.codec.testdata.v1;

/**
 * <pre>
 * google.protobuf.Any is not supported (§3.4).
 * </pre>
 *
 * Protobuf type {@code codebinge.firestore.codec.testdata.v1.AnyField}
 */
@com.google.protobuf.Generated
public final class AnyField extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:codebinge.firestore.codec.testdata.v1.AnyField)
    AnyFieldOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 3,
      /* suffix= */ "",
      "AnyField");
  }
  // Use AnyField.newBuilder() to construct.
  private AnyField(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private AnyField() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.codebinge.firestore.codec.testdata.v1.Invalid.internal_static_codebinge_firestore_codec_testdata_v1_AnyField_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.codebinge.firestore.codec.testdata.v1.Invalid.internal_static_codebinge_firestore_codec_testdata_v1_AnyField_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.codebinge.firestore.codec.testdata.v1.AnyField.class, com.codebinge.firestore.codec.testdata.v1.AnyField.Builder.class);
  }

  private int bitField0_;
  public static final int BAD_FIELD_NUMBER = 1;
  private com.google.protobuf.Any bad_;
  /**
   * <code>.google.protobuf.Any bad = 1;</code>
   * @return Whether the bad field is set.
   */
  @java.lang.Override
  public boolean hasBad() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.google.protobuf.Any bad = 1;</code>
   * @return The bad.
   */
  @java.lang.Override
  public com.google.protobuf.Any getBad() {
    return bad_ == null ? com.google.protobuf.Any.getDefaultInstance() : bad_;
  }
  /**
   * <code>.google.protobuf.Any bad = 1;</code>
   */
  @java.lang.Override
  public com.google.protobuf.AnyOrBuilder getBadOrBuilder() {
    return bad_ == null ? com.google.protobuf.Any.getDefaultInstance() : bad_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getBad());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getBad());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.codebinge.firestore.codec.testdata.v1.AnyField)) {
      return super.equals(obj);
    }
    com.codebinge.firestore.codec.testdata.v1.AnyField other = (com.codebinge.firestore.codec.testdata.v1.AnyField) obj;

    if (hasBad() != other.hasBad()) return false;
    if (hasBad()) {
      if (!getBad()
          .equals(other.getBad())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasBad()) {
      hash = (37 * hash) + BAD_FIELD_NUMBER;
      hash = (53 * hash) + getBad().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.codebinge.firestore.codec.testdata.v1.AnyField parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.codebinge.firestore.codec.testdata.v1.AnyField parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.codebinge.firestore.codec.testdata.v1.AnyField parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.codebinge.firestore.codec.testdata.v1.AnyField parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.codebinge.firestore.codec.testdata.v1.AnyField parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.codebinge.firestore.codec.testdata.v1.AnyField parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.codebinge.firestore.codec.testdata.v1.AnyField parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.codebinge.firestore.codec.testdata.v1.AnyField parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.codebinge.firestore.codec.testdata.v1.AnyField parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.codebinge.firestore.codec.testdata.v1.AnyField parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.codebinge.firestore.codec.testdata.v1.AnyField parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.codebinge.firestore.codec.testdata.v1.AnyField parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.codebinge.firestore.codec.testdata.v1.AnyField prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * google.protobuf.Any is not supported (§3.4).
   * </pre>
   *
   * Protobuf type {@code codebinge.firestore.codec.testdata.v1.AnyField}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:codebinge.firestore.codec.testdata.v1.AnyField)
      com.codebinge.firestore.codec.testdata.v1.AnyFieldOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.codebinge.firestore.codec.testdata.v1.Invalid.internal_static_codebinge_firestore_codec_testdata_v1_AnyField_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.codebinge.firestore.codec.testdata.v1.Invalid.internal_static_codebinge_firestore_codec_testdata_v1_AnyField_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.codebinge.firestore.codec.testdata.v1.AnyField.class, com.codebinge.firestore.codec.testdata.v1.AnyField.Builder.class);
    }

    // Construct using com.codebinge.firestore.codec.testdata.v1.AnyField.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetBadFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      bad_ = null;
      if (badBuilder_ != null) {
        badBuilder_.dispose();
        badBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.codebinge.firestore.codec.testdata.v1.Invalid.internal_static_codebinge_firestore_codec_testdata_v1_AnyField_descriptor;
    }

    @java.lang.Override
    public com.codebinge.firestore.codec.testdata.v1.AnyField getDefaultInstanceForType() {
      return com.codebinge.firestore.codec.testdata.v1.AnyField.getDefaultInstance();
    }

    @java.lang.Override
    public com.codebinge.firestore.codec.testdata.v1.AnyField build() {
      com.codebinge.firestore.codec.testdata.v1.AnyField result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.codebinge.firestore.codec.testdata.v1.AnyField buildPartial() {
      com.codebinge.firestore.codec.testdata.v1.AnyField result = new com.codebinge.firestore.codec.testdata.v1.AnyField(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.codebinge.firestore.codec.testdata.v1.AnyField result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.bad_ = badBuilder_ == null
            ? bad_
            : badBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.codebinge.firestore.codec.testdata.v1.AnyField) {
        return mergeFrom((com.codebinge.firestore.codec.testdata.v1.AnyField)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.codebinge.firestore.codec.testdata.v1.AnyField other) {
      if (other == com.codebinge.firestore.codec.testdata.v1.AnyField.getDefaultInstance()) return this;
      if (other.hasBad()) {
        mergeBad(other.getBad());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetBadFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Any bad_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> badBuilder_;
    /**
     * <code>.google.protobuf.Any bad = 1;</code>
     * @return Whether the bad field is set.
     */
    public boolean hasBad() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.google.protobuf.Any bad = 1;</code>
     * @return The bad.
     */
    public com.google.protobuf.Any getBad() {
      if (badBuilder_ == null) {
        return bad_ == null ? com.google.protobuf.Any.getDefaultInstance() : bad_;
      } else {
        return badBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Any bad = 1;</code>
     */
    public Builder setBad(com.google.protobuf.Any value) {
      if (badBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        bad_ = value;
      } else {
        badBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Any bad = 1;</code>
     */
    public Builder setBad(
        com.google.protobuf.Any.Builder builderForValue) {
      if (badBuilder_ == null) {
        bad_ = builderForValue.build();
      } else {
        badBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Any bad = 1;</code>
     */
    public Builder mergeBad(com.google.protobuf.Any value) {
      if (badBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          bad_ != null &&
          bad_ != com.google.protobuf.Any.getDefaultInstance()) {
          getBadBuilder().mergeFrom(value);
        } else {
          bad_ = value;
        }
      } else {
        badBuilder_.mergeFrom(value);
      }
      if (bad_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Any bad = 1;</code>
     */
    public Builder clearBad() {
      bitField0_ = (bitField0_ & ~0x00000001);
      bad_ = null;
      if (badBuilder_ != null) {
        badBuilder_.dispose();
        badBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Any bad = 1;</code>
     */
    public com.google.protobuf.Any.Builder getBadBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetBadFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Any bad = 1;</code>
     */
    public com.google.protobuf.AnyOrBuilder getBadOrBuilder() {
      if (badBuilder_ != null) {
        return badBuilder_.getMessageOrBuilder();
      } else {
        return bad_ == null ?
            com.google.protobuf.Any.getDefaultInstance() : bad_;
      }
    }
    /**
     * <code>.google.protobuf.Any bad = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
        internalGetBadFieldBuilder() {
      if (badBuilder_ == null) {
        badBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                getBad(),
                getParentForChildren(),
                isClean());
        bad_ = null;
      }
      return badBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:codebinge.firestore.codec.testdata.v1.AnyField)
  }

  // @@protoc_insertion_point(class_scope:codebinge.firestore.codec.testdata.v1.AnyField)
  private static final com.codebinge.firestore.codec.testdata.v1.AnyField DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.codebinge.firestore.codec.testdata.v1.AnyField();
  }

  public static com.codebinge.firestore.codec.testdata.v1.AnyField getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AnyField>
      PARSER = new com.google.protobuf.AbstractParser<AnyField>() {
    @java.lang.Override
    public AnyField parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AnyField> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AnyField> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.codebinge.firestore.codec.testdata.v1.AnyField getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

