// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: testdata.proto
// Protobuf Java Version: 4.33.3

package com.codebinge.firestore.codec.testdata.v1;

@com.google.protobuf.Generated
public interface ChoiceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:codebinge.firestore.codec.testdata.v1.Choice)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string text = 1;</code>
   * @return Whether the text field is set.
   */
  boolean hasText();
  /**
   * <code>string text = 1;</code>
   * @return The text.
   */
  java.lang.String getText();
  /**
   * <code>string text = 1;</code>
   * @return The bytes for text.
   */
  com.google.protobuf.ByteString
      getTextBytes();

  /**
   * <code>int32 number = 2;</code>
   * @return Whether the number field is set.
   */
  boolean hasNumber();
  /**
   * <code>int32 number = 2;</code>
   * @return The number.
   */
  int getNumber();

  /**
   * <code>.codebinge.firestore.codec.testdata.v1.Inner inner = 3;</code>
   * @return Whether the inner field is set.
   */
  boolean hasInner();
  /**
   * <code>.codebinge.firestore.codec.testdata.v1.Inner inner = 3;</code>
   * @return The inner.
   */
  com.codebinge.firestore.codec.testdata.v1.Inner getInner();
  /**
   * <code>.codebinge.firestore.codec.testdata.v1.Inner inner = 3;</code>
   */
  com.codebinge.firestore.codec.testdata.v1.InnerOrBuilder getInnerOrBuilder();

  com.codebinge.firestore.codec.testdata.v1.Choice.KindCase getKindCase();
}
