// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: testdata.proto
// Protobuf Java Version: 4.33.3

package com.codebinge.firestore.codec.testdata.v1;

/**
 * <pre>
 * Nested messages, repeated fields, and maps (§5).
 * </pre>
 *
 * Protobuf type {@code codebinge.firestore.codec.testdata.v1.Composite}
 */
@com.google.protobuf.Generated
public final class Composite extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:codebinge.firestore.codec.testdata.v1.Composite)
    CompositeOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 3,
      /* suffix= */ "",
      "Composite");
  }
  // Use Composite.newBuilder() to construct.
  private Composite(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Composite() {
    strings_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    messages_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.codebinge.firestore.codec.testdata.v1.Testdata.internal_static_codebinge_firestore_codec_testdata_v1_Composite_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
    switch (number) {
      case 4:
        return internalGetStringMap();
      case 5:
        return internalGetMessageMap();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.codebinge.firestore.codec.testdata.v1.Testdata.internal_static_codebinge_firestore_codec_testdata_v1_Composite_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.codebinge.firestore.codec.testdata.v1.Composite.class, com.codebinge.firestore.codec.testdata.v1.Composite.Builder.class);
  }

  private int bitField0_;
  public static final int SINGLE_FIELD_NUMBER = 1;
  private com.codebinge.firestore.codec.testdata.v1.Inner single_;
  /**
   * <code>.codebinge.firestore.codec.testdata.v1.Inner single = 1;</code>
   * @return Whether the single field is set.
   */
  @java.lang.Override
  public boolean hasSingle() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.codebinge.firestore.codec.testdata.v1.Inner single = 1;</code>
   * @return The single.
   */
  @java.lang.Override
  public com.codebinge.firestore.codec.testdata.v1.Inner getSingle() {
    return single_ == null ? com.codebinge.firestore.codec.testdata.v1.Inner.getDefaultInstance() : single_;
  }
  /**
   * <code>.codebinge.firestore.codec.testdata.v1.Inner single = 1;</code>
   */
  @java.lang.Override
  public com.codebinge.firestore.codec.testdata.v1.InnerOrBuilder getSingleOrBuilder() {
    return single_ == null ? com.codebinge.firestore.codec.testdata.v1.Inner.getDefaultInstance() : single_;
  }

  public static final int STRINGS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList strings_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string strings = 2;</code>
   * @return A list containing the strings.
   */
  public com.google.protobuf.ProtocolStringList
      getStringsList() {
    return strings_;
  }
  /**
   * <code>repeated string strings = 2;</code>
   * @return The count of strings.
   */
  public int getStringsCount() {
    return strings_.size();
  }
  /**
   * <code>repeated string strings = 2;</code>
   * @param index The index of the element to return.
   * @return The strings at the given index.
   */
  public java.lang.String getStrings(int index) {
    return strings_.get(index);
  }
  /**
   * <code>repeated string strings = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the strings at the given index.
   */
  public com.google.protobuf.ByteString
      getStringsBytes(int index) {
    return strings_.getByteString(index);
  }

  public static final int MESSAGES_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<com.codebinge.firestore.codec.testdata.v1.Inner> messages_;
  /**
   * <code>repeated .codebinge.firestore.codec.testdata.v1.Inner messages = 3;</code>
   */
  @java.lang.Override
  public java.util.List<com.codebinge.firestore.codec.testdata.v1.Inner> getMessagesList() {
    return messages_;
  }
  /**
   * <code>repeated .codebinge.firestore.codec.testdata.v1.Inner messages = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.codebinge.firestore.codec.testdata.v1.InnerOrBuilder> 
      getMessagesOrBuilderList() {
    return messages_;
  }
  /**
   * <code>repeated .codebinge.firestore.codec.testdata.v1.Inner messages = 3;</code>
   */
  @java.lang.Override
  public int getMessagesCount() {
    return messages_.size();
  }
  /**
   * <code>repeated .codebinge.firestore.codec.testdata.v1.Inner messages = 3;</code>
   */
  @java.lang.Override
  public com.codebinge.firestore.codec.testdata.v1.Inner getMessages(int index) {
    return messages_.get(index);
  }
  /**
   * <code>repeated .codebinge.firestore.codec.testdata.v1.Inner messages = 3;</code>
   */
  @java.lang.Override
  public com.codebinge.firestore.codec.testdata.v1.InnerOrBuilder getMessagesOrBuilder(
      int index) {
    return messages_.get(index);
  }

  public static final int STRING_MAP_FIELD_NUMBER = 4;
  private static final class StringMapDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.codebinge.firestore.codec.testdata.v1.Testdata.internal_static_codebinge_firestore_codec_testdata_v1_Composite_StringMapEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> stringMap_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetStringMap() {
    if (stringMap_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          StringMapDefaultEntryHolder.defaultEntry);
    }
    return stringMap_;
  }
  public int getStringMapCount() {
    return internalGetStringMap().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; string_map = 4;</code>
   */
  @java.lang.Override
  public boolean containsStringMap(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetStringMap().getMap().containsKey(key);
  }
  /**
   * Use {@link #getStringMapMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getStringMap() {
    return getStringMapMap();
  }
  /**
   * <code>map&lt;string, string&gt; string_map = 4;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, java.lang.String> getStringMapMap() {
    return internalGetStringMap().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; string_map = 4;</code>
   */
  @java.lang.Override
  public /* nullable */
java.lang.String getStringMapOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetStringMap().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; string_map = 4;</code>
   */
  @java.lang.Override
  public java.lang.String getStringMapOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetStringMap().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int MESSAGE_MAP_FIELD_NUMBER = 5;
  private static final class MessageMapDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, com.codebinge.firestore.codec.testdata.v1.Inner> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, com.codebinge.firestore.codec.testdata.v1.Inner>newDefaultInstance(
                com.codebinge.firestore.codec.testdata.v1.Testdata.internal_static_codebinge_firestore_codec_testdata_v1_Composite_MessageMapEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                com.codebinge.firestore.codec.testdata.v1.Inner.getDefaultInstance());
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, com.codebinge.firestore.codec.testdata.v1.Inner> messageMap_;
  private com.google.protobuf.MapField<java.lang.String, com.codebinge.firestore.codec.testdata.v1.Inner>
  internalGetMessageMap() {
    if (messageMap_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          MessageMapDefaultEntryHolder.defaultEntry);
    }
    return messageMap_;
  }
  public int getMessageMapCount() {
    return internalGetMessageMap().getMap().size();
  }
  /**
   * <code>map&lt;string, .codebinge.firestore.codec.testdata.v1.Inner&gt; message_map = 5;</code>
   */
  @java.lang.Override
  public boolean containsMessageMap(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetMessageMap().getMap().containsKey(key);
  }
  /**
   * Use {@link #getMessageMapMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, com.codebinge.firestore.codec.testdata.v1.Inner> getMessageMap() {
    return getMessageMapMap();
  }
  /**
   * <code>map&lt;string, .codebinge.firestore.codec.testdata.v1.Inner&gt; message_map = 5;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, com.codebinge.firestore.codec.testdata.v1.Inner> getMessageMapMap() {
    return internalGetMessageMap().getMap();
  }
  /**
   * <code>map&lt;string, .codebinge.firestore.codec.testdata.v1.Inner&gt; message_map = 5;</code>
   */
  @java.lang.Override
  public /* nullable */
com.codebinge.firestore.codec.testdata.v1.Inner getMessageMapOrDefault(
      java.lang.String key,
      /* nullable */
com.codebinge.firestore.codec.testdata.v1.Inner defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, com.codebinge.firestore.codec.testdata.v1.Inner> map =
        internalGetMessageMap().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, .codebinge.firestore.codec.testdata.v1.Inner&gt; message_map = 5;</code>
   */
  @java.lang.Override
  public com.codebinge.firestore.codec.testdata.v1.Inner getMessageMapOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, com.codebinge.firestore.codec.testdata.v1.Inner> map =
        internalGetMessageMap().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getSingle());
    }
    for (int i = 0; i < strings_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, strings_.getRaw(i));
    }
    for (int i = 0; i < messages_.size(); i++) {
      output.writeMessage(3, messages_.get(i));
    }
    com.google.protobuf.GeneratedMessage
      .serializeStringMapTo(
        output,
        internalGetStringMap(),
        StringMapDefaultEntryHolder.defaultEntry,
        4);
    com.google.protobuf.GeneratedMessage
      .serializeStringMapTo(
        output,
        internalGetMessageMap(),
        MessageMapDefaultEntryHolder.defaultEntry,
        5);
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getSingle());
    }
    {
      int dataSize = 0;
      for (int i = 0; i < strings_.size(); i++) {
        dataSize += computeStringSizeNoTag(strings_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getStringsList().size();
    }
    for (int i = 0; i < messages_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, messages_.get(i));
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetStringMap().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      stringMap__ = StringMapDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, stringMap__);
    }
    for (java.util.Map.Entry<java.lang.String, com.codebinge.firestore.codec.testdata.v1.Inner> entry
         : internalGetMessageMap().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, com.codebinge.firestore.codec.testdata.v1.Inner>
      messageMap__ = MessageMapDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, messageMap__);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.codebinge.firestore.codec.testdata.v1.Composite)) {
      return super.equals(obj);
    }
    com.codebinge.firestore.codec.testdata.v1.Composite other = (com.codebinge.firestore.codec.testdata.v1.Composite) obj;

    if (hasSingle() != other.hasSingle()) return false;
    if (hasSingle()) {
      if (!getSingle()
          .equals(other.getSingle())) return false;
    }
    if (!getStringsList()
        .equals(other.getStringsList())) return false;
    if (!getMessagesList()
        .equals(other.getMessagesList())) return false;
    if (!internalGetStringMap().equals(
        other.internalGetStringMap())) return false;
    if (!internalGetMessageMap().equals(
        other.internalGetMessageMap())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasSingle()) {
      hash = (37 * hash) + SINGLE_FIELD_NUMBER;
      hash = (53 * hash) + getSingle().hashCode();
    }
    if (getStringsCount() > 0) {
      hash = (37 * hash) + STRINGS_FIELD_NUMBER;
      hash = (53 * hash) + getStringsList().hashCode();
    }
    if (getMessagesCount() > 0) {
      hash = (37 * hash) + MESSAGES_FIELD_NUMBER;
      hash = (53 * hash) + getMessagesList().hashCode();
    }
    if (!internalGetStringMap().getMap().isEmpty()) {
      hash = (37 * hash) + STRING_MAP_FIELD_NUMBER;
      hash = (53 * hash) + internalGetStringMap().hashCode();
    }
    if (!internalGetMessageMap().getMap().isEmpty()) {
      hash = (37 * hash) + MESSAGE_MAP_FIELD_NUMBER;
      hash = (53 * hash) + internalGetMessageMap().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.codebinge.firestore.codec.testdata.v1.Composite parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Composite parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Composite parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Composite parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Composite parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Composite parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Composite parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Composite parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.codebinge.firestore.codec.testdata.v1.Composite parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.codebinge.firestore.codec.testdata.v1.Composite parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Composite parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Composite parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.codebinge.firestore.codec.testdata.v1.Composite prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Nested messages, repeated fields, and maps (§5).
   * </pre>
   *
   * Protobuf type {@code codebinge.firestore.codec.testdata.v1.Composite}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:codebinge.firestore.codec.testdata.v1.Composite)
      com.codebinge.firestore.codec.testdata.v1.CompositeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.codebinge.firestore.codec.testdata.v1.Testdata.internal_static_codebinge_firestore_codec_testdata_v1_Composite_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 4:
          return internalGetStringMap();
        case 5:
          return internalGetMessageMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
      switch (number) {
        case 4:
          return internalGetMutableStringMap();
        case 5:
          return internalGetMutableMessageMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.codebinge.firestore.codec.testdata.v1.Testdata.internal_static_codebinge_firestore_codec_testdata_v1_Composite_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.codebinge.firestore.codec.testdata.v1.Composite.class, com.codebinge.firestore.codec.testdata.v1.Composite.Builder.class);
    }

    // Construct using com.codebinge.firestore.codec.testdata.v1.Composite.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetSingleFieldBuilder();
        internalGetMessagesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      single_ = null;
      if (singleBuilder_ != null) {
        singleBuilder_.dispose();
        singleBuilder_ = null;
      }
      strings_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      if (messagesBuilder_ == null) {
        messages_ = java.util.Collections.emptyList();
      } else {
        messages_ = null;
        messagesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      internalGetMutableStringMap().clear();
      internalGetMutableMessageMap().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.codebinge.firestore.codec.testdata.v1.Testdata.internal_static_codebinge_firestore_codec_testdata_v1_Composite_descriptor;
    }

    @java.lang.Override
    public com.codebinge.firestore.codec.testdata.v1.Composite getDefaultInstanceForType() {
      return com.codebinge.firestore.codec.testdata.v1.Composite.getDefaultInstance();
    }

    @java.lang.Override
    public com.codebinge.firestore.codec.testdata.v1.Composite build() {
      com.codebinge.firestore.codec.testdata.v1.Composite result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.codebinge.firestore.codec.testdata.v1.Composite buildPartial() {
      com.codebinge.firestore.codec.testdata.v1.Composite result = new com.codebinge.firestore.codec.testdata.v1.Composite(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.codebinge.firestore.codec.testdata.v1.Composite result) {
      if (messagesBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          messages_ = java.util.Collections.unmodifiableList(messages_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.messages_ = messages_;
      } else {
        result.messages_ = messagesBuilder_.build();
      }
    }

    private void buildPartial0(com.codebinge.firestore.codec.testdata.v1.Composite result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.single_ = singleBuilder_ == null
            ? single_
            : singleBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        strings_.makeImmutable();
        result.strings_ = strings_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.stringMap_ = internalGetStringMap();
        result.stringMap_.makeImmutable();
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.messageMap_ = internalGetMessageMap().build(MessageMapDefaultEntryHolder.defaultEntry);
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.codebinge.firestore.codec.testdata.v1.Composite) {
        return mergeFrom((com.codebinge.firestore.codec.testdata.v1.Composite)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.codebinge.firestore.codec.testdata.v1.Composite other) {
      if (other == com.codebinge.firestore.codec.testdata.v1.Composite.getDefaultInstance()) return this;
      if (other.hasSingle()) {
        mergeSingle(other.getSingle());
      }
      if (!other.strings_.isEmpty()) {
        if (strings_.isEmpty()) {
          strings_ = other.strings_;
          bitField0_ |= 0x00000002;
        } else {
          ensureStringsIsMutable();
          strings_.addAll(other.strings_);
        }
        onChanged();
      }
      if (messagesBuilder_ == null) {
        if (!other.messages_.isEmpty()) {
          if (messages_.isEmpty()) {
            messages_ = other.messages_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureMessagesIsMutable();
            messages_.addAll(other.messages_);
          }
          onChanged();
        }
      } else {
        if (!other.messages_.isEmpty()) {
          if (messagesBuilder_.isEmpty()) {
            messagesBuilder_.dispose();
            messagesBuilder_ = null;
            messages_ = other.messages_;
            bitField0_ = (bitField0_ & ~0x00000004);
            messagesBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetMessagesFieldBuilder() : null;
          } else {
            messagesBuilder_.addAllMessages(other.messages_);
          }
        }
      }
      internalGetMutableStringMap().mergeFrom(
          other.internalGetStringMap());
      bitField0_ |= 0x00000008;
      internalGetMutableMessageMap().mergeFrom(
          other.internalGetMessageMap());
      bitField0_ |= 0x00000010;
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetSingleFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureStringsIsMutable();
              strings_.add(s);
              break;
            } // case 18
            case 26: {
              com.codebinge.firestore.codec.testdata.v1.Inner m =
                  input.readMessage(
                      com.codebinge.firestore.codec.testdata.v1.Inner.parser(),
                      extensionRegistry);
              if (messagesBuilder_ == null) {
                ensureMessagesIsMutable();
                messages_.add(m);
              } else {
                messagesBuilder_.addMessage(m);
              }
              break;
            } // case 26
            case 34: {
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              stringMap__ = input.readMessage(
                  StringMapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableStringMap().getMutableMap().put(
                  stringMap__.getKey(), stringMap__.getValue());
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              com.google.protobuf.MapEntry<java.lang.String, com.codebinge.firestore.codec.testdata.v1.Inner>
              messageMap__ = input.readMessage(
                  MessageMapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableMessageMap().ensureBuilderMap().put(
                  messageMap__.getKey(), messageMap__.getValue());
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.codebinge.firestore.codec.testdata.v1.Inner single_;
    private com.google.protobuf.SingleFieldBuilder<
        com.codebinge.firestore.codec.testdata.v1.Inner, com.codebinge.firestore.codec.testdata.v1.Inner.Builder, com.codebinge.firestore.codec.testdata.v1.InnerOrBuilder> singleBuilder_;
    /**
     * <code>.codebinge.firestore.codec.testdata.v1.Inner single = 1;</code>
     * @return Whether the single field is set.
     */
    public boolean hasSingle() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.codebinge.firestore.codec.testdata.v1.Inner single = 1;</code>
     * @return The single.
     */
    public com.codebinge.firestore.codec.testdata.v1.Inner getSingle() {
      if (singleBuilder_ == null) {
        return single_ == null ? com.codebinge.firestore.codec.testdata.v1.Inner.getDefaultInstance() : single_;
      } else {
        return singleBuilder_.getMessage();
      }
    }
    /**
     * <code>.codebinge.firestore.codec.testdata.v1.Inner single = 1;</code>
     */
    public Builder setSingle(com.codebinge.firestore.codec.testdata.v1.Inner value) {
      if (singleBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        single_ = value;
      } else {
        singleBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.codebinge.firestore.codec.testdata.v1.Inner single = 1;</code>
     */
    public Builder setSingle(
        com.codebinge.firestore.codec.testdata.v1.Inner.Builder builderForValue) {
      if (singleBuilder_ == null) {
        single_ = builderForValue.build();
      } else {
        singleBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.codebinge.firestore.codec.testdata.v1.Inner single = 1;</code>
     */
    public Builder mergeSingle(com.codebinge.firestore.codec.testdata.v1.Inner value) {
      if (singleBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          single_ != null &&
          single_ != com.codebinge.firestore.codec.testdata.v1.Inner.getDefaultInstance()) {
          getSingleBuilder().mergeFrom(value);
        } else {
          single_ = value;
        }
      } else {
        singleBuilder_.mergeFrom(value);
      }
      if (single_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.codebinge.firestore.codec.testdata.v1.Inner single = 1;</code>
     */
    public Builder clearSingle() {
      bitField0_ = (bitField0_ & ~0x00000001);
      single_ = null;
      if (singleBuilder_ != null) {
        singleBuilder_.dispose();
        singleBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.codebinge.firestore.codec.testdata.v1.Inner single = 1;</code>
     */
    public com.codebinge.firestore.codec.testdata.v1.Inner.Builder getSingleBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetSingleFieldBuilder().getBuilder();
    }
    /**
     * <code>.codebinge.firestore.codec.testdata.v1.Inner single = 1;</code>
     */
    public com.codebinge.firestore.codec.testdata.v1.InnerOrBuilder getSingleOrBuilder() {
      if (singleBuilder_ != null) {
        return singleBuilder_.getMessageOrBuilder();
      } else {
        return single_ == null ?
            com.codebinge.firestore.codec.testdata.v1.Inner.getDefaultInstance() : single_;
      }
    }
    /**
     * <code>.codebinge.firestore.codec.testdata.v1.Inner single = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.codebinge.firestore.codec.testdata.v1.Inner, com.codebinge.firestore.codec.testdata.v1.Inner.Builder, com.codebinge.firestore.codec.testdata.v1.InnerOrBuilder> 
        internalGetSingleFieldBuilder() {
      if (singleBuilder_ == null) {
        singleBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.codebinge.firestore.codec.testdata.v1.Inner, com.codebinge.firestore.codec.testdata.v1.Inner.Builder, com.codebinge.firestore.codec.testdata.v1.InnerOrBuilder>(
                getSingle(),
                getParentForChildren(),
                isClean());
        single_ = null;
      }
      return singleBuilder_;
    }

    private com.google.protobuf.LazyStringArrayList strings_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureStringsIsMutable() {
      if (!strings_.isModifiable()) {
        strings_ = new com.google.protobuf.LazyStringArrayList(strings_);
      }
      bitField0_ |= 0x00000002;
    }
    /**
     * <code>repeated string strings = 2;</code>
     * @return A list containing the strings.
     */
    public com.google.protobuf.ProtocolStringList
        getStringsList() {
      strings_.makeImmutable();
      return strings_;
    }
    /**
     * <code>repeated string strings = 2;</code>
     * @return The count of strings.
     */
    public int getStringsCount() {
      return strings_.size();
    }
    /**
     * <code>repeated string strings = 2;</code>
     * @param index The index of the element to return.
     * @return The strings at the given index.
     */
    public java.lang.String getStrings(int index) {
      return strings_.get(index);
    }
    /**
     * <code>repeated string strings = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the strings at the given index.
     */
    public com.google.protobuf.ByteString
        getStringsBytes(int index) {
      return strings_.getByteString(index);
    }
    /**
     * <code>repeated string strings = 2;</code>
     * @param index The index to set the value at.
     * @param value The strings to set.
     * @return This builder for chaining.
     */
    public Builder setStrings(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureStringsIsMutable();
      strings_.set(index, value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string strings = 2;</code>
     * @param value The strings to add.
     * @return This builder for chaining.
     */
    public Builder addStrings(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureStringsIsMutable();
      strings_.add(value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string strings = 2;</code>
     * @param values The strings to add.
     * @return This builder for chaining.
     */
    public Builder addAllStrings(
        java.lang.Iterable<java.lang.String> values) {
      ensureStringsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, strings_);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string strings = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearStrings() {
      strings_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string strings = 2;</code>
     * @param value The bytes of the strings to add.
     * @return This builder for chaining.
     */
    public Builder addStringsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureStringsIsMutable();
      strings_.add(value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.util.List<com.codebinge.firestore.codec.testdata.v1.Inner> messages_ =
      java.util.Collections.emptyList();
    private void ensureMessagesIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        messages_ = new java.util.ArrayList<com.codebinge.firestore.codec.testdata.v1.Inner>(messages_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.codebinge.firestore.codec.testdata.v1.Inner, com.codebinge.firestore.codec.testdata.v1.Inner.Builder, com.codebinge.firestore.codec.testdata.v1.InnerOrBuilder> messagesBuilder_;

    /**
     * <code>repeated .codebinge.firestore.codec.testdata.v1.Inner messages = 3;</code>
     */
    public java.util.List<com.codebinge.firestore.codec.testdata.v1.Inner> getMessagesList() {
      if (messagesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(messages_);
      } else {
        return messagesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .codebinge.firestore.codec.testdata.v1.Inner messages = 3;</code>
     */
    public int getMessagesCount() {
      if (messagesBuilder_ == null) {
        return messages_.size();
      } else {
        return messagesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .codebinge.firestore.codec.testdata.v1.Inner messages = 3;</code>
     */
    public com.codebinge.firestore.codec.testdata.v1.Inner getMessages(int index) {
      if (messagesBuilder_ == null) {
        return messages_.get(index);
      } else {
        return messagesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .codebinge.firestore.codec.testdata.v1.Inner messages = 3;</code>
     */
    public Builder setMessages(
        int index, com.codebinge.firestore.codec.testdata.v1.Inner value) {
      if (messagesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMessagesIsMutable();
        messages_.set(index, value);
        onChanged();
      } else {
        messagesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .codebinge.firestore.codec.testdata.v1.Inner messages = 3;</code>
     */
    public Builder setMessages(
        int index, com.codebinge.firestore.codec.testdata.v1.Inner.Builder builderForValue) {
      if (messagesBuilder_ == null) {
        ensureMessagesIsMutable();
        messages_.set(index, builderForValue.build());
        onChanged();
      } else {
        messagesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .codebinge.firestore.codec.testdata.v1.Inner messages = 3;</code>
     */
    public Builder addMessages(com.codebinge.firestore.codec.testdata.v1.Inner value) {
      if (messagesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMessagesIsMutable();
        messages_.add(value);
        onChanged();
      } else {
        messagesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .codebinge.firestore.codec.testdata.v1.Inner messages = 3;</code>
     */
    public Builder addMessages(
        int index, com.codebinge.firestore.codec.testdata.v1.Inner value) {
      if (messagesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMessagesIsMutable();
        messages_.add(index, value);
        onChanged();
      } else {
        messagesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .codebinge.firestore.codec.testdata.v1.Inner messages = 3;</code>
     */
    public Builder addMessages(
        com.codebinge.firestore.codec.testdata.v1.Inner.Builder builderForValue) {
      if (messagesBuilder_ == null) {
        ensureMessagesIsMutable();
        messages_.add(builderForValue.build());
        onChanged();
      } else {
        messagesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .codebinge.firestore.codec.testdata.v1.Inner messages = 3;</code>
     */
    public Builder addMessages(
        int index, com.codebinge.firestore.codec.testdata.v1.Inner.Builder builderForValue) {
      if (messagesBuilder_ == null) {
        ensureMessagesIsMutable();
        messages_.add(index, builderForValue.build());
        onChanged();
      } else {
        messagesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .codebinge.firestore.codec.testdata.v1.Inner messages = 3;</code>
     */
    public Builder addAllMessages(
        java.lang.Iterable<? extends com.codebinge.firestore.codec.testdata.v1.Inner> values) {
      if (messagesBuilder_ == null) {
        ensureMessagesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, messages_);
        onChanged();
      } else {
        messagesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .codebinge.firestore.codec.testdata.v1.Inner messages = 3;</code>
     */
    public Builder clearMessages() {
      if (messagesBuilder_ == null) {
        messages_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        messagesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .codebinge.firestore.codec.testdata.v1.Inner messages = 3;</code>
     */
    public Builder removeMessages(int index) {
      if (messagesBuilder_ == null) {
        ensureMessagesIsMutable();
        messages_.remove(index);
        onChanged();
      } else {
        messagesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .codebinge.firestore.codec.testdata.v1.Inner messages = 3;</code>
     */
    public com.codebinge.firestore.codec.testdata.v1.Inner.Builder getMessagesBuilder(
        int index) {
      return internalGetMessagesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .codebinge.firestore.codec.testdata.v1.Inner messages = 3;</code>
     */
    public com.codebinge.firestore.codec.testdata.v1.InnerOrBuilder getMessagesOrBuilder(
        int index) {
      if (messagesBuilder_ == null) {
        return messages_.get(index);  } else {
        return messagesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .codebinge.firestore.codec.testdata.v1.Inner messages = 3;</code>
     */
    public java.util.List<? extends com.codebinge.firestore.codec.testdata.v1.InnerOrBuilder> 
         getMessagesOrBuilderList() {
      if (messagesBuilder_ != null) {
        return messagesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(messages_);
      }
    }
    /**
     * <code>repeated .codebinge.firestore.codec.testdata.v1.Inner messages = 3;</code>
     */
    public com.codebinge.firestore.codec.testdata.v1.Inner.Builder addMessagesBuilder() {
      return internalGetMessagesFieldBuilder().addBuilder(
          com.codebinge.firestore.codec.testdata.v1.Inner.getDefaultInstance());
    }
    /**
     * <code>repeated .codebinge.firestore.codec.testdata.v1.Inner messages = 3;</code>
     */
    public com.codebinge.firestore.codec.testdata.v1.Inner.Builder addMessagesBuilder(
        int index) {
      return internalGetMessagesFieldBuilder().addBuilder(
          index, com.codebinge.firestore.codec.testdata.v1.Inner.getDefaultInstance());
    }
    /**
     * <code>repeated .codebinge.firestore.codec.testdata.v1.Inner messages = 3;</code>
     */
    public java.util.List<com.codebinge.firestore.codec.testdata.v1.Inner.Builder> 
         getMessagesBuilderList() {
      return internalGetMessagesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.codebinge.firestore.codec.testdata.v1.Inner, com.codebinge.firestore.codec.testdata.v1.Inner.Builder, com.codebinge.firestore.codec.testdata.v1.InnerOrBuilder> 
        internalGetMessagesFieldBuilder() {
      if (messagesBuilder_ == null) {
        messagesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.codebinge.firestore.codec.testdata.v1.Inner, com.codebinge.firestore.codec.testdata.v1.Inner.Builder, com.codebinge.firestore.codec.testdata.v1.InnerOrBuilder>(
                messages_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        messages_ = null;
      }
      return messagesBuilder_;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> stringMap_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetStringMap() {
      if (stringMap_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            StringMapDefaultEntryHolder.defaultEntry);
      }
      return stringMap_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetMutableStringMap() {
      if (stringMap_ == null) {
        stringMap_ = com.google.protobuf.MapField.newMapField(
            StringMapDefaultEntryHolder.defaultEntry);
      }
      if (!stringMap_.isMutable()) {
        stringMap_ = stringMap_.copy();
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return stringMap_;
    }
    public int getStringMapCount() {
      return internalGetStringMap().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; string_map = 4;</code>
     */
    @java.lang.Override
    public boolean containsStringMap(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetStringMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getStringMapMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getStringMap() {
      return getStringMapMap();
    }
    /**
     * <code>map&lt;string, string&gt; string_map = 4;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getStringMapMap() {
      return internalGetStringMap().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; string_map = 4;</code>
     */
    @java.lang.Override
    public /* nullable */
java.lang.String getStringMapOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetStringMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; string_map = 4;</code>
     */
    @java.lang.Override
    public java.lang.String getStringMapOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetStringMap().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearStringMap() {
      bitField0_ = (bitField0_ & ~0x00000008);
      internalGetMutableStringMap().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; string_map = 4;</code>
     */
    public Builder removeStringMap(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableStringMap().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
        getMutableStringMap() {
      bitField0_ |= 0x00000008;
      return internalGetMutableStringMap().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; string_map = 4;</code>
     */
    public Builder putStringMap(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableStringMap().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000008;
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; string_map = 4;</code>
     */
    public Builder putAllStringMap(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableStringMap().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000008;
      return this;
    }

    private static final class MessageMapConverter implements com.google.protobuf.MapFieldBuilder.Converter<java.lang.String, com.codebinge.firestore.codec.testdata.v1.InnerOrBuilder, com.codebinge.firestore.codec.testdata.v1.Inner> {
      @java.lang.Override
      public com.codebinge.firestore.codec.testdata.v1.Inner build(com.codebinge.firestore.codec.testdata.v1.InnerOrBuilder val) {
        if (val instanceof com.codebinge.firestore.codec.testdata.v1.Inner) { return (com.codebinge.firestore.codec.testdata.v1.Inner) val; }
        return ((com.codebinge.firestore.codec.testdata.v1.Inner.Builder) val).build();
      }

      @java.lang.Override
      public com.google.protobuf.MapEntry<java.lang.String, com.codebinge.firestore.codec.testdata.v1.Inner> defaultEntry() {
        return MessageMapDefaultEntryHolder.defaultEntry;
      }
    };
    private static final MessageMapConverter messageMapConverter = new MessageMapConverter();

    private com.google.protobuf.MapFieldBuilder<
        java.lang.String, com.codebinge.firestore.codec.testdata.v1.InnerOrBuilder, com.codebinge.firestore.codec.testdata.v1.Inner, com.codebinge.firestore.codec.testdata.v1.Inner.Builder> messageMap_;
    private com.google.protobuf.MapFieldBuilder<java.lang.String, com.codebinge.firestore.codec.testdata.v1.InnerOrBuilder, com.codebinge.firestore.codec.testdata.v1.Inner, com.codebinge.firestore.codec.testdata.v1.Inner.Builder>
        internalGetMessageMap() {
      if (messageMap_ == null) {
        return new com.google.protobuf.MapFieldBuilder<>(messageMapConverter);
      }
      return messageMap_;
    }
    private com.google.protobuf.MapFieldBuilder<java.lang.String, com.codebinge.firestore.codec.testdata.v1.InnerOrBuilder, com.codebinge.firestore.codec.testdata.v1.Inner, com.codebinge.firestore.codec.testdata.v1.Inner.Builder>
        internalGetMutableMessageMap() {
      if (messageMap_ == null) {
        messageMap_ = new com.google.protobuf.MapFieldBuilder<>(messageMapConverter);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return messageMap_;
    }
    public int getMessageMapCount() {
      return internalGetMessageMap().ensureBuilderMap().size();
    }
    /**
     * <code>map&lt;string, .codebinge.firestore.codec.testdata.v1.Inner&gt; message_map = 5;</code>
     */
    @java.lang.Override
    public boolean containsMessageMap(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetMessageMap().ensureBuilderMap().containsKey(key);
    }
    /**
     * Use {@link #getMessageMapMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.codebinge.firestore.codec.testdata.v1.Inner> getMessageMap() {
      return getMessageMapMap();
    }
    /**
     * <code>map&lt;string, .codebinge.firestore.codec.testdata.v1.Inner&gt; message_map = 5;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, com.codebinge.firestore.codec.testdata.v1.Inner> getMessageMapMap() {
      return internalGetMessageMap().getImmutableMap();
    }
    /**
     * <code>map&lt;string, .codebinge.firestore.codec.testdata.v1.Inner&gt; message_map = 5;</code>
     */
    @java.lang.Override
    public /* nullable */
com.codebinge.firestore.codec.testdata.v1.Inner getMessageMapOrDefault(
        java.lang.String key,
        /* nullable */
com.codebinge.firestore.codec.testdata.v1.Inner defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.codebinge.firestore.codec.testdata.v1.InnerOrBuilder> map = internalGetMutableMessageMap().ensureBuilderMap();
      return map.containsKey(key) ? messageMapConverter.build(map.get(key)) : defaultValue;
    }
    /**
     * <code>map&lt;string, .codebinge.firestore.codec.testdata.v1.Inner&gt; message_map = 5;</code>
     */
    @java.lang.Override
    public com.codebinge.firestore.codec.testdata.v1.Inner getMessageMapOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.codebinge.firestore.codec.testdata.v1.InnerOrBuilder> map = internalGetMutableMessageMap().ensureBuilderMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return messageMapConverter.build(map.get(key));
    }
    public Builder clearMessageMap() {
      bitField0_ = (bitField0_ & ~0x00000010);
      internalGetMutableMessageMap().clear();
      return this;
    }
    /**
     * <code>map&lt;string, .codebinge.firestore.codec.testdata.v1.Inner&gt; message_map = 5;</code>
     */
    public Builder removeMessageMap(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableMessageMap().ensureBuilderMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.codebinge.firestore.codec.testdata.v1.Inner>
        getMutableMessageMap() {
      bitField0_ |= 0x00000010;
      return internalGetMutableMessageMap().ensureMessageMap();
    }
    /**
     * <code>map&lt;string, .codebinge.firestore.codec.testdata.v1.Inner&gt; message_map = 5;</code>
     */
    public Builder putMessageMap(
        java.lang.String key,
        com.codebinge.firestore.codec.testdata.v1.Inner value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableMessageMap().ensureBuilderMap()
          .put(key, value);
      bitField0_ |= 0x00000010;
      return this;
    }
    /**
     * <code>map&lt;string, .codebinge.firestore.codec.testdata.v1.Inner&gt; message_map = 5;</code>
     */
    public Builder putAllMessageMap(
        java.util.Map<java.lang.String, com.codebinge.firestore.codec.testdata.v1.Inner> values) {
      for (java.util.Map.Entry<java.lang.String, com.codebinge.firestore.codec.testdata.v1.Inner> e : values.entrySet()) {
        if (e.getKey() == null || e.getValue() == null) {
          throw new NullPointerException();
        }
      }
      internalGetMutableMessageMap().ensureBuilderMap()
          .putAll(values);
      bitField0_ |= 0x00000010;
      return this;
    }
    /**
     * <code>map&lt;string, .codebinge.firestore.codec.testdata.v1.Inner&gt; message_map = 5;</code>
     */
    public com.codebinge.firestore.codec.testdata.v1.Inner.Builder putMessageMapBuilderIfAbsent(
        java.lang.String key) {
      java.util.Map<java.lang.String, com.codebinge.firestore.codec.testdata.v1.InnerOrBuilder> builderMap = internalGetMutableMessageMap().ensureBuilderMap();
      com.codebinge.firestore.codec.testdata.v1.InnerOrBuilder entry = builderMap.get(key);
      if (entry == null) {
        entry = com.codebinge.firestore.codec.testdata.v1.Inner.newBuilder();
        builderMap.put(key, entry);
      }
      if (entry instanceof com.codebinge.firestore.codec.testdata.v1.Inner) {
        entry = ((com.codebinge.firestore.codec.testdata.v1.Inner) entry).toBuilder();
        builderMap.put(key, entry);
      }
      return (com.codebinge.firestore.codec.testdata.v1.Inner.Builder) entry;
    }

    // @@protoc_insertion_point(builder_scope:codebinge.firestore.codec.testdata.v1.Composite)
  }

  // @@protoc_insertion_point(class_scope:codebinge.firestore.codec.testdata.v1.Composite)
  private static final com.codebinge.firestore.codec.testdata.v1.Composite DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.codebinge.firestore.codec.testdata.v1.Composite();
  }

  public static com.codebinge.firestore.codec.testdata.v1.Composite getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Composite>
      PARSER = new com.google.protobuf.AbstractParser<Composite>() {
    @java.lang.Override
    public Composite parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Composite> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Composite> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.codebinge.firestore.codec.testdata.v1.Composite getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

