// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: testdata.proto
// Protobuf Java Version: 4.33.3

package com.codebinge.firestore.codec.testdata.v1;

@com.google.protobuf.Generated
public interface CompositeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:codebinge.firestore.codec.testdata.v1.Composite)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.codebinge.firestore.codec.testdata.v1.Inner single = 1;</code>
   * @return Whether the single field is set.
   */
  boolean hasSingle();
  /**
   * <code>.codebinge.firestore.codec.testdata.v1.Inner single = 1;</code>
   * @return The single.
   */
  com.codebinge.firestore.codec.testdata.v1.Inner getSingle();
  /**
   * <code>.codebinge.firestore.codec.testdata.v1.Inner single = 1;</code>
   */
  com.codebinge.firestore.codec.testdata.v1.InnerOrBuilder getSingleOrBuilder();

  /**
   * <code>repeated string strings = 2;</code>
   * @return A list containing the strings.
   */
  java.util.List<java.lang.String>
      getStringsList();
  /**
   * <code>repeated string strings = 2;</code>
   * @return The count of strings.
   */
  int getStringsCount();
  /**
   * <code>repeated string strings = 2;</code>
   * @param index The index of the element to return.
   * @return The strings at the given index.
   */
  java.lang.String getStrings(int index);
  /**
   * <code>repeated string strings = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the strings at the given index.
   */
  com.google.protobuf.ByteString
      getStringsBytes(int index);

  /**
   * <code>repeated .codebinge.firestore.codec.testdata.v1.Inner messages = 3;</code>
   */
  java.util.List<com.codebinge.firestore.codec.testdata.v1.Inner> 
      getMessagesList();
  /**
   * <code>repeated .codebinge.firestore.codec.testdata.v1.Inner messages = 3;</code>
   */
  com.codebinge.firestore.codec.testdata.v1.Inner getMessages(int index);
  /**
   * <code>repeated .codebinge.firestore.codec.testdata.v1.Inner messages = 3;</code>
   */
  int getMessagesCount();
  /**
   * <code>repeated .codebinge.firestore.codec.testdata.v1.Inner messages = 3;</code>
   */
  java.util.List<? extends com.codebinge.firestore.codec.testdata.v1.InnerOrBuilder> 
      getMessagesOrBuilderList();
  /**
   * <code>repeated .codebinge.firestore.codec.testdata.v1.Inner messages = 3;</code>
   */
  com.codebinge.firestore.codec.testdata.v1.InnerOrBuilder getMessagesOrBuilder(
      int index);

  /**
   * <code>map&lt;string, string&gt; string_map = 4;</code>
   */
  int getStringMapCount();
  /**
   * <code>map&lt;string, string&gt; string_map = 4;</code>
   */
  boolean containsStringMap(
      java.lang.String key);
  /**
   * Use {@link #getStringMapMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getStringMap();
  /**
   * <code>map&lt;string, string&gt; string_map = 4;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getStringMapMap();
  /**
   * <code>map&lt;string, string&gt; string_map = 4;</code>
   */
  /* nullable */
java.lang.String getStringMapOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; string_map = 4;</code>
   */
  java.lang.String getStringMapOrThrow(
      java.lang.String key);

  /**
   * <code>map&lt;string, .codebinge.firestore.codec.testdata.v1.Inner&gt; message_map = 5;</code>
   */
  int getMessageMapCount();
  /**
   * <code>map&lt;string, .codebinge.firestore.codec.testdata.v1.Inner&gt; message_map = 5;</code>
   */
  boolean containsMessageMap(
      java.lang.String key);
  /**
   * Use {@link #getMessageMapMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, com.codebinge.firestore.codec.testdata.v1.Inner>
  getMessageMap();
  /**
   * <code>map&lt;string, .codebinge.firestore.codec.testdata.v1.Inner&gt; message_map = 5;</code>
   */
  java.util.Map<java.lang.String, com.codebinge.firestore.codec.testdata.v1.Inner>
  getMessageMapMap();
  /**
   * <code>map&lt;string, .codebinge.firestore.codec.testdata.v1.Inner&gt; message_map = 5;</code>
   */
  /* nullable */
com.codebinge.firestore.codec.testdata.v1.Inner getMessageMapOrDefault(
      java.lang.String key,
      /* nullable */
com.codebinge.firestore.codec.testdata.v1.Inner defaultValue);
  /**
   * <code>map&lt;string, .codebinge.firestore.codec.testdata.v1.Inner&gt; message_map = 5;</code>
   */
  com.codebinge.firestore.codec.testdata.v1.Inner getMessageMapOrThrow(
      java.lang.String key);
}
