// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: testdata.proto
// Protobuf Java Version: 4.33.3

package com.codebinge.firestore.codec.testdata.v1;

@com.google.protobuf.Generated
public interface DoublesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:codebinge.firestore.codec.testdata.v1.Doubles)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double nan_field = 1;</code>
   * @return The nanField.
   */
  double getNanField();

  /**
   * <code>double pos_inf_field = 2;</code>
   * @return The posInfField.
   */
  double getPosInfField();

  /**
   * <code>double neg_inf_field = 3;</code>
   * @return The negInfField.
   */
  double getNegInfField();
}
