// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: testdata.proto
// Protobuf Java Version: 4.33.3

package com.codebinge.firestore.codec.testdata.v1;

/**
 * <pre>
 * NaN and the infinities, which Firestore supports natively (§2).
 * </pre>
 *
 * Protobuf type {@code codebinge.firestore.codec.testdata.v1.Doubles}
 */
@com.google.protobuf.Generated
public final class Doubles extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:codebinge.firestore.codec.testdata.v1.Doubles)
    DoublesOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 3,
      /* suffix= */ "",
      "Doubles");
  }
  // Use Doubles.newBuilder() to construct.
  private Doubles(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Doubles() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.codebinge.firestore.codec.testdata.v1.Testdata.internal_static_codebinge_firestore_codec_testdata_v1_Doubles_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.codebinge.firestore.codec.testdata.v1.Testdata.internal_static_codebinge_firestore_codec_testdata_v1_Doubles_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.codebinge.firestore.codec.testdata.v1.Doubles.class, com.codebinge.firestore.codec.testdata.v1.Doubles.Builder.class);
  }

  public static final int NAN_FIELD_FIELD_NUMBER = 1;
  private double nanField_ = 0D;
  /**
   * <code>double nan_field = 1;</code>
   * @return The nanField.
   */
  @java.lang.Override
  public double getNanField() {
    return nanField_;
  }

  public static final int POS_INF_FIELD_FIELD_NUMBER = 2;
  private double posInfField_ = 0D;
  /**
   * <code>double pos_inf_field = 2;</code>
   * @return The posInfField.
   */
  @java.lang.Override
  public double getPosInfField() {
    return posInfField_;
  }

  public static final int NEG_INF_FIELD_FIELD_NUMBER = 3;
  private double negInfField_ = 0D;
  /**
   * <code>double neg_inf_field = 3;</code>
   * @return The negInfField.
   */
  @java.lang.Override
  public double getNegInfField() {
    return negInfField_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (java.lang.Double.doubleToRawLongBits(nanField_) != 0) {
      output.writeDouble(1, nanField_);
    }
    if (java.lang.Double.doubleToRawLongBits(posInfField_) != 0) {
      output.writeDouble(2, posInfField_);
    }
    if (java.lang.Double.doubleToRawLongBits(negInfField_) != 0) {
      output.writeDouble(3, negInfField_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (java.lang.Double.doubleToRawLongBits(nanField_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, nanField_);
    }
    if (java.lang.Double.doubleToRawLongBits(posInfField_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, posInfField_);
    }
    if (java.lang.Double.doubleToRawLongBits(negInfField_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, negInfField_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.codebinge.firestore.codec.testdata.v1.Doubles)) {
      return super.equals(obj);
    }
    com.codebinge.firestore.codec.testdata.v1.Doubles other = (com.codebinge.firestore.codec.testdata.v1.Doubles) obj;

    if (java.lang.Double.doubleToLongBits(getNanField())
        != java.lang.Double.doubleToLongBits(
            other.getNanField())) return false;
    if (java.lang.Double.doubleToLongBits(getPosInfField())
        != java.lang.Double.doubleToLongBits(
            other.getPosInfField())) return false;
    if (java.lang.Double.doubleToLongBits(getNegInfField())
        != java.lang.Double.doubleToLongBits(
            other.getNegInfField())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAN_FIELD_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getNanField()));
    hash = (37 * hash) + POS_INF_FIELD_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getPosInfField()));
    hash = (37 * hash) + NEG_INF_FIELD_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getNegInfField()));
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.codebinge.firestore.codec.testdata.v1.Doubles parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Doubles parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Doubles parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Doubles parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Doubles parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Doubles parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Doubles parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Doubles parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.codebinge.firestore.codec.testdata.v1.Doubles parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.codebinge.firestore.codec.testdata.v1.Doubles parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Doubles parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Doubles parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.codebinge.firestore.codec.testdata.v1.Doubles prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * NaN and the infinities, which Firestore supports natively (§2).
   * </pre>
   *
   * Protobuf type {@code codebinge.firestore.codec.testdata.v1.Doubles}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:codebinge.firestore.codec.testdata.v1.Doubles)
      com.codebinge.firestore.codec.testdata.v1.DoublesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.codebinge.firestore.codec.testdata.v1.Testdata.internal_static_codebinge_firestore_codec_testdata_v1_Doubles_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.codebinge.firestore.codec.testdata.v1.Testdata.internal_static_codebinge_firestore_codec_testdata_v1_Doubles_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.codebinge.firestore.codec.testdata.v1.Doubles.class, com.codebinge.firestore.codec.testdata.v1.Doubles.Builder.class);
    }

    // Construct using com.codebinge.firestore.codec.testdata.v1.Doubles.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      nanField_ = 0D;
      posInfField_ = 0D;
      negInfField_ = 0D;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.codebinge.firestore.codec.testdata.v1.Testdata.internal_static_codebinge_firestore_codec_testdata_v1_Doubles_descriptor;
    }

    @java.lang.Override
    public com.codebinge.firestore.codec.testdata.v1.Doubles getDefaultInstanceForType() {
      return com.codebinge.firestore.codec.testdata.v1.Doubles.getDefaultInstance();
    }

    @java.lang.Override
    public com.codebinge.firestore.codec.testdata.v1.Doubles build() {
      com.codebinge.firestore.codec.testdata.v1.Doubles result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.codebinge.firestore.codec.testdata.v1.Doubles buildPartial() {
      com.codebinge.firestore.codec.testdata.v1.Doubles result = new com.codebinge.firestore.codec.testdata.v1.Doubles(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.codebinge.firestore.codec.testdata.v1.Doubles result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.nanField_ = nanField_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.posInfField_ = posInfField_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.negInfField_ = negInfField_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.codebinge.firestore.codec.testdata.v1.Doubles) {
        return mergeFrom((com.codebinge.firestore.codec.testdata.v1.Doubles)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.codebinge.firestore.codec.testdata.v1.Doubles other) {
      if (other == com.codebinge.firestore.codec.testdata.v1.Doubles.getDefaultInstance()) return this;
      if (java.lang.Double.doubleToRawLongBits(other.getNanField()) != 0) {
        setNanField(other.getNanField());
      }
      if (java.lang.Double.doubleToRawLongBits(other.getPosInfField()) != 0) {
        setPosInfField(other.getPosInfField());
      }
      if (java.lang.Double.doubleToRawLongBits(other.getNegInfField()) != 0) {
        setNegInfField(other.getNegInfField());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {
              nanField_ = input.readDouble();
              bitField0_ |= 0x00000001;
              break;
            } // case 9
            case 17: {
              posInfField_ = input.readDouble();
              bitField0_ |= 0x00000002;
              break;
            } // case 17
            case 25: {
              negInfField_ = input.readDouble();
              bitField0_ |= 0x00000004;
              break;
            } // case 25
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private double nanField_ ;
    /**
     * <code>double nan_field = 1;</code>
     * @return The nanField.
     */
    @java.lang.Override
    public double getNanField() {
      return nanField_;
    }
    /**
     * <code>double nan_field = 1;</code>
     * @param value The nanField to set.
     * @return This builder for chaining.
     */
    public Builder setNanField(double value) {

      nanField_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>double nan_field = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearNanField() {
      bitField0_ = (bitField0_ & ~0x00000001);
      nanField_ = 0D;
      onChanged();
      return this;
    }

    private double posInfField_ ;
    /**
     * <code>double pos_inf_field = 2;</code>
     * @return The posInfField.
     */
    @java.lang.Override
    public double getPosInfField() {
      return posInfField_;
    }
    /**
     * <code>double pos_inf_field = 2;</code>
     * @param value The posInfField to set.
     * @return This builder for chaining.
     */
    public Builder setPosInfField(double value) {

      posInfField_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>double pos_inf_field = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPosInfField() {
      bitField0_ = (bitField0_ & ~0x00000002);
      posInfField_ = 0D;
      onChanged();
      return this;
    }

    private double negInfField_ ;
    /**
     * <code>double neg_inf_field = 3;</code>
     * @return The negInfField.
     */
    @java.lang.Override
    public double getNegInfField() {
      return negInfField_;
    }
    /**
     * <code>double neg_inf_field = 3;</code>
     * @param value The negInfField to set.
     * @return This builder for chaining.
     */
    public Builder setNegInfField(double value) {

      negInfField_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>double neg_inf_field = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearNegInfField() {
      bitField0_ = (bitField0_ & ~0x00000004);
      negInfField_ = 0D;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:codebinge.firestore.codec.testdata.v1.Doubles)
  }

  // @@protoc_insertion_point(class_scope:codebinge.firestore.codec.testdata.v1.Doubles)
  private static final com.codebinge.firestore.codec.testdata.v1.Doubles DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.codebinge.firestore.codec.testdata.v1.Doubles();
  }

  public static com.codebinge.firestore.codec.testdata.v1.Doubles getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Doubles>
      PARSER = new com.google.protobuf.AbstractParser<Doubles>() {
    @java.lang.Override
    public Doubles parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Doubles> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Doubles> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.codebinge.firestore.codec.testdata.v1.Doubles getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

