// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: testdata.proto
// Protobuf Java Version: 4.33.3

package com.codebinge.firestore.codec.testdata.v1;

@com.google.protobuf.Generated
public interface EnumsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:codebinge.firestore.codec.testdata.v1.Enums)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.codebinge.firestore.codec.testdata.v1.Status as_name = 1;</code>
   * @return The enum numeric value on the wire for asName.
   */
  int getAsNameValue();
  /**
   * <code>.codebinge.firestore.codec.testdata.v1.Status as_name = 1;</code>
   * @return The asName.
   */
  com.codebinge.firestore.codec.testdata.v1.Status getAsName();

  /**
   * <code>.codebinge.firestore.codec.testdata.v1.Status as_number = 2 [(.codebinge.firestore.codec.v1.field) = { ... }</code>
   * @return The enum numeric value on the wire for asNumber.
   */
  int getAsNumberValue();
  /**
   * <code>.codebinge.firestore.codec.testdata.v1.Status as_number = 2 [(.codebinge.firestore.codec.v1.field) = { ... }</code>
   * @return The asNumber.
   */
  com.codebinge.firestore.codec.testdata.v1.Status getAsNumber();
}
