// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: testdata.proto
// Protobuf Java Version: 4.33.3

package com.codebinge.firestore.codec.testdata.v1;

/**
 * <pre>
 * Both enum encodings (§4).
 * </pre>
 *
 * Protobuf type {@code codebinge.firestore.codec.testdata.v1.Enums}
 */
@com.google.protobuf.Generated
public final class Enums extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:codebinge.firestore.codec.testdata.v1.Enums)
    EnumsOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 3,
      /* suffix= */ "",
      "Enums");
  }
  // Use Enums.newBuilder() to construct.
  private Enums(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Enums() {
    asName_ = 0;
    asNumber_ = 0;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.codebinge.firestore.codec.testdata.v1.Testdata.internal_static_codebinge_firestore_codec_testdata_v1_Enums_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.codebinge.firestore.codec.testdata.v1.Testdata.internal_static_codebinge_firestore_codec_testdata_v1_Enums_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.codebinge.firestore.codec.testdata.v1.Enums.class, com.codebinge.firestore.codec.testdata.v1.Enums.Builder.class);
  }

  public static final int AS_NAME_FIELD_NUMBER = 1;
  private int asName_ = 0;
  /**
   * <code>.codebinge.firestore.codec.testdata.v1.Status as_name = 1;</code>
   * @return The enum numeric value on the wire for asName.
   */
  @java.lang.Override public int getAsNameValue() {
    return asName_;
  }
  /**
   * <code>.codebinge.firestore.codec.testdata.v1.Status as_name = 1;</code>
   * @return The asName.
   */
  @java.lang.Override public com.codebinge.firestore.codec.testdata.v1.Status getAsName() {
    com.codebinge.firestore.codec.testdata.v1.Status result = com.codebinge.firestore.codec.testdata.v1.Status.forNumber(asName_);
    return result == null ? com.codebinge.firestore.codec.testdata.v1.Status.UNRECOGNIZED : result;
  }

  public static final int AS_NUMBER_FIELD_NUMBER = 2;
  private int asNumber_ = 0;
  /**
   * <code>.codebinge.firestore.codec.testdata.v1.Status as_number = 2 [(.codebinge.firestore.codec.v1.field) = { ... }</code>
   * @return The enum numeric value on the wire for asNumber.
   */
  @java.lang.Override public int getAsNumberValue() {
    return asNumber_;
  }
  /**
   * <code>.codebinge.firestore.codec.testdata.v1.Status as_number = 2 [(.codebinge.firestore.codec.v1.field) = { ... }</code>
   * @return The asNumber.
   */
  @java.lang.Override public com.codebinge.firestore.codec.testdata.v1.Status getAsNumber() {
    com.codebinge.firestore.codec.testdata.v1.Status result = com.codebinge.firestore.codec.testdata.v1.Status.forNumber(asNumber_);
    return result == null ? com.codebinge.firestore.codec.testdata.v1.Status.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (asName_ != com.codebinge.firestore.codec.testdata.v1.Status.STATUS_UNKNOWN.getNumber()) {
      output.writeEnum(1, asName_);
    }
    if (asNumber_ != com.codebinge.firestore.codec.testdata.v1.Status.STATUS_UNKNOWN.getNumber()) {
      output.writeEnum(2, asNumber_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (asName_ != com.codebinge.firestore.codec.testdata.v1.Status.STATUS_UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, asName_);
    }
    if (asNumber_ != com.codebinge.firestore.codec.testdata.v1.Status.STATUS_UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, asNumber_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.codebinge.firestore.codec.testdata.v1.Enums)) {
      return super.equals(obj);
    }
    com.codebinge.firestore.codec.testdata.v1.Enums other = (com.codebinge.firestore.codec.testdata.v1.Enums) obj;

    if (asName_ != other.asName_) return false;
    if (asNumber_ != other.asNumber_) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + AS_NAME_FIELD_NUMBER;
    hash = (53 * hash) + asName_;
    hash = (37 * hash) + AS_NUMBER_FIELD_NUMBER;
    hash = (53 * hash) + asNumber_;
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.codebinge.firestore.codec.testdata.v1.Enums parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Enums parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Enums parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Enums parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Enums parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Enums parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Enums parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Enums parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.codebinge.firestore.codec.testdata.v1.Enums parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.codebinge.firestore.codec.testdata.v1.Enums parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Enums parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Enums parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.codebinge.firestore.codec.testdata.v1.Enums prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Both enum encodings (§4).
   * </pre>
   *
   * Protobuf type {@code codebinge.firestore.codec.testdata.v1.Enums}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:codebinge.firestore.codec.testdata.v1.Enums)
      com.codebinge.firestore.codec.testdata.v1.EnumsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.codebinge.firestore.codec.testdata.v1.Testdata.internal_static_codebinge_firestore_codec_testdata_v1_Enums_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.codebinge.firestore.codec.testdata.v1.Testdata.internal_static_codebinge_firestore_codec_testdata_v1_Enums_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.codebinge.firestore.codec.testdata.v1.Enums.class, com.codebinge.firestore.codec.testdata.v1.Enums.Builder.class);
    }

    // Construct using com.codebinge.firestore.codec.testdata.v1.Enums.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      asName_ = 0;
      asNumber_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.codebinge.firestore.codec.testdata.v1.Testdata.internal_static_codebinge_firestore_codec_testdata_v1_Enums_descriptor;
    }

    @java.lang.Override
    public com.codebinge.firestore.codec.testdata.v1.Enums getDefaultInstanceForType() {
      return com.codebinge.firestore.codec.testdata.v1.Enums.getDefaultInstance();
    }

    @java.lang.Override
    public com.codebinge.firestore.codec.testdata.v1.Enums build() {
      com.codebinge.firestore.codec.testdata.v1.Enums result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.codebinge.firestore.codec.testdata.v1.Enums buildPartial() {
      com.codebinge.firestore.codec.testdata.v1.Enums result = new com.codebinge.firestore.codec.testdata.v1.Enums(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.codebinge.firestore.codec.testdata.v1.Enums result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.asName_ = asName_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.asNumber_ = asNumber_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.codebinge.firestore.codec.testdata.v1.Enums) {
        return mergeFrom((com.codebinge.firestore.codec.testdata.v1.Enums)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.codebinge.firestore.codec.testdata.v1.Enums other) {
      if (other == com.codebinge.firestore.codec.testdata.v1.Enums.getDefaultInstance()) return this;
      if (other.asName_ != 0) {
        setAsNameValue(other.getAsNameValue());
      }
      if (other.asNumber_ != 0) {
        setAsNumberValue(other.getAsNumberValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              asName_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              asNumber_ = input.readEnum();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int asName_ = 0;
    /**
     * <code>.codebinge.firestore.codec.testdata.v1.Status as_name = 1;</code>
     * @return The enum numeric value on the wire for asName.
     */
    @java.lang.Override public int getAsNameValue() {
      return asName_;
    }
    /**
     * <code>.codebinge.firestore.codec.testdata.v1.Status as_name = 1;</code>
     * @param value The enum numeric value on the wire for asName to set.
     * @return This builder for chaining.
     */
    public Builder setAsNameValue(int value) {
      asName_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.codebinge.firestore.codec.testdata.v1.Status as_name = 1;</code>
     * @return The asName.
     */
    @java.lang.Override
    public com.codebinge.firestore.codec.testdata.v1.Status getAsName() {
      com.codebinge.firestore.codec.testdata.v1.Status result = com.codebinge.firestore.codec.testdata.v1.Status.forNumber(asName_);
      return result == null ? com.codebinge.firestore.codec.testdata.v1.Status.UNRECOGNIZED : result;
    }
    /**
     * <code>.codebinge.firestore.codec.testdata.v1.Status as_name = 1;</code>
     * @param value The asName to set.
     * @return This builder for chaining.
     */
    public Builder setAsName(com.codebinge.firestore.codec.testdata.v1.Status value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000001;
      asName_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.codebinge.firestore.codec.testdata.v1.Status as_name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAsName() {
      bitField0_ = (bitField0_ & ~0x00000001);
      asName_ = 0;
      onChanged();
      return this;
    }

    private int asNumber_ = 0;
    /**
     * <code>.codebinge.firestore.codec.testdata.v1.Status as_number = 2 [(.codebinge.firestore.codec.v1.field) = { ... }</code>
     * @return The enum numeric value on the wire for asNumber.
     */
    @java.lang.Override public int getAsNumberValue() {
      return asNumber_;
    }
    /**
     * <code>.codebinge.firestore.codec.testdata.v1.Status as_number = 2 [(.codebinge.firestore.codec.v1.field) = { ... }</code>
     * @param value The enum numeric value on the wire for asNumber to set.
     * @return This builder for chaining.
     */
    public Builder setAsNumberValue(int value) {
      asNumber_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.codebinge.firestore.codec.testdata.v1.Status as_number = 2 [(.codebinge.firestore.codec.v1.field) = { ... }</code>
     * @return The asNumber.
     */
    @java.lang.Override
    public com.codebinge.firestore.codec.testdata.v1.Status getAsNumber() {
      com.codebinge.firestore.codec.testdata.v1.Status result = com.codebinge.firestore.codec.testdata.v1.Status.forNumber(asNumber_);
      return result == null ? com.codebinge.firestore.codec.testdata.v1.Status.UNRECOGNIZED : result;
    }
    /**
     * <code>.codebinge.firestore.codec.testdata.v1.Status as_number = 2 [(.codebinge.firestore.codec.v1.field) = { ... }</code>
     * @param value The asNumber to set.
     * @return This builder for chaining.
     */
    public Builder setAsNumber(com.codebinge.firestore.codec.testdata.v1.Status value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000002;
      asNumber_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.codebinge.firestore.codec.testdata.v1.Status as_number = 2 [(.codebinge.firestore.codec.v1.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearAsNumber() {
      bitField0_ = (bitField0_ & ~0x00000002);
      asNumber_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:codebinge.firestore.codec.testdata.v1.Enums)
  }

  // @@protoc_insertion_point(class_scope:codebinge.firestore.codec.testdata.v1.Enums)
  private static final com.codebinge.firestore.codec.testdata.v1.Enums DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.codebinge.firestore.codec.testdata.v1.Enums();
  }

  public static com.codebinge.firestore.codec.testdata.v1.Enums getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Enums>
      PARSER = new com.google.protobuf.AbstractParser<Enums>() {
    @java.lang.Override
    public Enums parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Enums> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Enums> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.codebinge.firestore.codec.testdata.v1.Enums getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

