// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: invalid.proto
// Protobuf Java Version: 4.33.3

package com.codebinge.firestore.codec.testdata.v1;

@com.google.protobuf.Generated
public final class Invalid extends com.google.protobuf.GeneratedFile {
  private Invalid() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 3,
      /* suffix= */ "",
      "Invalid");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_codebinge_firestore_codec_testdata_v1_IntKeyMap_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_codebinge_firestore_codec_testdata_v1_IntKeyMap_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_codebinge_firestore_codec_testdata_v1_IntKeyMap_BadEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_codebinge_firestore_codec_testdata_v1_IntKeyMap_BadEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_codebinge_firestore_codec_testdata_v1_AnyField_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_codebinge_firestore_codec_testdata_v1_AnyField_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_codebinge_firestore_codec_testdata_v1_StructField_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_codebinge_firestore_codec_testdata_v1_StructField_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rinvalid.proto\022%codebinge.firestore.cod" +
      "ec.testdata.v1\032\031google/protobuf/any.prot" +
      "o\032\034google/protobuf/struct.proto\"\177\n\tIntKe" +
      "yMap\022F\n\003bad\030\001 \003(\01329.codebinge.firestore." +
      "codec.testdata.v1.IntKeyMap.BadEntry\032*\n\010" +
      "BadEntry\022\013\n\003key\030\001 \001(\005\022\r\n\005value\030\002 \001(\t:\0028\001" +
      "\"-\n\010AnyField\022!\n\003bad\030\001 \001(\0132\024.google.proto" +
      "buf.Any\"3\n\013StructField\022$\n\003bad\030\001 \001(\0132\027.go" +
      "ogle.protobuf.StructB-\n)com.codebinge.fi" +
      "restore.codec.testdata.v1P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
          com.google.protobuf.StructProto.getDescriptor(),
        });
    internal_static_codebinge_firestore_codec_testdata_v1_IntKeyMap_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_codebinge_firestore_codec_testdata_v1_IntKeyMap_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_codebinge_firestore_codec_testdata_v1_IntKeyMap_descriptor,
        new java.lang.String[] { "Bad", });
    internal_static_codebinge_firestore_codec_testdata_v1_IntKeyMap_BadEntry_descriptor =
      internal_static_codebinge_firestore_codec_testdata_v1_IntKeyMap_descriptor.getNestedType(0);
    internal_static_codebinge_firestore_codec_testdata_v1_IntKeyMap_BadEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_codebinge_firestore_codec_testdata_v1_IntKeyMap_BadEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_codebinge_firestore_codec_testdata_v1_AnyField_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_codebinge_firestore_codec_testdata_v1_AnyField_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_codebinge_firestore_codec_testdata_v1_AnyField_descriptor,
        new java.lang.String[] { "Bad", });
    internal_static_codebinge_firestore_codec_testdata_v1_StructField_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_codebinge_firestore_codec_testdata_v1_StructField_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_codebinge_firestore_codec_testdata_v1_StructField_descriptor,
        new java.lang.String[] { "Bad", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.AnyProto.getDescriptor();
    com.google.protobuf.StructProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
