// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: testdata.proto
// Protobuf Java Version: 4.33.3

package com.codebinge.firestore.codec.testdata.v1;

@com.google.protobuf.Generated
public interface OptionsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:codebinge.firestore.codec.testdata.v1.Options)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string kept = 1;</code>
   * @return The kept.
   */
  java.lang.String getKept();
  /**
   * <code>string kept = 1;</code>
   * @return The bytes for kept.
   */
  com.google.protobuf.ByteString
      getKeptBytes();

  /**
   * <code>string dropped = 2 [(.codebinge.firestore.codec.v1.field) = { ... }</code>
   * @return The dropped.
   */
  java.lang.String getDropped();
  /**
   * <code>string dropped = 2 [(.codebinge.firestore.codec.v1.field) = { ... }</code>
   * @return The bytes for dropped.
   */
  com.google.protobuf.ByteString
      getDroppedBytes();

  /**
   * <code>string renamed = 3 [(.codebinge.firestore.codec.v1.field) = { ... }</code>
   * @return The renamed.
   */
  java.lang.String getRenamed();
  /**
   * <code>string renamed = 3 [(.codebinge.firestore.codec.v1.field) = { ... }</code>
   * @return The bytes for renamed.
   */
  com.google.protobuf.ByteString
      getRenamedBytes();
}
