// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: testdata.proto
// Protobuf Java Version: 4.33.3

package com.codebinge.firestore.codec.testdata.v1;

/**
 * <pre>
 * The `skip` and `name` options (§7).
 * </pre>
 *
 * Protobuf type {@code codebinge.firestore.codec.testdata.v1.Options}
 */
@com.google.protobuf.Generated
public final class Options extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:codebinge.firestore.codec.testdata.v1.Options)
    OptionsOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 3,
      /* suffix= */ "",
      "Options");
  }
  // Use Options.newBuilder() to construct.
  private Options(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Options() {
    kept_ = "";
    dropped_ = "";
    renamed_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.codebinge.firestore.codec.testdata.v1.Testdata.internal_static_codebinge_firestore_codec_testdata_v1_Options_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.codebinge.firestore.codec.testdata.v1.Testdata.internal_static_codebinge_firestore_codec_testdata_v1_Options_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.codebinge.firestore.codec.testdata.v1.Options.class, com.codebinge.firestore.codec.testdata.v1.Options.Builder.class);
  }

  public static final int KEPT_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object kept_ = "";
  /**
   * <code>string kept = 1;</code>
   * @return The kept.
   */
  @java.lang.Override
  public java.lang.String getKept() {
    java.lang.Object ref = kept_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      kept_ = s;
      return s;
    }
  }
  /**
   * <code>string kept = 1;</code>
   * @return The bytes for kept.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getKeptBytes() {
    java.lang.Object ref = kept_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      kept_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DROPPED_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object dropped_ = "";
  /**
   * <code>string dropped = 2 [(.codebinge.firestore.codec.v1.field) = { ... }</code>
   * @return The dropped.
   */
  @java.lang.Override
  public java.lang.String getDropped() {
    java.lang.Object ref = dropped_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dropped_ = s;
      return s;
    }
  }
  /**
   * <code>string dropped = 2 [(.codebinge.firestore.codec.v1.field) = { ... }</code>
   * @return The bytes for dropped.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDroppedBytes() {
    java.lang.Object ref = dropped_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dropped_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RENAMED_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object renamed_ = "";
  /**
   * <code>string renamed = 3 [(.codebinge.firestore.codec.v1.field) = { ... }</code>
   * @return The renamed.
   */
  @java.lang.Override
  public java.lang.String getRenamed() {
    java.lang.Object ref = renamed_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      renamed_ = s;
      return s;
    }
  }
  /**
   * <code>string renamed = 3 [(.codebinge.firestore.codec.v1.field) = { ... }</code>
   * @return The bytes for renamed.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRenamedBytes() {
    java.lang.Object ref = renamed_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      renamed_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(kept_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, kept_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(dropped_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, dropped_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(renamed_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, renamed_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(kept_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, kept_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(dropped_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, dropped_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(renamed_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, renamed_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.codebinge.firestore.codec.testdata.v1.Options)) {
      return super.equals(obj);
    }
    com.codebinge.firestore.codec.testdata.v1.Options other = (com.codebinge.firestore.codec.testdata.v1.Options) obj;

    if (!getKept()
        .equals(other.getKept())) return false;
    if (!getDropped()
        .equals(other.getDropped())) return false;
    if (!getRenamed()
        .equals(other.getRenamed())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + KEPT_FIELD_NUMBER;
    hash = (53 * hash) + getKept().hashCode();
    hash = (37 * hash) + DROPPED_FIELD_NUMBER;
    hash = (53 * hash) + getDropped().hashCode();
    hash = (37 * hash) + RENAMED_FIELD_NUMBER;
    hash = (53 * hash) + getRenamed().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.codebinge.firestore.codec.testdata.v1.Options parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Options parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Options parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Options parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Options parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Options parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Options parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Options parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.codebinge.firestore.codec.testdata.v1.Options parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.codebinge.firestore.codec.testdata.v1.Options parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Options parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Options parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.codebinge.firestore.codec.testdata.v1.Options prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The `skip` and `name` options (§7).
   * </pre>
   *
   * Protobuf type {@code codebinge.firestore.codec.testdata.v1.Options}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:codebinge.firestore.codec.testdata.v1.Options)
      com.codebinge.firestore.codec.testdata.v1.OptionsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.codebinge.firestore.codec.testdata.v1.Testdata.internal_static_codebinge_firestore_codec_testdata_v1_Options_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.codebinge.firestore.codec.testdata.v1.Testdata.internal_static_codebinge_firestore_codec_testdata_v1_Options_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.codebinge.firestore.codec.testdata.v1.Options.class, com.codebinge.firestore.codec.testdata.v1.Options.Builder.class);
    }

    // Construct using com.codebinge.firestore.codec.testdata.v1.Options.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      kept_ = "";
      dropped_ = "";
      renamed_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.codebinge.firestore.codec.testdata.v1.Testdata.internal_static_codebinge_firestore_codec_testdata_v1_Options_descriptor;
    }

    @java.lang.Override
    public com.codebinge.firestore.codec.testdata.v1.Options getDefaultInstanceForType() {
      return com.codebinge.firestore.codec.testdata.v1.Options.getDefaultInstance();
    }

    @java.lang.Override
    public com.codebinge.firestore.codec.testdata.v1.Options build() {
      com.codebinge.firestore.codec.testdata.v1.Options result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.codebinge.firestore.codec.testdata.v1.Options buildPartial() {
      com.codebinge.firestore.codec.testdata.v1.Options result = new com.codebinge.firestore.codec.testdata.v1.Options(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.codebinge.firestore.codec.testdata.v1.Options result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.kept_ = kept_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.dropped_ = dropped_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.renamed_ = renamed_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.codebinge.firestore.codec.testdata.v1.Options) {
        return mergeFrom((com.codebinge.firestore.codec.testdata.v1.Options)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.codebinge.firestore.codec.testdata.v1.Options other) {
      if (other == com.codebinge.firestore.codec.testdata.v1.Options.getDefaultInstance()) return this;
      if (!other.getKept().isEmpty()) {
        kept_ = other.kept_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getDropped().isEmpty()) {
        dropped_ = other.dropped_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getRenamed().isEmpty()) {
        renamed_ = other.renamed_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              kept_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              dropped_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              renamed_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object kept_ = "";
    /**
     * <code>string kept = 1;</code>
     * @return The kept.
     */
    public java.lang.String getKept() {
      java.lang.Object ref = kept_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        kept_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string kept = 1;</code>
     * @return The bytes for kept.
     */
    public com.google.protobuf.ByteString
        getKeptBytes() {
      java.lang.Object ref = kept_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        kept_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string kept = 1;</code>
     * @param value The kept to set.
     * @return This builder for chaining.
     */
    public Builder setKept(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      kept_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string kept = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearKept() {
      kept_ = getDefaultInstance().getKept();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string kept = 1;</code>
     * @param value The bytes for kept to set.
     * @return This builder for chaining.
     */
    public Builder setKeptBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      kept_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object dropped_ = "";
    /**
     * <code>string dropped = 2 [(.codebinge.firestore.codec.v1.field) = { ... }</code>
     * @return The dropped.
     */
    public java.lang.String getDropped() {
      java.lang.Object ref = dropped_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dropped_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string dropped = 2 [(.codebinge.firestore.codec.v1.field) = { ... }</code>
     * @return The bytes for dropped.
     */
    public com.google.protobuf.ByteString
        getDroppedBytes() {
      java.lang.Object ref = dropped_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dropped_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string dropped = 2 [(.codebinge.firestore.codec.v1.field) = { ... }</code>
     * @param value The dropped to set.
     * @return This builder for chaining.
     */
    public Builder setDropped(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      dropped_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string dropped = 2 [(.codebinge.firestore.codec.v1.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearDropped() {
      dropped_ = getDefaultInstance().getDropped();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string dropped = 2 [(.codebinge.firestore.codec.v1.field) = { ... }</code>
     * @param value The bytes for dropped to set.
     * @return This builder for chaining.
     */
    public Builder setDroppedBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      dropped_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object renamed_ = "";
    /**
     * <code>string renamed = 3 [(.codebinge.firestore.codec.v1.field) = { ... }</code>
     * @return The renamed.
     */
    public java.lang.String getRenamed() {
      java.lang.Object ref = renamed_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        renamed_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string renamed = 3 [(.codebinge.firestore.codec.v1.field) = { ... }</code>
     * @return The bytes for renamed.
     */
    public com.google.protobuf.ByteString
        getRenamedBytes() {
      java.lang.Object ref = renamed_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        renamed_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string renamed = 3 [(.codebinge.firestore.codec.v1.field) = { ... }</code>
     * @param value The renamed to set.
     * @return This builder for chaining.
     */
    public Builder setRenamed(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      renamed_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string renamed = 3 [(.codebinge.firestore.codec.v1.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearRenamed() {
      renamed_ = getDefaultInstance().getRenamed();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string renamed = 3 [(.codebinge.firestore.codec.v1.field) = { ... }</code>
     * @param value The bytes for renamed to set.
     * @return This builder for chaining.
     */
    public Builder setRenamedBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      renamed_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:codebinge.firestore.codec.testdata.v1.Options)
  }

  // @@protoc_insertion_point(class_scope:codebinge.firestore.codec.testdata.v1.Options)
  private static final com.codebinge.firestore.codec.testdata.v1.Options DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.codebinge.firestore.codec.testdata.v1.Options();
  }

  public static com.codebinge.firestore.codec.testdata.v1.Options getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Options>
      PARSER = new com.google.protobuf.AbstractParser<Options>() {
    @java.lang.Override
    public Options parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Options> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Options> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.codebinge.firestore.codec.testdata.v1.Options getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

