// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: testdata.proto
// Protobuf Java Version: 4.33.3

package com.codebinge.firestore.codec.testdata.v1;

@com.google.protobuf.Generated
public interface PresenceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:codebinge.firestore.codec.testdata.v1.Presence)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string opt_string = 1;</code>
   * @return Whether the optString field is set.
   */
  boolean hasOptString();
  /**
   * <code>optional string opt_string = 1;</code>
   * @return The optString.
   */
  java.lang.String getOptString();
  /**
   * <code>optional string opt_string = 1;</code>
   * @return The bytes for optString.
   */
  com.google.protobuf.ByteString
      getOptStringBytes();

  /**
   * <code>optional int32 opt_int32 = 2;</code>
   * @return Whether the optInt32 field is set.
   */
  boolean hasOptInt32();
  /**
   * <code>optional int32 opt_int32 = 2;</code>
   * @return The optInt32.
   */
  int getOptInt32();

  /**
   * <code>.codebinge.firestore.codec.testdata.v1.Inner inner = 3;</code>
   * @return Whether the inner field is set.
   */
  boolean hasInner();
  /**
   * <code>.codebinge.firestore.codec.testdata.v1.Inner inner = 3;</code>
   * @return The inner.
   */
  com.codebinge.firestore.codec.testdata.v1.Inner getInner();
  /**
   * <code>.codebinge.firestore.codec.testdata.v1.Inner inner = 3;</code>
   */
  com.codebinge.firestore.codec.testdata.v1.InnerOrBuilder getInnerOrBuilder();
}
