// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: testdata.proto
// Protobuf Java Version: 4.33.3

package com.codebinge.firestore.codec.testdata.v1;

/**
 * <pre>
 * Explicit presence (§6). `optional` scalars and singular message fields are
 * written even when they hold a default, and omitted when unset.
 * </pre>
 *
 * Protobuf type {@code codebinge.firestore.codec.testdata.v1.Presence}
 */
@com.google.protobuf.Generated
public final class Presence extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:codebinge.firestore.codec.testdata.v1.Presence)
    PresenceOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 3,
      /* suffix= */ "",
      "Presence");
  }
  // Use Presence.newBuilder() to construct.
  private Presence(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Presence() {
    optString_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.codebinge.firestore.codec.testdata.v1.Testdata.internal_static_codebinge_firestore_codec_testdata_v1_Presence_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.codebinge.firestore.codec.testdata.v1.Testdata.internal_static_codebinge_firestore_codec_testdata_v1_Presence_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.codebinge.firestore.codec.testdata.v1.Presence.class, com.codebinge.firestore.codec.testdata.v1.Presence.Builder.class);
  }

  private int bitField0_;
  public static final int OPT_STRING_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object optString_ = "";
  /**
   * <code>optional string opt_string = 1;</code>
   * @return Whether the optString field is set.
   */
  @java.lang.Override
  public boolean hasOptString() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string opt_string = 1;</code>
   * @return The optString.
   */
  @java.lang.Override
  public java.lang.String getOptString() {
    java.lang.Object ref = optString_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      optString_ = s;
      return s;
    }
  }
  /**
   * <code>optional string opt_string = 1;</code>
   * @return The bytes for optString.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOptStringBytes() {
    java.lang.Object ref = optString_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      optString_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OPT_INT32_FIELD_NUMBER = 2;
  private int optInt32_ = 0;
  /**
   * <code>optional int32 opt_int32 = 2;</code>
   * @return Whether the optInt32 field is set.
   */
  @java.lang.Override
  public boolean hasOptInt32() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional int32 opt_int32 = 2;</code>
   * @return The optInt32.
   */
  @java.lang.Override
  public int getOptInt32() {
    return optInt32_;
  }

  public static final int INNER_FIELD_NUMBER = 3;
  private com.codebinge.firestore.codec.testdata.v1.Inner inner_;
  /**
   * <code>.codebinge.firestore.codec.testdata.v1.Inner inner = 3;</code>
   * @return Whether the inner field is set.
   */
  @java.lang.Override
  public boolean hasInner() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>.codebinge.firestore.codec.testdata.v1.Inner inner = 3;</code>
   * @return The inner.
   */
  @java.lang.Override
  public com.codebinge.firestore.codec.testdata.v1.Inner getInner() {
    return inner_ == null ? com.codebinge.firestore.codec.testdata.v1.Inner.getDefaultInstance() : inner_;
  }
  /**
   * <code>.codebinge.firestore.codec.testdata.v1.Inner inner = 3;</code>
   */
  @java.lang.Override
  public com.codebinge.firestore.codec.testdata.v1.InnerOrBuilder getInnerOrBuilder() {
    return inner_ == null ? com.codebinge.firestore.codec.testdata.v1.Inner.getDefaultInstance() : inner_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, optString_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeInt32(2, optInt32_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(3, getInner());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, optString_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, optInt32_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getInner());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.codebinge.firestore.codec.testdata.v1.Presence)) {
      return super.equals(obj);
    }
    com.codebinge.firestore.codec.testdata.v1.Presence other = (com.codebinge.firestore.codec.testdata.v1.Presence) obj;

    if (hasOptString() != other.hasOptString()) return false;
    if (hasOptString()) {
      if (!getOptString()
          .equals(other.getOptString())) return false;
    }
    if (hasOptInt32() != other.hasOptInt32()) return false;
    if (hasOptInt32()) {
      if (getOptInt32()
          != other.getOptInt32()) return false;
    }
    if (hasInner() != other.hasInner()) return false;
    if (hasInner()) {
      if (!getInner()
          .equals(other.getInner())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasOptString()) {
      hash = (37 * hash) + OPT_STRING_FIELD_NUMBER;
      hash = (53 * hash) + getOptString().hashCode();
    }
    if (hasOptInt32()) {
      hash = (37 * hash) + OPT_INT32_FIELD_NUMBER;
      hash = (53 * hash) + getOptInt32();
    }
    if (hasInner()) {
      hash = (37 * hash) + INNER_FIELD_NUMBER;
      hash = (53 * hash) + getInner().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.codebinge.firestore.codec.testdata.v1.Presence parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Presence parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Presence parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Presence parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Presence parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Presence parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Presence parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Presence parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.codebinge.firestore.codec.testdata.v1.Presence parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.codebinge.firestore.codec.testdata.v1.Presence parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Presence parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Presence parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.codebinge.firestore.codec.testdata.v1.Presence prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Explicit presence (§6). `optional` scalars and singular message fields are
   * written even when they hold a default, and omitted when unset.
   * </pre>
   *
   * Protobuf type {@code codebinge.firestore.codec.testdata.v1.Presence}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:codebinge.firestore.codec.testdata.v1.Presence)
      com.codebinge.firestore.codec.testdata.v1.PresenceOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.codebinge.firestore.codec.testdata.v1.Testdata.internal_static_codebinge_firestore_codec_testdata_v1_Presence_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.codebinge.firestore.codec.testdata.v1.Testdata.internal_static_codebinge_firestore_codec_testdata_v1_Presence_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.codebinge.firestore.codec.testdata.v1.Presence.class, com.codebinge.firestore.codec.testdata.v1.Presence.Builder.class);
    }

    // Construct using com.codebinge.firestore.codec.testdata.v1.Presence.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetInnerFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      optString_ = "";
      optInt32_ = 0;
      inner_ = null;
      if (innerBuilder_ != null) {
        innerBuilder_.dispose();
        innerBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.codebinge.firestore.codec.testdata.v1.Testdata.internal_static_codebinge_firestore_codec_testdata_v1_Presence_descriptor;
    }

    @java.lang.Override
    public com.codebinge.firestore.codec.testdata.v1.Presence getDefaultInstanceForType() {
      return com.codebinge.firestore.codec.testdata.v1.Presence.getDefaultInstance();
    }

    @java.lang.Override
    public com.codebinge.firestore.codec.testdata.v1.Presence build() {
      com.codebinge.firestore.codec.testdata.v1.Presence result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.codebinge.firestore.codec.testdata.v1.Presence buildPartial() {
      com.codebinge.firestore.codec.testdata.v1.Presence result = new com.codebinge.firestore.codec.testdata.v1.Presence(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.codebinge.firestore.codec.testdata.v1.Presence result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.optString_ = optString_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.optInt32_ = optInt32_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.inner_ = innerBuilder_ == null
            ? inner_
            : innerBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.codebinge.firestore.codec.testdata.v1.Presence) {
        return mergeFrom((com.codebinge.firestore.codec.testdata.v1.Presence)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.codebinge.firestore.codec.testdata.v1.Presence other) {
      if (other == com.codebinge.firestore.codec.testdata.v1.Presence.getDefaultInstance()) return this;
      if (other.hasOptString()) {
        optString_ = other.optString_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasOptInt32()) {
        setOptInt32(other.getOptInt32());
      }
      if (other.hasInner()) {
        mergeInner(other.getInner());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              optString_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              optInt32_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              input.readMessage(
                  internalGetInnerFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object optString_ = "";
    /**
     * <code>optional string opt_string = 1;</code>
     * @return Whether the optString field is set.
     */
    public boolean hasOptString() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string opt_string = 1;</code>
     * @return The optString.
     */
    public java.lang.String getOptString() {
      java.lang.Object ref = optString_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        optString_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string opt_string = 1;</code>
     * @return The bytes for optString.
     */
    public com.google.protobuf.ByteString
        getOptStringBytes() {
      java.lang.Object ref = optString_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        optString_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string opt_string = 1;</code>
     * @param value The optString to set.
     * @return This builder for chaining.
     */
    public Builder setOptString(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      optString_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional string opt_string = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOptString() {
      optString_ = getDefaultInstance().getOptString();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>optional string opt_string = 1;</code>
     * @param value The bytes for optString to set.
     * @return This builder for chaining.
     */
    public Builder setOptStringBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      optString_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int optInt32_ ;
    /**
     * <code>optional int32 opt_int32 = 2;</code>
     * @return Whether the optInt32 field is set.
     */
    @java.lang.Override
    public boolean hasOptInt32() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 opt_int32 = 2;</code>
     * @return The optInt32.
     */
    @java.lang.Override
    public int getOptInt32() {
      return optInt32_;
    }
    /**
     * <code>optional int32 opt_int32 = 2;</code>
     * @param value The optInt32 to set.
     * @return This builder for chaining.
     */
    public Builder setOptInt32(int value) {

      optInt32_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 opt_int32 = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearOptInt32() {
      bitField0_ = (bitField0_ & ~0x00000002);
      optInt32_ = 0;
      onChanged();
      return this;
    }

    private com.codebinge.firestore.codec.testdata.v1.Inner inner_;
    private com.google.protobuf.SingleFieldBuilder<
        com.codebinge.firestore.codec.testdata.v1.Inner, com.codebinge.firestore.codec.testdata.v1.Inner.Builder, com.codebinge.firestore.codec.testdata.v1.InnerOrBuilder> innerBuilder_;
    /**
     * <code>.codebinge.firestore.codec.testdata.v1.Inner inner = 3;</code>
     * @return Whether the inner field is set.
     */
    public boolean hasInner() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.codebinge.firestore.codec.testdata.v1.Inner inner = 3;</code>
     * @return The inner.
     */
    public com.codebinge.firestore.codec.testdata.v1.Inner getInner() {
      if (innerBuilder_ == null) {
        return inner_ == null ? com.codebinge.firestore.codec.testdata.v1.Inner.getDefaultInstance() : inner_;
      } else {
        return innerBuilder_.getMessage();
      }
    }
    /**
     * <code>.codebinge.firestore.codec.testdata.v1.Inner inner = 3;</code>
     */
    public Builder setInner(com.codebinge.firestore.codec.testdata.v1.Inner value) {
      if (innerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        inner_ = value;
      } else {
        innerBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.codebinge.firestore.codec.testdata.v1.Inner inner = 3;</code>
     */
    public Builder setInner(
        com.codebinge.firestore.codec.testdata.v1.Inner.Builder builderForValue) {
      if (innerBuilder_ == null) {
        inner_ = builderForValue.build();
      } else {
        innerBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.codebinge.firestore.codec.testdata.v1.Inner inner = 3;</code>
     */
    public Builder mergeInner(com.codebinge.firestore.codec.testdata.v1.Inner value) {
      if (innerBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          inner_ != null &&
          inner_ != com.codebinge.firestore.codec.testdata.v1.Inner.getDefaultInstance()) {
          getInnerBuilder().mergeFrom(value);
        } else {
          inner_ = value;
        }
      } else {
        innerBuilder_.mergeFrom(value);
      }
      if (inner_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.codebinge.firestore.codec.testdata.v1.Inner inner = 3;</code>
     */
    public Builder clearInner() {
      bitField0_ = (bitField0_ & ~0x00000004);
      inner_ = null;
      if (innerBuilder_ != null) {
        innerBuilder_.dispose();
        innerBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.codebinge.firestore.codec.testdata.v1.Inner inner = 3;</code>
     */
    public com.codebinge.firestore.codec.testdata.v1.Inner.Builder getInnerBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return internalGetInnerFieldBuilder().getBuilder();
    }
    /**
     * <code>.codebinge.firestore.codec.testdata.v1.Inner inner = 3;</code>
     */
    public com.codebinge.firestore.codec.testdata.v1.InnerOrBuilder getInnerOrBuilder() {
      if (innerBuilder_ != null) {
        return innerBuilder_.getMessageOrBuilder();
      } else {
        return inner_ == null ?
            com.codebinge.firestore.codec.testdata.v1.Inner.getDefaultInstance() : inner_;
      }
    }
    /**
     * <code>.codebinge.firestore.codec.testdata.v1.Inner inner = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.codebinge.firestore.codec.testdata.v1.Inner, com.codebinge.firestore.codec.testdata.v1.Inner.Builder, com.codebinge.firestore.codec.testdata.v1.InnerOrBuilder> 
        internalGetInnerFieldBuilder() {
      if (innerBuilder_ == null) {
        innerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.codebinge.firestore.codec.testdata.v1.Inner, com.codebinge.firestore.codec.testdata.v1.Inner.Builder, com.codebinge.firestore.codec.testdata.v1.InnerOrBuilder>(
                getInner(),
                getParentForChildren(),
                isClean());
        inner_ = null;
      }
      return innerBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:codebinge.firestore.codec.testdata.v1.Presence)
  }

  // @@protoc_insertion_point(class_scope:codebinge.firestore.codec.testdata.v1.Presence)
  private static final com.codebinge.firestore.codec.testdata.v1.Presence DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.codebinge.firestore.codec.testdata.v1.Presence();
  }

  public static com.codebinge.firestore.codec.testdata.v1.Presence getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Presence>
      PARSER = new com.google.protobuf.AbstractParser<Presence>() {
    @java.lang.Override
    public Presence parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Presence> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Presence> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.codebinge.firestore.codec.testdata.v1.Presence getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

