// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: testdata.proto
// Protobuf Java Version: 4.33.3

package com.codebinge.firestore.codec.testdata.v1;

/**
 * <pre>
 * Nesting depth (§5). A chain of N `child` values puts the innermost map at
 * depth N; Firestore's limit is 20.
 * </pre>
 *
 * Protobuf type {@code codebinge.firestore.codec.testdata.v1.Recursive}
 */
@com.google.protobuf.Generated
public final class Recursive extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:codebinge.firestore.codec.testdata.v1.Recursive)
    RecursiveOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 3,
      /* suffix= */ "",
      "Recursive");
  }
  // Use Recursive.newBuilder() to construct.
  private Recursive(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Recursive() {
    label_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.codebinge.firestore.codec.testdata.v1.Testdata.internal_static_codebinge_firestore_codec_testdata_v1_Recursive_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.codebinge.firestore.codec.testdata.v1.Testdata.internal_static_codebinge_firestore_codec_testdata_v1_Recursive_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.codebinge.firestore.codec.testdata.v1.Recursive.class, com.codebinge.firestore.codec.testdata.v1.Recursive.Builder.class);
  }

  private int bitField0_;
  public static final int LABEL_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object label_ = "";
  /**
   * <code>string label = 1;</code>
   * @return The label.
   */
  @java.lang.Override
  public java.lang.String getLabel() {
    java.lang.Object ref = label_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      label_ = s;
      return s;
    }
  }
  /**
   * <code>string label = 1;</code>
   * @return The bytes for label.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLabelBytes() {
    java.lang.Object ref = label_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      label_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CHILD_FIELD_NUMBER = 2;
  private com.codebinge.firestore.codec.testdata.v1.Recursive child_;
  /**
   * <code>.codebinge.firestore.codec.testdata.v1.Recursive child = 2;</code>
   * @return Whether the child field is set.
   */
  @java.lang.Override
  public boolean hasChild() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.codebinge.firestore.codec.testdata.v1.Recursive child = 2;</code>
   * @return The child.
   */
  @java.lang.Override
  public com.codebinge.firestore.codec.testdata.v1.Recursive getChild() {
    return child_ == null ? com.codebinge.firestore.codec.testdata.v1.Recursive.getDefaultInstance() : child_;
  }
  /**
   * <code>.codebinge.firestore.codec.testdata.v1.Recursive child = 2;</code>
   */
  @java.lang.Override
  public com.codebinge.firestore.codec.testdata.v1.RecursiveOrBuilder getChildOrBuilder() {
    return child_ == null ? com.codebinge.firestore.codec.testdata.v1.Recursive.getDefaultInstance() : child_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(label_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, label_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getChild());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(label_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, label_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getChild());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.codebinge.firestore.codec.testdata.v1.Recursive)) {
      return super.equals(obj);
    }
    com.codebinge.firestore.codec.testdata.v1.Recursive other = (com.codebinge.firestore.codec.testdata.v1.Recursive) obj;

    if (!getLabel()
        .equals(other.getLabel())) return false;
    if (hasChild() != other.hasChild()) return false;
    if (hasChild()) {
      if (!getChild()
          .equals(other.getChild())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LABEL_FIELD_NUMBER;
    hash = (53 * hash) + getLabel().hashCode();
    if (hasChild()) {
      hash = (37 * hash) + CHILD_FIELD_NUMBER;
      hash = (53 * hash) + getChild().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.codebinge.firestore.codec.testdata.v1.Recursive parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Recursive parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Recursive parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Recursive parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Recursive parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Recursive parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Recursive parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Recursive parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.codebinge.firestore.codec.testdata.v1.Recursive parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.codebinge.firestore.codec.testdata.v1.Recursive parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Recursive parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Recursive parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.codebinge.firestore.codec.testdata.v1.Recursive prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Nesting depth (§5). A chain of N `child` values puts the innermost map at
   * depth N; Firestore's limit is 20.
   * </pre>
   *
   * Protobuf type {@code codebinge.firestore.codec.testdata.v1.Recursive}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:codebinge.firestore.codec.testdata.v1.Recursive)
      com.codebinge.firestore.codec.testdata.v1.RecursiveOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.codebinge.firestore.codec.testdata.v1.Testdata.internal_static_codebinge_firestore_codec_testdata_v1_Recursive_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.codebinge.firestore.codec.testdata.v1.Testdata.internal_static_codebinge_firestore_codec_testdata_v1_Recursive_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.codebinge.firestore.codec.testdata.v1.Recursive.class, com.codebinge.firestore.codec.testdata.v1.Recursive.Builder.class);
    }

    // Construct using com.codebinge.firestore.codec.testdata.v1.Recursive.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetChildFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      label_ = "";
      child_ = null;
      if (childBuilder_ != null) {
        childBuilder_.dispose();
        childBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.codebinge.firestore.codec.testdata.v1.Testdata.internal_static_codebinge_firestore_codec_testdata_v1_Recursive_descriptor;
    }

    @java.lang.Override
    public com.codebinge.firestore.codec.testdata.v1.Recursive getDefaultInstanceForType() {
      return com.codebinge.firestore.codec.testdata.v1.Recursive.getDefaultInstance();
    }

    @java.lang.Override
    public com.codebinge.firestore.codec.testdata.v1.Recursive build() {
      com.codebinge.firestore.codec.testdata.v1.Recursive result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.codebinge.firestore.codec.testdata.v1.Recursive buildPartial() {
      com.codebinge.firestore.codec.testdata.v1.Recursive result = new com.codebinge.firestore.codec.testdata.v1.Recursive(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.codebinge.firestore.codec.testdata.v1.Recursive result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.label_ = label_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.child_ = childBuilder_ == null
            ? child_
            : childBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.codebinge.firestore.codec.testdata.v1.Recursive) {
        return mergeFrom((com.codebinge.firestore.codec.testdata.v1.Recursive)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.codebinge.firestore.codec.testdata.v1.Recursive other) {
      if (other == com.codebinge.firestore.codec.testdata.v1.Recursive.getDefaultInstance()) return this;
      if (!other.getLabel().isEmpty()) {
        label_ = other.label_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasChild()) {
        mergeChild(other.getChild());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              label_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetChildFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object label_ = "";
    /**
     * <code>string label = 1;</code>
     * @return The label.
     */
    public java.lang.String getLabel() {
      java.lang.Object ref = label_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        label_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string label = 1;</code>
     * @return The bytes for label.
     */
    public com.google.protobuf.ByteString
        getLabelBytes() {
      java.lang.Object ref = label_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        label_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string label = 1;</code>
     * @param value The label to set.
     * @return This builder for chaining.
     */
    public Builder setLabel(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      label_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string label = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearLabel() {
      label_ = getDefaultInstance().getLabel();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string label = 1;</code>
     * @param value The bytes for label to set.
     * @return This builder for chaining.
     */
    public Builder setLabelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      label_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.codebinge.firestore.codec.testdata.v1.Recursive child_;
    private com.google.protobuf.SingleFieldBuilder<
        com.codebinge.firestore.codec.testdata.v1.Recursive, com.codebinge.firestore.codec.testdata.v1.Recursive.Builder, com.codebinge.firestore.codec.testdata.v1.RecursiveOrBuilder> childBuilder_;
    /**
     * <code>.codebinge.firestore.codec.testdata.v1.Recursive child = 2;</code>
     * @return Whether the child field is set.
     */
    public boolean hasChild() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.codebinge.firestore.codec.testdata.v1.Recursive child = 2;</code>
     * @return The child.
     */
    public com.codebinge.firestore.codec.testdata.v1.Recursive getChild() {
      if (childBuilder_ == null) {
        return child_ == null ? com.codebinge.firestore.codec.testdata.v1.Recursive.getDefaultInstance() : child_;
      } else {
        return childBuilder_.getMessage();
      }
    }
    /**
     * <code>.codebinge.firestore.codec.testdata.v1.Recursive child = 2;</code>
     */
    public Builder setChild(com.codebinge.firestore.codec.testdata.v1.Recursive value) {
      if (childBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        child_ = value;
      } else {
        childBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.codebinge.firestore.codec.testdata.v1.Recursive child = 2;</code>
     */
    public Builder setChild(
        com.codebinge.firestore.codec.testdata.v1.Recursive.Builder builderForValue) {
      if (childBuilder_ == null) {
        child_ = builderForValue.build();
      } else {
        childBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.codebinge.firestore.codec.testdata.v1.Recursive child = 2;</code>
     */
    public Builder mergeChild(com.codebinge.firestore.codec.testdata.v1.Recursive value) {
      if (childBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          child_ != null &&
          child_ != com.codebinge.firestore.codec.testdata.v1.Recursive.getDefaultInstance()) {
          getChildBuilder().mergeFrom(value);
        } else {
          child_ = value;
        }
      } else {
        childBuilder_.mergeFrom(value);
      }
      if (child_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.codebinge.firestore.codec.testdata.v1.Recursive child = 2;</code>
     */
    public Builder clearChild() {
      bitField0_ = (bitField0_ & ~0x00000002);
      child_ = null;
      if (childBuilder_ != null) {
        childBuilder_.dispose();
        childBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.codebinge.firestore.codec.testdata.v1.Recursive child = 2;</code>
     */
    public com.codebinge.firestore.codec.testdata.v1.Recursive.Builder getChildBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return internalGetChildFieldBuilder().getBuilder();
    }
    /**
     * <code>.codebinge.firestore.codec.testdata.v1.Recursive child = 2;</code>
     */
    public com.codebinge.firestore.codec.testdata.v1.RecursiveOrBuilder getChildOrBuilder() {
      if (childBuilder_ != null) {
        return childBuilder_.getMessageOrBuilder();
      } else {
        return child_ == null ?
            com.codebinge.firestore.codec.testdata.v1.Recursive.getDefaultInstance() : child_;
      }
    }
    /**
     * <code>.codebinge.firestore.codec.testdata.v1.Recursive child = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.codebinge.firestore.codec.testdata.v1.Recursive, com.codebinge.firestore.codec.testdata.v1.Recursive.Builder, com.codebinge.firestore.codec.testdata.v1.RecursiveOrBuilder> 
        internalGetChildFieldBuilder() {
      if (childBuilder_ == null) {
        childBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.codebinge.firestore.codec.testdata.v1.Recursive, com.codebinge.firestore.codec.testdata.v1.Recursive.Builder, com.codebinge.firestore.codec.testdata.v1.RecursiveOrBuilder>(
                getChild(),
                getParentForChildren(),
                isClean());
        child_ = null;
      }
      return childBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:codebinge.firestore.codec.testdata.v1.Recursive)
  }

  // @@protoc_insertion_point(class_scope:codebinge.firestore.codec.testdata.v1.Recursive)
  private static final com.codebinge.firestore.codec.testdata.v1.Recursive DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.codebinge.firestore.codec.testdata.v1.Recursive();
  }

  public static com.codebinge.firestore.codec.testdata.v1.Recursive getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Recursive>
      PARSER = new com.google.protobuf.AbstractParser<Recursive>() {
    @java.lang.Override
    public Recursive parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Recursive> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Recursive> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.codebinge.firestore.codec.testdata.v1.Recursive getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

