// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: testdata.proto
// Protobuf Java Version: 4.33.3

package com.codebinge.firestore.codec.testdata.v1;

@com.google.protobuf.Generated
public interface RecursiveOrBuilder extends
    // @@protoc_insertion_point(interface_extends:codebinge.firestore.codec.testdata.v1.Recursive)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string label = 1;</code>
   * @return The label.
   */
  java.lang.String getLabel();
  /**
   * <code>string label = 1;</code>
   * @return The bytes for label.
   */
  com.google.protobuf.ByteString
      getLabelBytes();

  /**
   * <code>.codebinge.firestore.codec.testdata.v1.Recursive child = 2;</code>
   * @return Whether the child field is set.
   */
  boolean hasChild();
  /**
   * <code>.codebinge.firestore.codec.testdata.v1.Recursive child = 2;</code>
   * @return The child.
   */
  com.codebinge.firestore.codec.testdata.v1.Recursive getChild();
  /**
   * <code>.codebinge.firestore.codec.testdata.v1.Recursive child = 2;</code>
   */
  com.codebinge.firestore.codec.testdata.v1.RecursiveOrBuilder getChildOrBuilder();
}
