// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: testdata.proto
// Protobuf Java Version: 4.33.3

package com.codebinge.firestore.codec.testdata.v1;

@com.google.protobuf.Generated
public interface ScalarsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:codebinge.firestore.codec.testdata.v1.Scalars)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string string_field = 1;</code>
   * @return The stringField.
   */
  java.lang.String getStringField();
  /**
   * <code>string string_field = 1;</code>
   * @return The bytes for stringField.
   */
  com.google.protobuf.ByteString
      getStringFieldBytes();

  /**
   * <code>bool bool_field = 2;</code>
   * @return The boolField.
   */
  boolean getBoolField();

  /**
   * <code>bytes bytes_field = 3;</code>
   * @return The bytesField.
   */
  com.google.protobuf.ByteString getBytesField();

  /**
   * <code>int32 int32_field = 4;</code>
   * @return The int32Field.
   */
  int getInt32Field();

  /**
   * <code>sint32 sint32_field = 5;</code>
   * @return The sint32Field.
   */
  int getSint32Field();

  /**
   * <code>sfixed32 sfixed32_field = 6;</code>
   * @return The sfixed32Field.
   */
  int getSfixed32Field();

  /**
   * <code>uint32 uint32_field = 7;</code>
   * @return The uint32Field.
   */
  int getUint32Field();

  /**
   * <code>fixed32 fixed32_field = 8;</code>
   * @return The fixed32Field.
   */
  int getFixed32Field();

  /**
   * <code>int64 int64_field = 9;</code>
   * @return The int64Field.
   */
  long getInt64Field();

  /**
   * <code>sint64 sint64_field = 10;</code>
   * @return The sint64Field.
   */
  long getSint64Field();

  /**
   * <code>sfixed64 sfixed64_field = 11;</code>
   * @return The sfixed64Field.
   */
  long getSfixed64Field();

  /**
   * <code>uint64 uint64_field = 12;</code>
   * @return The uint64Field.
   */
  long getUint64Field();

  /**
   * <code>fixed64 fixed64_field = 13;</code>
   * @return The fixed64Field.
   */
  long getFixed64Field();

  /**
   * <code>double double_field = 14;</code>
   * @return The doubleField.
   */
  double getDoubleField();

  /**
   * <pre>
   * scalars_full uses 1.5, exactly representable in binary32, so that vector
   * tests the type mapping alone. float_rounding uses 0.1 to pin the rule that
   * a float encodes as its binary32 value, 0.10000000149011612 (§2).
   * </pre>
   *
   * <code>float float_field = 15;</code>
   * @return The floatField.
   */
  float getFloatField();
}
