// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: testdata.proto
// Protobuf Java Version: 4.33.3

package com.codebinge.firestore.codec.testdata.v1;

/**
 * <pre>
 * `jstype = JS_STRING` changes only the in-memory JavaScript type of an int64
 * field; the Firestore type is still Integer (§8). Dart and Java ignore the
 * option entirely.
 * </pre>
 *
 * Protobuf type {@code codebinge.firestore.codec.testdata.v1.StringifiedInt64}
 */
@com.google.protobuf.Generated
public final class StringifiedInt64 extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:codebinge.firestore.codec.testdata.v1.StringifiedInt64)
    StringifiedInt64OrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 3,
      /* suffix= */ "",
      "StringifiedInt64");
  }
  // Use StringifiedInt64.newBuilder() to construct.
  private StringifiedInt64(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private StringifiedInt64() {
    ids_ = emptyLongList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.codebinge.firestore.codec.testdata.v1.Testdata.internal_static_codebinge_firestore_codec_testdata_v1_StringifiedInt64_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.codebinge.firestore.codec.testdata.v1.Testdata.internal_static_codebinge_firestore_codec_testdata_v1_StringifiedInt64_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.codebinge.firestore.codec.testdata.v1.StringifiedInt64.class, com.codebinge.firestore.codec.testdata.v1.StringifiedInt64.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_ = 0L;
  /**
   * <code>int64 id = 1 [jstype = JS_STRING];</code>
   * @return The id.
   */
  @java.lang.Override
  public long getId() {
    return id_;
  }

  public static final int IDS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.LongList ids_ =
      emptyLongList();
  /**
   * <code>repeated int64 ids = 2 [jstype = JS_STRING];</code>
   * @return A list containing the ids.
   */
  @java.lang.Override
  public java.util.List<java.lang.Long>
      getIdsList() {
    return ids_;
  }
  /**
   * <code>repeated int64 ids = 2 [jstype = JS_STRING];</code>
   * @return The count of ids.
   */
  public int getIdsCount() {
    return ids_.size();
  }
  /**
   * <code>repeated int64 ids = 2 [jstype = JS_STRING];</code>
   * @param index The index of the element to return.
   * @return The ids at the given index.
   */
  public long getIds(int index) {
    return ids_.getLong(index);
  }
  private int idsMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (getIdsList().size() > 0) {
      output.writeUInt32NoTag(18);
      output.writeUInt32NoTag(idsMemoizedSerializedSize);
    }
    for (int i = 0; i < ids_.size(); i++) {
      output.writeInt64NoTag(ids_.getLong(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < ids_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt64SizeNoTag(ids_.getLong(i));
      }
      size += dataSize;
      if (!getIdsList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      idsMemoizedSerializedSize = dataSize;
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.codebinge.firestore.codec.testdata.v1.StringifiedInt64)) {
      return super.equals(obj);
    }
    com.codebinge.firestore.codec.testdata.v1.StringifiedInt64 other = (com.codebinge.firestore.codec.testdata.v1.StringifiedInt64) obj;

    if (getId()
        != other.getId()) return false;
    if (!getIdsList()
        .equals(other.getIdsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    if (getIdsCount() > 0) {
      hash = (37 * hash) + IDS_FIELD_NUMBER;
      hash = (53 * hash) + getIdsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.codebinge.firestore.codec.testdata.v1.StringifiedInt64 parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.codebinge.firestore.codec.testdata.v1.StringifiedInt64 parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.codebinge.firestore.codec.testdata.v1.StringifiedInt64 parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.codebinge.firestore.codec.testdata.v1.StringifiedInt64 parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.codebinge.firestore.codec.testdata.v1.StringifiedInt64 parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.codebinge.firestore.codec.testdata.v1.StringifiedInt64 parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.codebinge.firestore.codec.testdata.v1.StringifiedInt64 parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.codebinge.firestore.codec.testdata.v1.StringifiedInt64 parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.codebinge.firestore.codec.testdata.v1.StringifiedInt64 parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.codebinge.firestore.codec.testdata.v1.StringifiedInt64 parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.codebinge.firestore.codec.testdata.v1.StringifiedInt64 parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.codebinge.firestore.codec.testdata.v1.StringifiedInt64 parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.codebinge.firestore.codec.testdata.v1.StringifiedInt64 prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * `jstype = JS_STRING` changes only the in-memory JavaScript type of an int64
   * field; the Firestore type is still Integer (§8). Dart and Java ignore the
   * option entirely.
   * </pre>
   *
   * Protobuf type {@code codebinge.firestore.codec.testdata.v1.StringifiedInt64}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:codebinge.firestore.codec.testdata.v1.StringifiedInt64)
      com.codebinge.firestore.codec.testdata.v1.StringifiedInt64OrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.codebinge.firestore.codec.testdata.v1.Testdata.internal_static_codebinge_firestore_codec_testdata_v1_StringifiedInt64_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.codebinge.firestore.codec.testdata.v1.Testdata.internal_static_codebinge_firestore_codec_testdata_v1_StringifiedInt64_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.codebinge.firestore.codec.testdata.v1.StringifiedInt64.class, com.codebinge.firestore.codec.testdata.v1.StringifiedInt64.Builder.class);
    }

    // Construct using com.codebinge.firestore.codec.testdata.v1.StringifiedInt64.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = 0L;
      ids_ = emptyLongList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.codebinge.firestore.codec.testdata.v1.Testdata.internal_static_codebinge_firestore_codec_testdata_v1_StringifiedInt64_descriptor;
    }

    @java.lang.Override
    public com.codebinge.firestore.codec.testdata.v1.StringifiedInt64 getDefaultInstanceForType() {
      return com.codebinge.firestore.codec.testdata.v1.StringifiedInt64.getDefaultInstance();
    }

    @java.lang.Override
    public com.codebinge.firestore.codec.testdata.v1.StringifiedInt64 build() {
      com.codebinge.firestore.codec.testdata.v1.StringifiedInt64 result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.codebinge.firestore.codec.testdata.v1.StringifiedInt64 buildPartial() {
      com.codebinge.firestore.codec.testdata.v1.StringifiedInt64 result = new com.codebinge.firestore.codec.testdata.v1.StringifiedInt64(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.codebinge.firestore.codec.testdata.v1.StringifiedInt64 result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        ids_.makeImmutable();
        result.ids_ = ids_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.codebinge.firestore.codec.testdata.v1.StringifiedInt64) {
        return mergeFrom((com.codebinge.firestore.codec.testdata.v1.StringifiedInt64)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.codebinge.firestore.codec.testdata.v1.StringifiedInt64 other) {
      if (other == com.codebinge.firestore.codec.testdata.v1.StringifiedInt64.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (!other.ids_.isEmpty()) {
        if (ids_.isEmpty()) {
          ids_ = other.ids_;
          ids_.makeImmutable();
          bitField0_ |= 0x00000002;
        } else {
          ensureIdsIsMutable();
          ids_.addAll(other.ids_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              id_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              long v = input.readInt64();
              ensureIdsIsMutable();
              ids_.addLong(v);
              break;
            } // case 16
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureIdsIsMutable();
              while (input.getBytesUntilLimit() > 0) {
                ids_.addLong(input.readInt64());
              }
              input.popLimit(limit);
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long id_ ;
    /**
     * <code>int64 id = 1 [jstype = JS_STRING];</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1 [jstype = JS_STRING];</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {

      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 1 [jstype = JS_STRING];</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.LongList ids_ = emptyLongList();
    private void ensureIdsIsMutable() {
      if (!ids_.isModifiable()) {
        ids_ = makeMutableCopy(ids_);
      }
      bitField0_ |= 0x00000002;
    }
    /**
     * <code>repeated int64 ids = 2 [jstype = JS_STRING];</code>
     * @return A list containing the ids.
     */
    public java.util.List<java.lang.Long>
        getIdsList() {
      ids_.makeImmutable();
      return ids_;
    }
    /**
     * <code>repeated int64 ids = 2 [jstype = JS_STRING];</code>
     * @return The count of ids.
     */
    public int getIdsCount() {
      return ids_.size();
    }
    /**
     * <code>repeated int64 ids = 2 [jstype = JS_STRING];</code>
     * @param index The index of the element to return.
     * @return The ids at the given index.
     */
    public long getIds(int index) {
      return ids_.getLong(index);
    }
    /**
     * <code>repeated int64 ids = 2 [jstype = JS_STRING];</code>
     * @param index The index to set the value at.
     * @param value The ids to set.
     * @return This builder for chaining.
     */
    public Builder setIds(
        int index, long value) {

      ensureIdsIsMutable();
      ids_.setLong(index, value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 ids = 2 [jstype = JS_STRING];</code>
     * @param value The ids to add.
     * @return This builder for chaining.
     */
    public Builder addIds(long value) {

      ensureIdsIsMutable();
      ids_.addLong(value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 ids = 2 [jstype = JS_STRING];</code>
     * @param values The ids to add.
     * @return This builder for chaining.
     */
    public Builder addAllIds(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, ids_);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 ids = 2 [jstype = JS_STRING];</code>
     * @return This builder for chaining.
     */
    public Builder clearIds() {
      ids_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:codebinge.firestore.codec.testdata.v1.StringifiedInt64)
  }

  // @@protoc_insertion_point(class_scope:codebinge.firestore.codec.testdata.v1.StringifiedInt64)
  private static final com.codebinge.firestore.codec.testdata.v1.StringifiedInt64 DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.codebinge.firestore.codec.testdata.v1.StringifiedInt64();
  }

  public static com.codebinge.firestore.codec.testdata.v1.StringifiedInt64 getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StringifiedInt64>
      PARSER = new com.google.protobuf.AbstractParser<StringifiedInt64>() {
    @java.lang.Override
    public StringifiedInt64 parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<StringifiedInt64> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StringifiedInt64> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.codebinge.firestore.codec.testdata.v1.StringifiedInt64 getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

