// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: testdata.proto
// Protobuf Java Version: 4.33.3

package com.codebinge.firestore.codec.testdata.v1;

@com.google.protobuf.Generated
public interface StringifiedInt64OrBuilder extends
    // @@protoc_insertion_point(interface_extends:codebinge.firestore.codec.testdata.v1.StringifiedInt64)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1 [jstype = JS_STRING];</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>repeated int64 ids = 2 [jstype = JS_STRING];</code>
   * @return A list containing the ids.
   */
  java.util.List<java.lang.Long> getIdsList();
  /**
   * <code>repeated int64 ids = 2 [jstype = JS_STRING];</code>
   * @return The count of ids.
   */
  int getIdsCount();
  /**
   * <code>repeated int64 ids = 2 [jstype = JS_STRING];</code>
   * @param index The index of the element to return.
   * @return The ids at the given index.
   */
  long getIds(int index);
}
