// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: invalid.proto
// Protobuf Java Version: 4.33.3

package com.codebinge.firestore.codec.testdata.v1;

@com.google.protobuf.Generated
public interface StructFieldOrBuilder extends
    // @@protoc_insertion_point(interface_extends:codebinge.firestore.codec.testdata.v1.StructField)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.Struct bad = 1;</code>
   * @return Whether the bad field is set.
   */
  boolean hasBad();
  /**
   * <code>.google.protobuf.Struct bad = 1;</code>
   * @return The bad.
   */
  com.google.protobuf.Struct getBad();
  /**
   * <code>.google.protobuf.Struct bad = 1;</code>
   */
  com.google.protobuf.StructOrBuilder getBadOrBuilder();
}
