// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: testdata.proto
// Protobuf Java Version: 4.33.3

package com.codebinge.firestore.codec.testdata.v1;

@com.google.protobuf.Generated
public final class Testdata extends com.google.protobuf.GeneratedFile {
  private Testdata() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 3,
      /* suffix= */ "",
      "Testdata");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_codebinge_firestore_codec_testdata_v1_Scalars_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_codebinge_firestore_codec_testdata_v1_Scalars_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_codebinge_firestore_codec_testdata_v1_Doubles_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_codebinge_firestore_codec_testdata_v1_Doubles_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_codebinge_firestore_codec_testdata_v1_Enums_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_codebinge_firestore_codec_testdata_v1_Enums_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_codebinge_firestore_codec_testdata_v1_Inner_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_codebinge_firestore_codec_testdata_v1_Inner_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_codebinge_firestore_codec_testdata_v1_Presence_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_codebinge_firestore_codec_testdata_v1_Presence_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_codebinge_firestore_codec_testdata_v1_Unsigned_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_codebinge_firestore_codec_testdata_v1_Unsigned_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_codebinge_firestore_codec_testdata_v1_WellKnown_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_codebinge_firestore_codec_testdata_v1_WellKnown_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_codebinge_firestore_codec_testdata_v1_Composite_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_codebinge_firestore_codec_testdata_v1_Composite_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_codebinge_firestore_codec_testdata_v1_Composite_StringMapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_codebinge_firestore_codec_testdata_v1_Composite_StringMapEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_codebinge_firestore_codec_testdata_v1_Composite_MessageMapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_codebinge_firestore_codec_testdata_v1_Composite_MessageMapEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_codebinge_firestore_codec_testdata_v1_Options_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_codebinge_firestore_codec_testdata_v1_Options_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_codebinge_firestore_codec_testdata_v1_Choice_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_codebinge_firestore_codec_testdata_v1_Choice_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_codebinge_firestore_codec_testdata_v1_StringifiedInt64_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_codebinge_firestore_codec_testdata_v1_StringifiedInt64_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_codebinge_firestore_codec_testdata_v1_Recursive_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_codebinge_firestore_codec_testdata_v1_Recursive_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016testdata.proto\022%codebinge.firestore.co" +
      "dec.testdata.v1\032\036google/protobuf/duratio" +
      "n.proto\032\037google/protobuf/timestamp.proto" +
      "\032\030google/type/latlng.proto\032*codebinge/fi" +
      "restore/codec/v1/options.proto\"\323\002\n\007Scala" +
      "rs\022\024\n\014string_field\030\001 \001(\t\022\022\n\nbool_field\030\002" +
      " \001(\010\022\023\n\013bytes_field\030\003 \001(\014\022\023\n\013int32_field" +
      "\030\004 \001(\005\022\024\n\014sint32_field\030\005 \001(\021\022\026\n\016sfixed32" +
      "_field\030\006 \001(\017\022\024\n\014uint32_field\030\007 \001(\r\022\025\n\rfi" +
      "xed32_field\030\010 \001(\007\022\023\n\013int64_field\030\t \001(\003\022\024" +
      "\n\014sint64_field\030\n \001(\022\022\026\n\016sfixed64_field\030\013" +
      " \001(\020\022\024\n\014uint64_field\030\014 \001(\004\022\025\n\rfixed64_fi" +
      "eld\030\r \001(\006\022\024\n\014double_field\030\016 \001(\001\022\023\n\013float" +
      "_field\030\017 \001(\002\"J\n\007Doubles\022\021\n\tnan_field\030\001 \001" +
      "(\001\022\025\n\rpos_inf_field\030\002 \001(\001\022\025\n\rneg_inf_fie" +
      "ld\030\003 \001(\001\"\221\001\n\005Enums\022>\n\007as_name\030\001 \001(\0162-.co" +
      "debinge.firestore.codec.testdata.v1.Stat" +
      "us\022H\n\tas_number\030\002 \001(\0162-.codebinge.firest" +
      "ore.codec.testdata.v1.StatusB\006\202\265\030\002\030\001\"\026\n\005" +
      "Inner\022\r\n\005value\030\001 \001(\t\"\225\001\n\010Presence\022\027\n\nopt" +
      "_string\030\001 \001(\tH\000\210\001\001\022\026\n\topt_int32\030\002 \001(\005H\001\210" +
      "\001\001\022;\n\005inner\030\003 \001(\0132,.codebinge.firestore." +
      "codec.testdata.v1.InnerB\r\n\013_opt_stringB\014" +
      "\n\n_opt_int32\"\240\001\n\010Unsigned\022\014\n\004zero\030\001 \001(\004\022" +
      "\022\n\nmax_signed\030\002 \001(\004\022\031\n\021min_unsigned_only" +
      "\030\003 \001(\004\022\024\n\014max_unsigned\030\004 \001(\004\022\r\n\005fixed\030\005 " +
      "\001(\006\022\032\n\nas_integer\030\006 \001(\004B\006\202\265\030\002(\002\022\026\n\006alway" +
      "s\030\007 \001(\004B\006\202\265\030\002 \000\"\216\001\n\tWellKnown\022-\n\ttimesta" +
      "mp\030\001 \001(\0132\032.google.protobuf.Timestamp\022+\n\010" +
      "duration\030\002 \001(\0132\031.google.protobuf.Duratio" +
      "n\022%\n\010location\030\003 \001(\0132\023.google.type.LatLng" +
      "\"\331\003\n\tComposite\022<\n\006single\030\001 \001(\0132,.codebin" +
      "ge.firestore.codec.testdata.v1.Inner\022\017\n\007" +
      "strings\030\002 \003(\t\022>\n\010messages\030\003 \003(\0132,.codebi" +
      "nge.firestore.codec.testdata.v1.Inner\022S\n" +
      "\nstring_map\030\004 \003(\0132?.codebinge.firestore." +
      "codec.testdata.v1.Composite.StringMapEnt" +
      "ry\022U\n\013message_map\030\005 \003(\0132@.codebinge.fire" +
      "store.codec.testdata.v1.Composite.Messag" +
      "eMapEntry\0320\n\016StringMapEntry\022\013\n\003key\030\001 \001(\t" +
      "\022\r\n\005value\030\002 \001(\t:\0028\001\032_\n\017MessageMapEntry\022\013" +
      "\n\003key\030\001 \001(\t\022;\n\005value\030\002 \001(\0132,.codebinge.f" +
      "irestore.codec.testdata.v1.Inner:\0028\001\"T\n\007" +
      "Options\022\014\n\004kept\030\001 \001(\t\022\027\n\007dropped\030\002 \001(\tB\006" +
      "\202\265\030\002\010\001\022\"\n\007renamed\030\003 \001(\tB\021\202\265\030\r\022\013stored_na" +
      "me\"q\n\006Choice\022\016\n\004text\030\001 \001(\tH\000\022\020\n\006number\030\002" +
      " \001(\005H\000\022=\n\005inner\030\003 \001(\0132,.codebinge.firest" +
      "ore.codec.testdata.v1.InnerH\000B\006\n\004kind\"3\n" +
      "\020StringifiedInt64\022\016\n\002id\030\001 \001(\003B\0020\001\022\017\n\003ids" +
      "\030\002 \003(\003B\0020\001\"[\n\tRecursive\022\r\n\005label\030\001 \001(\t\022?" +
      "\n\005child\030\002 \001(\01320.codebinge.firestore.code" +
      "c.testdata.v1.Recursive*D\n\006Status\022\022\n\016STA" +
      "TUS_UNKNOWN\020\000\022\021\n\rSTATUS_ACTIVE\020\001\022\023\n\017STAT" +
      "US_ARCHIVED\020\002B-\n)com.codebinge.firestore" +
      ".codec.testdata.v1P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DurationProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.google.type.LatLngProto.getDescriptor(),
          com.codebinge.firestore.codec.v1.Options.getDescriptor(),
        });
    internal_static_codebinge_firestore_codec_testdata_v1_Scalars_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_codebinge_firestore_codec_testdata_v1_Scalars_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_codebinge_firestore_codec_testdata_v1_Scalars_descriptor,
        new java.lang.String[] { "StringField", "BoolField", "BytesField", "Int32Field", "Sint32Field", "Sfixed32Field", "Uint32Field", "Fixed32Field", "Int64Field", "Sint64Field", "Sfixed64Field", "Uint64Field", "Fixed64Field", "DoubleField", "FloatField", });
    internal_static_codebinge_firestore_codec_testdata_v1_Doubles_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_codebinge_firestore_codec_testdata_v1_Doubles_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_codebinge_firestore_codec_testdata_v1_Doubles_descriptor,
        new java.lang.String[] { "NanField", "PosInfField", "NegInfField", });
    internal_static_codebinge_firestore_codec_testdata_v1_Enums_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_codebinge_firestore_codec_testdata_v1_Enums_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_codebinge_firestore_codec_testdata_v1_Enums_descriptor,
        new java.lang.String[] { "AsName", "AsNumber", });
    internal_static_codebinge_firestore_codec_testdata_v1_Inner_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_codebinge_firestore_codec_testdata_v1_Inner_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_codebinge_firestore_codec_testdata_v1_Inner_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_codebinge_firestore_codec_testdata_v1_Presence_descriptor =
      getDescriptor().getMessageType(4);
    internal_static_codebinge_firestore_codec_testdata_v1_Presence_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_codebinge_firestore_codec_testdata_v1_Presence_descriptor,
        new java.lang.String[] { "OptString", "OptInt32", "Inner", });
    internal_static_codebinge_firestore_codec_testdata_v1_Unsigned_descriptor =
      getDescriptor().getMessageType(5);
    internal_static_codebinge_firestore_codec_testdata_v1_Unsigned_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_codebinge_firestore_codec_testdata_v1_Unsigned_descriptor,
        new java.lang.String[] { "Zero", "MaxSigned", "MinUnsignedOnly", "MaxUnsigned", "Fixed", "AsInteger", "Always", });
    internal_static_codebinge_firestore_codec_testdata_v1_WellKnown_descriptor =
      getDescriptor().getMessageType(6);
    internal_static_codebinge_firestore_codec_testdata_v1_WellKnown_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_codebinge_firestore_codec_testdata_v1_WellKnown_descriptor,
        new java.lang.String[] { "Timestamp", "Duration", "Location", });
    internal_static_codebinge_firestore_codec_testdata_v1_Composite_descriptor =
      getDescriptor().getMessageType(7);
    internal_static_codebinge_firestore_codec_testdata_v1_Composite_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_codebinge_firestore_codec_testdata_v1_Composite_descriptor,
        new java.lang.String[] { "Single", "Strings", "Messages", "StringMap", "MessageMap", });
    internal_static_codebinge_firestore_codec_testdata_v1_Composite_StringMapEntry_descriptor =
      internal_static_codebinge_firestore_codec_testdata_v1_Composite_descriptor.getNestedType(0);
    internal_static_codebinge_firestore_codec_testdata_v1_Composite_StringMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_codebinge_firestore_codec_testdata_v1_Composite_StringMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_codebinge_firestore_codec_testdata_v1_Composite_MessageMapEntry_descriptor =
      internal_static_codebinge_firestore_codec_testdata_v1_Composite_descriptor.getNestedType(1);
    internal_static_codebinge_firestore_codec_testdata_v1_Composite_MessageMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_codebinge_firestore_codec_testdata_v1_Composite_MessageMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_codebinge_firestore_codec_testdata_v1_Options_descriptor =
      getDescriptor().getMessageType(8);
    internal_static_codebinge_firestore_codec_testdata_v1_Options_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_codebinge_firestore_codec_testdata_v1_Options_descriptor,
        new java.lang.String[] { "Kept", "Dropped", "Renamed", });
    internal_static_codebinge_firestore_codec_testdata_v1_Choice_descriptor =
      getDescriptor().getMessageType(9);
    internal_static_codebinge_firestore_codec_testdata_v1_Choice_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_codebinge_firestore_codec_testdata_v1_Choice_descriptor,
        new java.lang.String[] { "Text", "Number", "Inner", "Kind", });
    internal_static_codebinge_firestore_codec_testdata_v1_StringifiedInt64_descriptor =
      getDescriptor().getMessageType(10);
    internal_static_codebinge_firestore_codec_testdata_v1_StringifiedInt64_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_codebinge_firestore_codec_testdata_v1_StringifiedInt64_descriptor,
        new java.lang.String[] { "Id", "Ids", });
    internal_static_codebinge_firestore_codec_testdata_v1_Recursive_descriptor =
      getDescriptor().getMessageType(11);
    internal_static_codebinge_firestore_codec_testdata_v1_Recursive_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_codebinge_firestore_codec_testdata_v1_Recursive_descriptor,
        new java.lang.String[] { "Label", "Child", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.DurationProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.type.LatLngProto.getDescriptor();
    com.codebinge.firestore.codec.v1.Options.getDescriptor();
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.codebinge.firestore.codec.v1.Options.field);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
