// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: testdata.proto
// Protobuf Java Version: 4.33.3

package com.codebinge.firestore.codec.testdata.v1;

/**
 * <pre>
 * Nesting depth through arrays and maps (§5). Every map and array is a level,
 * so a Tree reached through `children` or `named` sits two levels below its
 * parent, not one, and `tags` is a level of its own.
 * </pre>
 *
 * Protobuf type {@code codebinge.firestore.codec.testdata.v1.Tree}
 */
@com.google.protobuf.Generated
public final class Tree extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:codebinge.firestore.codec.testdata.v1.Tree)
    TreeOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 3,
      /* suffix= */ "",
      "Tree");
  }
  // Use Tree.newBuilder() to construct.
  private Tree(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Tree() {
    label_ = "";
    children_ = java.util.Collections.emptyList();
    tags_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.codebinge.firestore.codec.testdata.v1.Testdata.internal_static_codebinge_firestore_codec_testdata_v1_Tree_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
    switch (number) {
      case 3:
        return internalGetNamed();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.codebinge.firestore.codec.testdata.v1.Testdata.internal_static_codebinge_firestore_codec_testdata_v1_Tree_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.codebinge.firestore.codec.testdata.v1.Tree.class, com.codebinge.firestore.codec.testdata.v1.Tree.Builder.class);
  }

  public static final int LABEL_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object label_ = "";
  /**
   * <code>string label = 1;</code>
   * @return The label.
   */
  @java.lang.Override
  public java.lang.String getLabel() {
    java.lang.Object ref = label_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      label_ = s;
      return s;
    }
  }
  /**
   * <code>string label = 1;</code>
   * @return The bytes for label.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLabelBytes() {
    java.lang.Object ref = label_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      label_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CHILDREN_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<com.codebinge.firestore.codec.testdata.v1.Tree> children_;
  /**
   * <code>repeated .codebinge.firestore.codec.testdata.v1.Tree children = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.codebinge.firestore.codec.testdata.v1.Tree> getChildrenList() {
    return children_;
  }
  /**
   * <code>repeated .codebinge.firestore.codec.testdata.v1.Tree children = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.codebinge.firestore.codec.testdata.v1.TreeOrBuilder> 
      getChildrenOrBuilderList() {
    return children_;
  }
  /**
   * <code>repeated .codebinge.firestore.codec.testdata.v1.Tree children = 2;</code>
   */
  @java.lang.Override
  public int getChildrenCount() {
    return children_.size();
  }
  /**
   * <code>repeated .codebinge.firestore.codec.testdata.v1.Tree children = 2;</code>
   */
  @java.lang.Override
  public com.codebinge.firestore.codec.testdata.v1.Tree getChildren(int index) {
    return children_.get(index);
  }
  /**
   * <code>repeated .codebinge.firestore.codec.testdata.v1.Tree children = 2;</code>
   */
  @java.lang.Override
  public com.codebinge.firestore.codec.testdata.v1.TreeOrBuilder getChildrenOrBuilder(
      int index) {
    return children_.get(index);
  }

  public static final int NAMED_FIELD_NUMBER = 3;
  private static final class NamedDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, com.codebinge.firestore.codec.testdata.v1.Tree> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, com.codebinge.firestore.codec.testdata.v1.Tree>newDefaultInstance(
                com.codebinge.firestore.codec.testdata.v1.Testdata.internal_static_codebinge_firestore_codec_testdata_v1_Tree_NamedEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                com.codebinge.firestore.codec.testdata.v1.Tree.getDefaultInstance());
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, com.codebinge.firestore.codec.testdata.v1.Tree> named_;
  private com.google.protobuf.MapField<java.lang.String, com.codebinge.firestore.codec.testdata.v1.Tree>
  internalGetNamed() {
    if (named_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          NamedDefaultEntryHolder.defaultEntry);
    }
    return named_;
  }
  public int getNamedCount() {
    return internalGetNamed().getMap().size();
  }
  /**
   * <code>map&lt;string, .codebinge.firestore.codec.testdata.v1.Tree&gt; named = 3;</code>
   */
  @java.lang.Override
  public boolean containsNamed(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetNamed().getMap().containsKey(key);
  }
  /**
   * Use {@link #getNamedMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, com.codebinge.firestore.codec.testdata.v1.Tree> getNamed() {
    return getNamedMap();
  }
  /**
   * <code>map&lt;string, .codebinge.firestore.codec.testdata.v1.Tree&gt; named = 3;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, com.codebinge.firestore.codec.testdata.v1.Tree> getNamedMap() {
    return internalGetNamed().getMap();
  }
  /**
   * <code>map&lt;string, .codebinge.firestore.codec.testdata.v1.Tree&gt; named = 3;</code>
   */
  @java.lang.Override
  public /* nullable */
com.codebinge.firestore.codec.testdata.v1.Tree getNamedOrDefault(
      java.lang.String key,
      /* nullable */
com.codebinge.firestore.codec.testdata.v1.Tree defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, com.codebinge.firestore.codec.testdata.v1.Tree> map =
        internalGetNamed().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, .codebinge.firestore.codec.testdata.v1.Tree&gt; named = 3;</code>
   */
  @java.lang.Override
  public com.codebinge.firestore.codec.testdata.v1.Tree getNamedOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, com.codebinge.firestore.codec.testdata.v1.Tree> map =
        internalGetNamed().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int TAGS_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList tags_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string tags = 4;</code>
   * @return A list containing the tags.
   */
  public com.google.protobuf.ProtocolStringList
      getTagsList() {
    return tags_;
  }
  /**
   * <code>repeated string tags = 4;</code>
   * @return The count of tags.
   */
  public int getTagsCount() {
    return tags_.size();
  }
  /**
   * <code>repeated string tags = 4;</code>
   * @param index The index of the element to return.
   * @return The tags at the given index.
   */
  public java.lang.String getTags(int index) {
    return tags_.get(index);
  }
  /**
   * <code>repeated string tags = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the tags at the given index.
   */
  public com.google.protobuf.ByteString
      getTagsBytes(int index) {
    return tags_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(label_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, label_);
    }
    for (int i = 0; i < children_.size(); i++) {
      output.writeMessage(2, children_.get(i));
    }
    com.google.protobuf.GeneratedMessage
      .serializeStringMapTo(
        output,
        internalGetNamed(),
        NamedDefaultEntryHolder.defaultEntry,
        3);
    for (int i = 0; i < tags_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, tags_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(label_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, label_);
    }
    for (int i = 0; i < children_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, children_.get(i));
    }
    for (java.util.Map.Entry<java.lang.String, com.codebinge.firestore.codec.testdata.v1.Tree> entry
         : internalGetNamed().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, com.codebinge.firestore.codec.testdata.v1.Tree>
      named__ = NamedDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, named__);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < tags_.size(); i++) {
        dataSize += computeStringSizeNoTag(tags_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getTagsList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.codebinge.firestore.codec.testdata.v1.Tree)) {
      return super.equals(obj);
    }
    com.codebinge.firestore.codec.testdata.v1.Tree other = (com.codebinge.firestore.codec.testdata.v1.Tree) obj;

    if (!getLabel()
        .equals(other.getLabel())) return false;
    if (!getChildrenList()
        .equals(other.getChildrenList())) return false;
    if (!internalGetNamed().equals(
        other.internalGetNamed())) return false;
    if (!getTagsList()
        .equals(other.getTagsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LABEL_FIELD_NUMBER;
    hash = (53 * hash) + getLabel().hashCode();
    if (getChildrenCount() > 0) {
      hash = (37 * hash) + CHILDREN_FIELD_NUMBER;
      hash = (53 * hash) + getChildrenList().hashCode();
    }
    if (!internalGetNamed().getMap().isEmpty()) {
      hash = (37 * hash) + NAMED_FIELD_NUMBER;
      hash = (53 * hash) + internalGetNamed().hashCode();
    }
    if (getTagsCount() > 0) {
      hash = (37 * hash) + TAGS_FIELD_NUMBER;
      hash = (53 * hash) + getTagsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.codebinge.firestore.codec.testdata.v1.Tree parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Tree parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Tree parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Tree parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Tree parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Tree parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Tree parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Tree parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.codebinge.firestore.codec.testdata.v1.Tree parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.codebinge.firestore.codec.testdata.v1.Tree parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Tree parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Tree parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.codebinge.firestore.codec.testdata.v1.Tree prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Nesting depth through arrays and maps (§5). Every map and array is a level,
   * so a Tree reached through `children` or `named` sits two levels below its
   * parent, not one, and `tags` is a level of its own.
   * </pre>
   *
   * Protobuf type {@code codebinge.firestore.codec.testdata.v1.Tree}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:codebinge.firestore.codec.testdata.v1.Tree)
      com.codebinge.firestore.codec.testdata.v1.TreeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.codebinge.firestore.codec.testdata.v1.Testdata.internal_static_codebinge_firestore_codec_testdata_v1_Tree_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 3:
          return internalGetNamed();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
      switch (number) {
        case 3:
          return internalGetMutableNamed();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.codebinge.firestore.codec.testdata.v1.Testdata.internal_static_codebinge_firestore_codec_testdata_v1_Tree_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.codebinge.firestore.codec.testdata.v1.Tree.class, com.codebinge.firestore.codec.testdata.v1.Tree.Builder.class);
    }

    // Construct using com.codebinge.firestore.codec.testdata.v1.Tree.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      label_ = "";
      if (childrenBuilder_ == null) {
        children_ = java.util.Collections.emptyList();
      } else {
        children_ = null;
        childrenBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      internalGetMutableNamed().clear();
      tags_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.codebinge.firestore.codec.testdata.v1.Testdata.internal_static_codebinge_firestore_codec_testdata_v1_Tree_descriptor;
    }

    @java.lang.Override
    public com.codebinge.firestore.codec.testdata.v1.Tree getDefaultInstanceForType() {
      return com.codebinge.firestore.codec.testdata.v1.Tree.getDefaultInstance();
    }

    @java.lang.Override
    public com.codebinge.firestore.codec.testdata.v1.Tree build() {
      com.codebinge.firestore.codec.testdata.v1.Tree result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.codebinge.firestore.codec.testdata.v1.Tree buildPartial() {
      com.codebinge.firestore.codec.testdata.v1.Tree result = new com.codebinge.firestore.codec.testdata.v1.Tree(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.codebinge.firestore.codec.testdata.v1.Tree result) {
      if (childrenBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          children_ = java.util.Collections.unmodifiableList(children_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.children_ = children_;
      } else {
        result.children_ = childrenBuilder_.build();
      }
    }

    private void buildPartial0(com.codebinge.firestore.codec.testdata.v1.Tree result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.label_ = label_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.named_ = internalGetNamed().build(NamedDefaultEntryHolder.defaultEntry);
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        tags_.makeImmutable();
        result.tags_ = tags_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.codebinge.firestore.codec.testdata.v1.Tree) {
        return mergeFrom((com.codebinge.firestore.codec.testdata.v1.Tree)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.codebinge.firestore.codec.testdata.v1.Tree other) {
      if (other == com.codebinge.firestore.codec.testdata.v1.Tree.getDefaultInstance()) return this;
      if (!other.getLabel().isEmpty()) {
        label_ = other.label_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (childrenBuilder_ == null) {
        if (!other.children_.isEmpty()) {
          if (children_.isEmpty()) {
            children_ = other.children_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureChildrenIsMutable();
            children_.addAll(other.children_);
          }
          onChanged();
        }
      } else {
        if (!other.children_.isEmpty()) {
          if (childrenBuilder_.isEmpty()) {
            childrenBuilder_.dispose();
            childrenBuilder_ = null;
            children_ = other.children_;
            bitField0_ = (bitField0_ & ~0x00000002);
            childrenBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetChildrenFieldBuilder() : null;
          } else {
            childrenBuilder_.addAllMessages(other.children_);
          }
        }
      }
      internalGetMutableNamed().mergeFrom(
          other.internalGetNamed());
      bitField0_ |= 0x00000004;
      if (!other.tags_.isEmpty()) {
        if (tags_.isEmpty()) {
          tags_ = other.tags_;
          bitField0_ |= 0x00000008;
        } else {
          ensureTagsIsMutable();
          tags_.addAll(other.tags_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              label_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              com.codebinge.firestore.codec.testdata.v1.Tree m =
                  input.readMessage(
                      com.codebinge.firestore.codec.testdata.v1.Tree.parser(),
                      extensionRegistry);
              if (childrenBuilder_ == null) {
                ensureChildrenIsMutable();
                children_.add(m);
              } else {
                childrenBuilder_.addMessage(m);
              }
              break;
            } // case 18
            case 26: {
              com.google.protobuf.MapEntry<java.lang.String, com.codebinge.firestore.codec.testdata.v1.Tree>
              named__ = input.readMessage(
                  NamedDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableNamed().ensureBuilderMap().put(
                  named__.getKey(), named__.getValue());
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureTagsIsMutable();
              tags_.add(s);
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object label_ = "";
    /**
     * <code>string label = 1;</code>
     * @return The label.
     */
    public java.lang.String getLabel() {
      java.lang.Object ref = label_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        label_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string label = 1;</code>
     * @return The bytes for label.
     */
    public com.google.protobuf.ByteString
        getLabelBytes() {
      java.lang.Object ref = label_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        label_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string label = 1;</code>
     * @param value The label to set.
     * @return This builder for chaining.
     */
    public Builder setLabel(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      label_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string label = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearLabel() {
      label_ = getDefaultInstance().getLabel();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string label = 1;</code>
     * @param value The bytes for label to set.
     * @return This builder for chaining.
     */
    public Builder setLabelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      label_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.util.List<com.codebinge.firestore.codec.testdata.v1.Tree> children_ =
      java.util.Collections.emptyList();
    private void ensureChildrenIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        children_ = new java.util.ArrayList<com.codebinge.firestore.codec.testdata.v1.Tree>(children_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.codebinge.firestore.codec.testdata.v1.Tree, com.codebinge.firestore.codec.testdata.v1.Tree.Builder, com.codebinge.firestore.codec.testdata.v1.TreeOrBuilder> childrenBuilder_;

    /**
     * <code>repeated .codebinge.firestore.codec.testdata.v1.Tree children = 2;</code>
     */
    public java.util.List<com.codebinge.firestore.codec.testdata.v1.Tree> getChildrenList() {
      if (childrenBuilder_ == null) {
        return java.util.Collections.unmodifiableList(children_);
      } else {
        return childrenBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .codebinge.firestore.codec.testdata.v1.Tree children = 2;</code>
     */
    public int getChildrenCount() {
      if (childrenBuilder_ == null) {
        return children_.size();
      } else {
        return childrenBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .codebinge.firestore.codec.testdata.v1.Tree children = 2;</code>
     */
    public com.codebinge.firestore.codec.testdata.v1.Tree getChildren(int index) {
      if (childrenBuilder_ == null) {
        return children_.get(index);
      } else {
        return childrenBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .codebinge.firestore.codec.testdata.v1.Tree children = 2;</code>
     */
    public Builder setChildren(
        int index, com.codebinge.firestore.codec.testdata.v1.Tree value) {
      if (childrenBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChildrenIsMutable();
        children_.set(index, value);
        onChanged();
      } else {
        childrenBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .codebinge.firestore.codec.testdata.v1.Tree children = 2;</code>
     */
    public Builder setChildren(
        int index, com.codebinge.firestore.codec.testdata.v1.Tree.Builder builderForValue) {
      if (childrenBuilder_ == null) {
        ensureChildrenIsMutable();
        children_.set(index, builderForValue.build());
        onChanged();
      } else {
        childrenBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .codebinge.firestore.codec.testdata.v1.Tree children = 2;</code>
     */
    public Builder addChildren(com.codebinge.firestore.codec.testdata.v1.Tree value) {
      if (childrenBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChildrenIsMutable();
        children_.add(value);
        onChanged();
      } else {
        childrenBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .codebinge.firestore.codec.testdata.v1.Tree children = 2;</code>
     */
    public Builder addChildren(
        int index, com.codebinge.firestore.codec.testdata.v1.Tree value) {
      if (childrenBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChildrenIsMutable();
        children_.add(index, value);
        onChanged();
      } else {
        childrenBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .codebinge.firestore.codec.testdata.v1.Tree children = 2;</code>
     */
    public Builder addChildren(
        com.codebinge.firestore.codec.testdata.v1.Tree.Builder builderForValue) {
      if (childrenBuilder_ == null) {
        ensureChildrenIsMutable();
        children_.add(builderForValue.build());
        onChanged();
      } else {
        childrenBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .codebinge.firestore.codec.testdata.v1.Tree children = 2;</code>
     */
    public Builder addChildren(
        int index, com.codebinge.firestore.codec.testdata.v1.Tree.Builder builderForValue) {
      if (childrenBuilder_ == null) {
        ensureChildrenIsMutable();
        children_.add(index, builderForValue.build());
        onChanged();
      } else {
        childrenBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .codebinge.firestore.codec.testdata.v1.Tree children = 2;</code>
     */
    public Builder addAllChildren(
        java.lang.Iterable<? extends com.codebinge.firestore.codec.testdata.v1.Tree> values) {
      if (childrenBuilder_ == null) {
        ensureChildrenIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, children_);
        onChanged();
      } else {
        childrenBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .codebinge.firestore.codec.testdata.v1.Tree children = 2;</code>
     */
    public Builder clearChildren() {
      if (childrenBuilder_ == null) {
        children_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        childrenBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .codebinge.firestore.codec.testdata.v1.Tree children = 2;</code>
     */
    public Builder removeChildren(int index) {
      if (childrenBuilder_ == null) {
        ensureChildrenIsMutable();
        children_.remove(index);
        onChanged();
      } else {
        childrenBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .codebinge.firestore.codec.testdata.v1.Tree children = 2;</code>
     */
    public com.codebinge.firestore.codec.testdata.v1.Tree.Builder getChildrenBuilder(
        int index) {
      return internalGetChildrenFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .codebinge.firestore.codec.testdata.v1.Tree children = 2;</code>
     */
    public com.codebinge.firestore.codec.testdata.v1.TreeOrBuilder getChildrenOrBuilder(
        int index) {
      if (childrenBuilder_ == null) {
        return children_.get(index);  } else {
        return childrenBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .codebinge.firestore.codec.testdata.v1.Tree children = 2;</code>
     */
    public java.util.List<? extends com.codebinge.firestore.codec.testdata.v1.TreeOrBuilder> 
         getChildrenOrBuilderList() {
      if (childrenBuilder_ != null) {
        return childrenBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(children_);
      }
    }
    /**
     * <code>repeated .codebinge.firestore.codec.testdata.v1.Tree children = 2;</code>
     */
    public com.codebinge.firestore.codec.testdata.v1.Tree.Builder addChildrenBuilder() {
      return internalGetChildrenFieldBuilder().addBuilder(
          com.codebinge.firestore.codec.testdata.v1.Tree.getDefaultInstance());
    }
    /**
     * <code>repeated .codebinge.firestore.codec.testdata.v1.Tree children = 2;</code>
     */
    public com.codebinge.firestore.codec.testdata.v1.Tree.Builder addChildrenBuilder(
        int index) {
      return internalGetChildrenFieldBuilder().addBuilder(
          index, com.codebinge.firestore.codec.testdata.v1.Tree.getDefaultInstance());
    }
    /**
     * <code>repeated .codebinge.firestore.codec.testdata.v1.Tree children = 2;</code>
     */
    public java.util.List<com.codebinge.firestore.codec.testdata.v1.Tree.Builder> 
         getChildrenBuilderList() {
      return internalGetChildrenFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.codebinge.firestore.codec.testdata.v1.Tree, com.codebinge.firestore.codec.testdata.v1.Tree.Builder, com.codebinge.firestore.codec.testdata.v1.TreeOrBuilder> 
        internalGetChildrenFieldBuilder() {
      if (childrenBuilder_ == null) {
        childrenBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.codebinge.firestore.codec.testdata.v1.Tree, com.codebinge.firestore.codec.testdata.v1.Tree.Builder, com.codebinge.firestore.codec.testdata.v1.TreeOrBuilder>(
                children_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        children_ = null;
      }
      return childrenBuilder_;
    }

    private static final class NamedConverter implements com.google.protobuf.MapFieldBuilder.Converter<java.lang.String, com.codebinge.firestore.codec.testdata.v1.TreeOrBuilder, com.codebinge.firestore.codec.testdata.v1.Tree> {
      @java.lang.Override
      public com.codebinge.firestore.codec.testdata.v1.Tree build(com.codebinge.firestore.codec.testdata.v1.TreeOrBuilder val) {
        if (val instanceof com.codebinge.firestore.codec.testdata.v1.Tree) { return (com.codebinge.firestore.codec.testdata.v1.Tree) val; }
        return ((com.codebinge.firestore.codec.testdata.v1.Tree.Builder) val).build();
      }

      @java.lang.Override
      public com.google.protobuf.MapEntry<java.lang.String, com.codebinge.firestore.codec.testdata.v1.Tree> defaultEntry() {
        return NamedDefaultEntryHolder.defaultEntry;
      }
    };
    private static final NamedConverter namedConverter = new NamedConverter();

    private com.google.protobuf.MapFieldBuilder<
        java.lang.String, com.codebinge.firestore.codec.testdata.v1.TreeOrBuilder, com.codebinge.firestore.codec.testdata.v1.Tree, com.codebinge.firestore.codec.testdata.v1.Tree.Builder> named_;
    private com.google.protobuf.MapFieldBuilder<java.lang.String, com.codebinge.firestore.codec.testdata.v1.TreeOrBuilder, com.codebinge.firestore.codec.testdata.v1.Tree, com.codebinge.firestore.codec.testdata.v1.Tree.Builder>
        internalGetNamed() {
      if (named_ == null) {
        return new com.google.protobuf.MapFieldBuilder<>(namedConverter);
      }
      return named_;
    }
    private com.google.protobuf.MapFieldBuilder<java.lang.String, com.codebinge.firestore.codec.testdata.v1.TreeOrBuilder, com.codebinge.firestore.codec.testdata.v1.Tree, com.codebinge.firestore.codec.testdata.v1.Tree.Builder>
        internalGetMutableNamed() {
      if (named_ == null) {
        named_ = new com.google.protobuf.MapFieldBuilder<>(namedConverter);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return named_;
    }
    public int getNamedCount() {
      return internalGetNamed().ensureBuilderMap().size();
    }
    /**
     * <code>map&lt;string, .codebinge.firestore.codec.testdata.v1.Tree&gt; named = 3;</code>
     */
    @java.lang.Override
    public boolean containsNamed(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetNamed().ensureBuilderMap().containsKey(key);
    }
    /**
     * Use {@link #getNamedMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.codebinge.firestore.codec.testdata.v1.Tree> getNamed() {
      return getNamedMap();
    }
    /**
     * <code>map&lt;string, .codebinge.firestore.codec.testdata.v1.Tree&gt; named = 3;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, com.codebinge.firestore.codec.testdata.v1.Tree> getNamedMap() {
      return internalGetNamed().getImmutableMap();
    }
    /**
     * <code>map&lt;string, .codebinge.firestore.codec.testdata.v1.Tree&gt; named = 3;</code>
     */
    @java.lang.Override
    public /* nullable */
com.codebinge.firestore.codec.testdata.v1.Tree getNamedOrDefault(
        java.lang.String key,
        /* nullable */
com.codebinge.firestore.codec.testdata.v1.Tree defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.codebinge.firestore.codec.testdata.v1.TreeOrBuilder> map = internalGetMutableNamed().ensureBuilderMap();
      return map.containsKey(key) ? namedConverter.build(map.get(key)) : defaultValue;
    }
    /**
     * <code>map&lt;string, .codebinge.firestore.codec.testdata.v1.Tree&gt; named = 3;</code>
     */
    @java.lang.Override
    public com.codebinge.firestore.codec.testdata.v1.Tree getNamedOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.codebinge.firestore.codec.testdata.v1.TreeOrBuilder> map = internalGetMutableNamed().ensureBuilderMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return namedConverter.build(map.get(key));
    }
    public Builder clearNamed() {
      bitField0_ = (bitField0_ & ~0x00000004);
      internalGetMutableNamed().clear();
      return this;
    }
    /**
     * <code>map&lt;string, .codebinge.firestore.codec.testdata.v1.Tree&gt; named = 3;</code>
     */
    public Builder removeNamed(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableNamed().ensureBuilderMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.codebinge.firestore.codec.testdata.v1.Tree>
        getMutableNamed() {
      bitField0_ |= 0x00000004;
      return internalGetMutableNamed().ensureMessageMap();
    }
    /**
     * <code>map&lt;string, .codebinge.firestore.codec.testdata.v1.Tree&gt; named = 3;</code>
     */
    public Builder putNamed(
        java.lang.String key,
        com.codebinge.firestore.codec.testdata.v1.Tree value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableNamed().ensureBuilderMap()
          .put(key, value);
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>map&lt;string, .codebinge.firestore.codec.testdata.v1.Tree&gt; named = 3;</code>
     */
    public Builder putAllNamed(
        java.util.Map<java.lang.String, com.codebinge.firestore.codec.testdata.v1.Tree> values) {
      for (java.util.Map.Entry<java.lang.String, com.codebinge.firestore.codec.testdata.v1.Tree> e : values.entrySet()) {
        if (e.getKey() == null || e.getValue() == null) {
          throw new NullPointerException();
        }
      }
      internalGetMutableNamed().ensureBuilderMap()
          .putAll(values);
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>map&lt;string, .codebinge.firestore.codec.testdata.v1.Tree&gt; named = 3;</code>
     */
    public com.codebinge.firestore.codec.testdata.v1.Tree.Builder putNamedBuilderIfAbsent(
        java.lang.String key) {
      java.util.Map<java.lang.String, com.codebinge.firestore.codec.testdata.v1.TreeOrBuilder> builderMap = internalGetMutableNamed().ensureBuilderMap();
      com.codebinge.firestore.codec.testdata.v1.TreeOrBuilder entry = builderMap.get(key);
      if (entry == null) {
        entry = com.codebinge.firestore.codec.testdata.v1.Tree.newBuilder();
        builderMap.put(key, entry);
      }
      if (entry instanceof com.codebinge.firestore.codec.testdata.v1.Tree) {
        entry = ((com.codebinge.firestore.codec.testdata.v1.Tree) entry).toBuilder();
        builderMap.put(key, entry);
      }
      return (com.codebinge.firestore.codec.testdata.v1.Tree.Builder) entry;
    }

    private com.google.protobuf.LazyStringArrayList tags_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureTagsIsMutable() {
      if (!tags_.isModifiable()) {
        tags_ = new com.google.protobuf.LazyStringArrayList(tags_);
      }
      bitField0_ |= 0x00000008;
    }
    /**
     * <code>repeated string tags = 4;</code>
     * @return A list containing the tags.
     */
    public com.google.protobuf.ProtocolStringList
        getTagsList() {
      tags_.makeImmutable();
      return tags_;
    }
    /**
     * <code>repeated string tags = 4;</code>
     * @return The count of tags.
     */
    public int getTagsCount() {
      return tags_.size();
    }
    /**
     * <code>repeated string tags = 4;</code>
     * @param index The index of the element to return.
     * @return The tags at the given index.
     */
    public java.lang.String getTags(int index) {
      return tags_.get(index);
    }
    /**
     * <code>repeated string tags = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the tags at the given index.
     */
    public com.google.protobuf.ByteString
        getTagsBytes(int index) {
      return tags_.getByteString(index);
    }
    /**
     * <code>repeated string tags = 4;</code>
     * @param index The index to set the value at.
     * @param value The tags to set.
     * @return This builder for chaining.
     */
    public Builder setTags(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureTagsIsMutable();
      tags_.set(index, value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string tags = 4;</code>
     * @param value The tags to add.
     * @return This builder for chaining.
     */
    public Builder addTags(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureTagsIsMutable();
      tags_.add(value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string tags = 4;</code>
     * @param values The tags to add.
     * @return This builder for chaining.
     */
    public Builder addAllTags(
        java.lang.Iterable<java.lang.String> values) {
      ensureTagsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, tags_);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string tags = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTags() {
      tags_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000008);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string tags = 4;</code>
     * @param value The bytes of the tags to add.
     * @return This builder for chaining.
     */
    public Builder addTagsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureTagsIsMutable();
      tags_.add(value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:codebinge.firestore.codec.testdata.v1.Tree)
  }

  // @@protoc_insertion_point(class_scope:codebinge.firestore.codec.testdata.v1.Tree)
  private static final com.codebinge.firestore.codec.testdata.v1.Tree DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.codebinge.firestore.codec.testdata.v1.Tree();
  }

  public static com.codebinge.firestore.codec.testdata.v1.Tree getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Tree>
      PARSER = new com.google.protobuf.AbstractParser<Tree>() {
    @java.lang.Override
    public Tree parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Tree> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Tree> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.codebinge.firestore.codec.testdata.v1.Tree getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

