// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: testdata.proto
// Protobuf Java Version: 4.33.3

package com.codebinge.firestore.codec.testdata.v1;

@com.google.protobuf.Generated
public interface TreeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:codebinge.firestore.codec.testdata.v1.Tree)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string label = 1;</code>
   * @return The label.
   */
  java.lang.String getLabel();
  /**
   * <code>string label = 1;</code>
   * @return The bytes for label.
   */
  com.google.protobuf.ByteString
      getLabelBytes();

  /**
   * <code>repeated .codebinge.firestore.codec.testdata.v1.Tree children = 2;</code>
   */
  java.util.List<com.codebinge.firestore.codec.testdata.v1.Tree> 
      getChildrenList();
  /**
   * <code>repeated .codebinge.firestore.codec.testdata.v1.Tree children = 2;</code>
   */
  com.codebinge.firestore.codec.testdata.v1.Tree getChildren(int index);
  /**
   * <code>repeated .codebinge.firestore.codec.testdata.v1.Tree children = 2;</code>
   */
  int getChildrenCount();
  /**
   * <code>repeated .codebinge.firestore.codec.testdata.v1.Tree children = 2;</code>
   */
  java.util.List<? extends com.codebinge.firestore.codec.testdata.v1.TreeOrBuilder> 
      getChildrenOrBuilderList();
  /**
   * <code>repeated .codebinge.firestore.codec.testdata.v1.Tree children = 2;</code>
   */
  com.codebinge.firestore.codec.testdata.v1.TreeOrBuilder getChildrenOrBuilder(
      int index);

  /**
   * <code>map&lt;string, .codebinge.firestore.codec.testdata.v1.Tree&gt; named = 3;</code>
   */
  int getNamedCount();
  /**
   * <code>map&lt;string, .codebinge.firestore.codec.testdata.v1.Tree&gt; named = 3;</code>
   */
  boolean containsNamed(
      java.lang.String key);
  /**
   * Use {@link #getNamedMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, com.codebinge.firestore.codec.testdata.v1.Tree>
  getNamed();
  /**
   * <code>map&lt;string, .codebinge.firestore.codec.testdata.v1.Tree&gt; named = 3;</code>
   */
  java.util.Map<java.lang.String, com.codebinge.firestore.codec.testdata.v1.Tree>
  getNamedMap();
  /**
   * <code>map&lt;string, .codebinge.firestore.codec.testdata.v1.Tree&gt; named = 3;</code>
   */
  /* nullable */
com.codebinge.firestore.codec.testdata.v1.Tree getNamedOrDefault(
      java.lang.String key,
      /* nullable */
com.codebinge.firestore.codec.testdata.v1.Tree defaultValue);
  /**
   * <code>map&lt;string, .codebinge.firestore.codec.testdata.v1.Tree&gt; named = 3;</code>
   */
  com.codebinge.firestore.codec.testdata.v1.Tree getNamedOrThrow(
      java.lang.String key);

  /**
   * <code>repeated string tags = 4;</code>
   * @return A list containing the tags.
   */
  java.util.List<java.lang.String>
      getTagsList();
  /**
   * <code>repeated string tags = 4;</code>
   * @return The count of tags.
   */
  int getTagsCount();
  /**
   * <code>repeated string tags = 4;</code>
   * @param index The index of the element to return.
   * @return The tags at the given index.
   */
  java.lang.String getTags(int index);
  /**
   * <code>repeated string tags = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the tags at the given index.
   */
  com.google.protobuf.ByteString
      getTagsBytes(int index);
}
