// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: testdata.proto
// Protobuf Java Version: 4.33.3

package com.codebinge.firestore.codec.testdata.v1;

/**
 * <pre>
 * Unsigned 64-bit boundaries (§2.1).
 * </pre>
 *
 * Protobuf type {@code codebinge.firestore.codec.testdata.v1.Unsigned}
 */
@com.google.protobuf.Generated
public final class Unsigned extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:codebinge.firestore.codec.testdata.v1.Unsigned)
    UnsignedOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 3,
      /* suffix= */ "",
      "Unsigned");
  }
  // Use Unsigned.newBuilder() to construct.
  private Unsigned(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Unsigned() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.codebinge.firestore.codec.testdata.v1.Testdata.internal_static_codebinge_firestore_codec_testdata_v1_Unsigned_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.codebinge.firestore.codec.testdata.v1.Testdata.internal_static_codebinge_firestore_codec_testdata_v1_Unsigned_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.codebinge.firestore.codec.testdata.v1.Unsigned.class, com.codebinge.firestore.codec.testdata.v1.Unsigned.Builder.class);
  }

  public static final int ZERO_FIELD_NUMBER = 1;
  private long zero_ = 0L;
  /**
   * <code>uint64 zero = 1;</code>
   * @return The zero.
   */
  @java.lang.Override
  public long getZero() {
    return zero_;
  }

  public static final int MAX_SIGNED_FIELD_NUMBER = 2;
  private long maxSigned_ = 0L;
  /**
   * <pre>
   * 2^63-1, the largest Firestore integer
   * </pre>
   *
   * <code>uint64 max_signed = 2;</code>
   * @return The maxSigned.
   */
  @java.lang.Override
  public long getMaxSigned() {
    return maxSigned_;
  }

  public static final int MIN_UNSIGNED_ONLY_FIELD_NUMBER = 3;
  private long minUnsignedOnly_ = 0L;
  /**
   * <pre>
   * 2^63, the first value that does not fit
   * </pre>
   *
   * <code>uint64 min_unsigned_only = 3;</code>
   * @return The minUnsignedOnly.
   */
  @java.lang.Override
  public long getMinUnsignedOnly() {
    return minUnsignedOnly_;
  }

  public static final int MAX_UNSIGNED_FIELD_NUMBER = 4;
  private long maxUnsigned_ = 0L;
  /**
   * <pre>
   * 2^64-1
   * </pre>
   *
   * <code>uint64 max_unsigned = 4;</code>
   * @return The maxUnsigned.
   */
  @java.lang.Override
  public long getMaxUnsigned() {
    return maxUnsigned_;
  }

  public static final int FIXED_FIELD_NUMBER = 5;
  private long fixed_ = 0L;
  /**
   * <code>fixed64 fixed = 5;</code>
   * @return The fixed.
   */
  @java.lang.Override
  public long getFixed() {
    return fixed_;
  }

  public static final int AS_INTEGER_FIELD_NUMBER = 6;
  private long asInteger_ = 0L;
  /**
   * <code>uint64 as_integer = 6 [(.codebinge.firestore.codec.v1.field) = { ... }</code>
   * @return The asInteger.
   */
  @java.lang.Override
  public long getAsInteger() {
    return asInteger_;
  }

  public static final int ALWAYS_FIELD_NUMBER = 7;
  private long always_ = 0L;
  /**
   * <code>uint64 always = 7 [(.codebinge.firestore.codec.v1.field) = { ... }</code>
   * @return The always.
   */
  @java.lang.Override
  public long getAlways() {
    return always_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (zero_ != 0L) {
      output.writeUInt64(1, zero_);
    }
    if (maxSigned_ != 0L) {
      output.writeUInt64(2, maxSigned_);
    }
    if (minUnsignedOnly_ != 0L) {
      output.writeUInt64(3, minUnsignedOnly_);
    }
    if (maxUnsigned_ != 0L) {
      output.writeUInt64(4, maxUnsigned_);
    }
    if (fixed_ != 0L) {
      output.writeFixed64(5, fixed_);
    }
    if (asInteger_ != 0L) {
      output.writeUInt64(6, asInteger_);
    }
    if (always_ != 0L) {
      output.writeUInt64(7, always_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (zero_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, zero_);
    }
    if (maxSigned_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(2, maxSigned_);
    }
    if (minUnsignedOnly_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(3, minUnsignedOnly_);
    }
    if (maxUnsigned_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(4, maxUnsigned_);
    }
    if (fixed_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeFixed64Size(5, fixed_);
    }
    if (asInteger_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(6, asInteger_);
    }
    if (always_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(7, always_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.codebinge.firestore.codec.testdata.v1.Unsigned)) {
      return super.equals(obj);
    }
    com.codebinge.firestore.codec.testdata.v1.Unsigned other = (com.codebinge.firestore.codec.testdata.v1.Unsigned) obj;

    if (getZero()
        != other.getZero()) return false;
    if (getMaxSigned()
        != other.getMaxSigned()) return false;
    if (getMinUnsignedOnly()
        != other.getMinUnsignedOnly()) return false;
    if (getMaxUnsigned()
        != other.getMaxUnsigned()) return false;
    if (getFixed()
        != other.getFixed()) return false;
    if (getAsInteger()
        != other.getAsInteger()) return false;
    if (getAlways()
        != other.getAlways()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ZERO_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getZero());
    hash = (37 * hash) + MAX_SIGNED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMaxSigned());
    hash = (37 * hash) + MIN_UNSIGNED_ONLY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMinUnsignedOnly());
    hash = (37 * hash) + MAX_UNSIGNED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMaxUnsigned());
    hash = (37 * hash) + FIXED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getFixed());
    hash = (37 * hash) + AS_INTEGER_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getAsInteger());
    hash = (37 * hash) + ALWAYS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getAlways());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.codebinge.firestore.codec.testdata.v1.Unsigned parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Unsigned parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Unsigned parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Unsigned parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Unsigned parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Unsigned parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Unsigned parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Unsigned parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.codebinge.firestore.codec.testdata.v1.Unsigned parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.codebinge.firestore.codec.testdata.v1.Unsigned parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Unsigned parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.codebinge.firestore.codec.testdata.v1.Unsigned parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.codebinge.firestore.codec.testdata.v1.Unsigned prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Unsigned 64-bit boundaries (§2.1).
   * </pre>
   *
   * Protobuf type {@code codebinge.firestore.codec.testdata.v1.Unsigned}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:codebinge.firestore.codec.testdata.v1.Unsigned)
      com.codebinge.firestore.codec.testdata.v1.UnsignedOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.codebinge.firestore.codec.testdata.v1.Testdata.internal_static_codebinge_firestore_codec_testdata_v1_Unsigned_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.codebinge.firestore.codec.testdata.v1.Testdata.internal_static_codebinge_firestore_codec_testdata_v1_Unsigned_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.codebinge.firestore.codec.testdata.v1.Unsigned.class, com.codebinge.firestore.codec.testdata.v1.Unsigned.Builder.class);
    }

    // Construct using com.codebinge.firestore.codec.testdata.v1.Unsigned.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      zero_ = 0L;
      maxSigned_ = 0L;
      minUnsignedOnly_ = 0L;
      maxUnsigned_ = 0L;
      fixed_ = 0L;
      asInteger_ = 0L;
      always_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.codebinge.firestore.codec.testdata.v1.Testdata.internal_static_codebinge_firestore_codec_testdata_v1_Unsigned_descriptor;
    }

    @java.lang.Override
    public com.codebinge.firestore.codec.testdata.v1.Unsigned getDefaultInstanceForType() {
      return com.codebinge.firestore.codec.testdata.v1.Unsigned.getDefaultInstance();
    }

    @java.lang.Override
    public com.codebinge.firestore.codec.testdata.v1.Unsigned build() {
      com.codebinge.firestore.codec.testdata.v1.Unsigned result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.codebinge.firestore.codec.testdata.v1.Unsigned buildPartial() {
      com.codebinge.firestore.codec.testdata.v1.Unsigned result = new com.codebinge.firestore.codec.testdata.v1.Unsigned(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.codebinge.firestore.codec.testdata.v1.Unsigned result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.zero_ = zero_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.maxSigned_ = maxSigned_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.minUnsignedOnly_ = minUnsignedOnly_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.maxUnsigned_ = maxUnsigned_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.fixed_ = fixed_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.asInteger_ = asInteger_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.always_ = always_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.codebinge.firestore.codec.testdata.v1.Unsigned) {
        return mergeFrom((com.codebinge.firestore.codec.testdata.v1.Unsigned)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.codebinge.firestore.codec.testdata.v1.Unsigned other) {
      if (other == com.codebinge.firestore.codec.testdata.v1.Unsigned.getDefaultInstance()) return this;
      if (other.getZero() != 0L) {
        setZero(other.getZero());
      }
      if (other.getMaxSigned() != 0L) {
        setMaxSigned(other.getMaxSigned());
      }
      if (other.getMinUnsignedOnly() != 0L) {
        setMinUnsignedOnly(other.getMinUnsignedOnly());
      }
      if (other.getMaxUnsigned() != 0L) {
        setMaxUnsigned(other.getMaxUnsigned());
      }
      if (other.getFixed() != 0L) {
        setFixed(other.getFixed());
      }
      if (other.getAsInteger() != 0L) {
        setAsInteger(other.getAsInteger());
      }
      if (other.getAlways() != 0L) {
        setAlways(other.getAlways());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              zero_ = input.readUInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              maxSigned_ = input.readUInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              minUnsignedOnly_ = input.readUInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              maxUnsigned_ = input.readUInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 41: {
              fixed_ = input.readFixed64();
              bitField0_ |= 0x00000010;
              break;
            } // case 41
            case 48: {
              asInteger_ = input.readUInt64();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              always_ = input.readUInt64();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long zero_ ;
    /**
     * <code>uint64 zero = 1;</code>
     * @return The zero.
     */
    @java.lang.Override
    public long getZero() {
      return zero_;
    }
    /**
     * <code>uint64 zero = 1;</code>
     * @param value The zero to set.
     * @return This builder for chaining.
     */
    public Builder setZero(long value) {

      zero_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 zero = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearZero() {
      bitField0_ = (bitField0_ & ~0x00000001);
      zero_ = 0L;
      onChanged();
      return this;
    }

    private long maxSigned_ ;
    /**
     * <pre>
     * 2^63-1, the largest Firestore integer
     * </pre>
     *
     * <code>uint64 max_signed = 2;</code>
     * @return The maxSigned.
     */
    @java.lang.Override
    public long getMaxSigned() {
      return maxSigned_;
    }
    /**
     * <pre>
     * 2^63-1, the largest Firestore integer
     * </pre>
     *
     * <code>uint64 max_signed = 2;</code>
     * @param value The maxSigned to set.
     * @return This builder for chaining.
     */
    public Builder setMaxSigned(long value) {

      maxSigned_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 2^63-1, the largest Firestore integer
     * </pre>
     *
     * <code>uint64 max_signed = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxSigned() {
      bitField0_ = (bitField0_ & ~0x00000002);
      maxSigned_ = 0L;
      onChanged();
      return this;
    }

    private long minUnsignedOnly_ ;
    /**
     * <pre>
     * 2^63, the first value that does not fit
     * </pre>
     *
     * <code>uint64 min_unsigned_only = 3;</code>
     * @return The minUnsignedOnly.
     */
    @java.lang.Override
    public long getMinUnsignedOnly() {
      return minUnsignedOnly_;
    }
    /**
     * <pre>
     * 2^63, the first value that does not fit
     * </pre>
     *
     * <code>uint64 min_unsigned_only = 3;</code>
     * @param value The minUnsignedOnly to set.
     * @return This builder for chaining.
     */
    public Builder setMinUnsignedOnly(long value) {

      minUnsignedOnly_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 2^63, the first value that does not fit
     * </pre>
     *
     * <code>uint64 min_unsigned_only = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMinUnsignedOnly() {
      bitField0_ = (bitField0_ & ~0x00000004);
      minUnsignedOnly_ = 0L;
      onChanged();
      return this;
    }

    private long maxUnsigned_ ;
    /**
     * <pre>
     * 2^64-1
     * </pre>
     *
     * <code>uint64 max_unsigned = 4;</code>
     * @return The maxUnsigned.
     */
    @java.lang.Override
    public long getMaxUnsigned() {
      return maxUnsigned_;
    }
    /**
     * <pre>
     * 2^64-1
     * </pre>
     *
     * <code>uint64 max_unsigned = 4;</code>
     * @param value The maxUnsigned to set.
     * @return This builder for chaining.
     */
    public Builder setMaxUnsigned(long value) {

      maxUnsigned_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 2^64-1
     * </pre>
     *
     * <code>uint64 max_unsigned = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxUnsigned() {
      bitField0_ = (bitField0_ & ~0x00000008);
      maxUnsigned_ = 0L;
      onChanged();
      return this;
    }

    private long fixed_ ;
    /**
     * <code>fixed64 fixed = 5;</code>
     * @return The fixed.
     */
    @java.lang.Override
    public long getFixed() {
      return fixed_;
    }
    /**
     * <code>fixed64 fixed = 5;</code>
     * @param value The fixed to set.
     * @return This builder for chaining.
     */
    public Builder setFixed(long value) {

      fixed_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>fixed64 fixed = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearFixed() {
      bitField0_ = (bitField0_ & ~0x00000010);
      fixed_ = 0L;
      onChanged();
      return this;
    }

    private long asInteger_ ;
    /**
     * <code>uint64 as_integer = 6 [(.codebinge.firestore.codec.v1.field) = { ... }</code>
     * @return The asInteger.
     */
    @java.lang.Override
    public long getAsInteger() {
      return asInteger_;
    }
    /**
     * <code>uint64 as_integer = 6 [(.codebinge.firestore.codec.v1.field) = { ... }</code>
     * @param value The asInteger to set.
     * @return This builder for chaining.
     */
    public Builder setAsInteger(long value) {

      asInteger_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 as_integer = 6 [(.codebinge.firestore.codec.v1.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearAsInteger() {
      bitField0_ = (bitField0_ & ~0x00000020);
      asInteger_ = 0L;
      onChanged();
      return this;
    }

    private long always_ ;
    /**
     * <code>uint64 always = 7 [(.codebinge.firestore.codec.v1.field) = { ... }</code>
     * @return The always.
     */
    @java.lang.Override
    public long getAlways() {
      return always_;
    }
    /**
     * <code>uint64 always = 7 [(.codebinge.firestore.codec.v1.field) = { ... }</code>
     * @param value The always to set.
     * @return This builder for chaining.
     */
    public Builder setAlways(long value) {

      always_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 always = 7 [(.codebinge.firestore.codec.v1.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearAlways() {
      bitField0_ = (bitField0_ & ~0x00000040);
      always_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:codebinge.firestore.codec.testdata.v1.Unsigned)
  }

  // @@protoc_insertion_point(class_scope:codebinge.firestore.codec.testdata.v1.Unsigned)
  private static final com.codebinge.firestore.codec.testdata.v1.Unsigned DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.codebinge.firestore.codec.testdata.v1.Unsigned();
  }

  public static com.codebinge.firestore.codec.testdata.v1.Unsigned getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Unsigned>
      PARSER = new com.google.protobuf.AbstractParser<Unsigned>() {
    @java.lang.Override
    public Unsigned parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Unsigned> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Unsigned> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.codebinge.firestore.codec.testdata.v1.Unsigned getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

