// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: testdata.proto
// Protobuf Java Version: 4.33.3

package com.codebinge.firestore.codec.testdata.v1;

@com.google.protobuf.Generated
public interface UnsignedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:codebinge.firestore.codec.testdata.v1.Unsigned)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 zero = 1;</code>
   * @return The zero.
   */
  long getZero();

  /**
   * <pre>
   * 2^63-1, the largest Firestore integer
   * </pre>
   *
   * <code>uint64 max_signed = 2;</code>
   * @return The maxSigned.
   */
  long getMaxSigned();

  /**
   * <pre>
   * 2^63, the first value that does not fit
   * </pre>
   *
   * <code>uint64 min_unsigned_only = 3;</code>
   * @return The minUnsignedOnly.
   */
  long getMinUnsignedOnly();

  /**
   * <pre>
   * 2^64-1
   * </pre>
   *
   * <code>uint64 max_unsigned = 4;</code>
   * @return The maxUnsigned.
   */
  long getMaxUnsigned();

  /**
   * <code>fixed64 fixed = 5;</code>
   * @return The fixed.
   */
  long getFixed();

  /**
   * <code>uint64 as_integer = 6 [(.codebinge.firestore.codec.v1.field) = { ... }</code>
   * @return The asInteger.
   */
  long getAsInteger();

  /**
   * <code>uint64 always = 7 [(.codebinge.firestore.codec.v1.field) = { ... }</code>
   * @return The always.
   */
  long getAlways();
}
