// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: codebinge/firestore/codec/v1/options.proto
// Protobuf Java Version: 4.33.3

package com.codebinge.firestore.codec.v1;

/**
 * Protobuf enum {@code codebinge.firestore.codec.v1.EnumEncoding}
 */
@com.google.protobuf.Generated
public enum EnumEncoding
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>ENUM_ENCODING_NAME = 0;</code>
   */
  ENUM_ENCODING_NAME(0),
  /**
   * <code>ENUM_ENCODING_NUMBER = 1;</code>
   */
  ENUM_ENCODING_NUMBER(1),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 3,
      /* suffix= */ "",
      "EnumEncoding");
  }
  /**
   * <code>ENUM_ENCODING_NAME = 0;</code>
   */
  public static final int ENUM_ENCODING_NAME_VALUE = 0;
  /**
   * <code>ENUM_ENCODING_NUMBER = 1;</code>
   */
  public static final int ENUM_ENCODING_NUMBER_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static EnumEncoding valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static EnumEncoding forNumber(int value) {
    switch (value) {
      case 0: return ENUM_ENCODING_NAME;
      case 1: return ENUM_ENCODING_NUMBER;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<EnumEncoding>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      EnumEncoding> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<EnumEncoding>() {
          public EnumEncoding findValueByNumber(int number) {
            return EnumEncoding.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.codebinge.firestore.codec.v1.Options.getDescriptor().getEnumTypes().get(1);
  }

  private static final EnumEncoding[] VALUES = values();

  public static EnumEncoding valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private EnumEncoding(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:codebinge.firestore.codec.v1.EnumEncoding)
}

