// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: codebinge/firestore/codec/v1/options.proto
// Protobuf Java Version: 4.33.3

package com.codebinge.firestore.codec.v1;

@com.google.protobuf.Generated
public interface FieldOrBuilder extends
    // @@protoc_insertion_point(interface_extends:codebinge.firestore.codec.v1.Field)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Never encoded.
   * </pre>
   *
   * <code>bool skip = 1;</code>
   * @return The skip.
   */
  boolean getSkip();

  /**
   * <pre>
   * Stored-name override. Exists only for adopting an existing collection;
   * the default is the proto field name verbatim (§1).
   * </pre>
   *
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * Stored-name override. Exists only for adopting an existing collection;
   * the default is the proto field name verbatim (§1).
   * </pre>
   *
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * Default: encode enum values as their name string (§4).
   * </pre>
   *
   * <code>.codebinge.firestore.codec.v1.EnumEncoding enum_as = 3;</code>
   * @return The enum numeric value on the wire for enumAs.
   */
  int getEnumAsValue();
  /**
   * <pre>
   * Default: encode enum values as their name string (§4).
   * </pre>
   *
   * <code>.codebinge.firestore.codec.v1.EnumEncoding enum_as = 3;</code>
   * @return The enumAs.
   */
  com.codebinge.firestore.codec.v1.EnumEncoding getEnumAs();

  /**
   * <pre>
   * Default true: omit singular scalar fields holding their default value (§6).
   * Set false where an index or security rule depends on the field existing.
   *
   * Explicit presence is required. The intended default is true, and a proto3
   * implicit-presence bool would not serialize `false`, leaving "set to false"
   * indistinguishable from "not set".
   * </pre>
   *
   * <code>optional bool omit_when_default = 4;</code>
   * @return Whether the omitWhenDefault field is set.
   */
  boolean hasOmitWhenDefault();
  /**
   * <pre>
   * Default true: omit singular scalar fields holding their default value (§6).
   * Set false where an index or security rule depends on the field existing.
   *
   * Explicit presence is required. The intended default is true, and a proto3
   * implicit-presence bool would not serialize `false`, leaving "set to false"
   * indistinguishable from "not set".
   * </pre>
   *
   * <code>optional bool omit_when_default = 4;</code>
   * @return The omitWhenDefault.
   */
  boolean getOmitWhenDefault();

  /**
   * <pre>
   * Overrides the encoding inferred from the proto type.
   * </pre>
   *
   * <code>.codebinge.firestore.codec.v1.Kind kind = 5;</code>
   * @return The enum numeric value on the wire for kind.
   */
  int getKindValue();
  /**
   * <pre>
   * Overrides the encoding inferred from the proto type.
   * </pre>
   *
   * <code>.codebinge.firestore.codec.v1.Kind kind = 5;</code>
   * @return The kind.
   */
  com.codebinge.firestore.codec.v1.Kind getKind();
}
