// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: codebinge/firestore/codec/v1/options.proto
// Protobuf Java Version: 4.33.3

package com.codebinge.firestore.codec.v1;

/**
 * Protobuf type {@code codebinge.firestore.codec.v1.Field}
 */
@com.google.protobuf.Generated
public final class Field extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:codebinge.firestore.codec.v1.Field)
    FieldOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 3,
      /* suffix= */ "",
      "Field");
  }
  // Use Field.newBuilder() to construct.
  private Field(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Field() {
    name_ = "";
    enumAs_ = 0;
    kind_ = 0;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.codebinge.firestore.codec.v1.Options.internal_static_codebinge_firestore_codec_v1_Field_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.codebinge.firestore.codec.v1.Options.internal_static_codebinge_firestore_codec_v1_Field_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.codebinge.firestore.codec.v1.Field.class, com.codebinge.firestore.codec.v1.Field.Builder.class);
  }

  private int bitField0_;
  public static final int SKIP_FIELD_NUMBER = 1;
  private boolean skip_ = false;
  /**
   * <pre>
   * Never encoded.
   * </pre>
   *
   * <code>bool skip = 1;</code>
   * @return The skip.
   */
  @java.lang.Override
  public boolean getSkip() {
    return skip_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <pre>
   * Stored-name override. Exists only for adopting an existing collection;
   * the default is the proto field name verbatim (§1).
   * </pre>
   *
   * <code>string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Stored-name override. Exists only for adopting an existing collection;
   * the default is the proto field name verbatim (§1).
   * </pre>
   *
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ENUM_AS_FIELD_NUMBER = 3;
  private int enumAs_ = 0;
  /**
   * <pre>
   * Default: encode enum values as their name string (§4).
   * </pre>
   *
   * <code>.codebinge.firestore.codec.v1.EnumEncoding enum_as = 3;</code>
   * @return The enum numeric value on the wire for enumAs.
   */
  @java.lang.Override public int getEnumAsValue() {
    return enumAs_;
  }
  /**
   * <pre>
   * Default: encode enum values as their name string (§4).
   * </pre>
   *
   * <code>.codebinge.firestore.codec.v1.EnumEncoding enum_as = 3;</code>
   * @return The enumAs.
   */
  @java.lang.Override public com.codebinge.firestore.codec.v1.EnumEncoding getEnumAs() {
    com.codebinge.firestore.codec.v1.EnumEncoding result = com.codebinge.firestore.codec.v1.EnumEncoding.forNumber(enumAs_);
    return result == null ? com.codebinge.firestore.codec.v1.EnumEncoding.UNRECOGNIZED : result;
  }

  public static final int OMIT_WHEN_DEFAULT_FIELD_NUMBER = 4;
  private boolean omitWhenDefault_ = false;
  /**
   * <pre>
   * Default true: omit singular scalar fields holding their default value (§6).
   * Set false where an index or security rule depends on the field existing.
   *
   * Explicit presence is required. The intended default is true, and a proto3
   * implicit-presence bool would not serialize `false`, leaving "set to false"
   * indistinguishable from "not set".
   * </pre>
   *
   * <code>optional bool omit_when_default = 4;</code>
   * @return Whether the omitWhenDefault field is set.
   */
  @java.lang.Override
  public boolean hasOmitWhenDefault() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Default true: omit singular scalar fields holding their default value (§6).
   * Set false where an index or security rule depends on the field existing.
   *
   * Explicit presence is required. The intended default is true, and a proto3
   * implicit-presence bool would not serialize `false`, leaving "set to false"
   * indistinguishable from "not set".
   * </pre>
   *
   * <code>optional bool omit_when_default = 4;</code>
   * @return The omitWhenDefault.
   */
  @java.lang.Override
  public boolean getOmitWhenDefault() {
    return omitWhenDefault_;
  }

  public static final int KIND_FIELD_NUMBER = 5;
  private int kind_ = 0;
  /**
   * <pre>
   * Overrides the encoding inferred from the proto type.
   * </pre>
   *
   * <code>.codebinge.firestore.codec.v1.Kind kind = 5;</code>
   * @return The enum numeric value on the wire for kind.
   */
  @java.lang.Override public int getKindValue() {
    return kind_;
  }
  /**
   * <pre>
   * Overrides the encoding inferred from the proto type.
   * </pre>
   *
   * <code>.codebinge.firestore.codec.v1.Kind kind = 5;</code>
   * @return The kind.
   */
  @java.lang.Override public com.codebinge.firestore.codec.v1.Kind getKind() {
    com.codebinge.firestore.codec.v1.Kind result = com.codebinge.firestore.codec.v1.Kind.forNumber(kind_);
    return result == null ? com.codebinge.firestore.codec.v1.Kind.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (skip_ != false) {
      output.writeBool(1, skip_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, name_);
    }
    if (enumAs_ != com.codebinge.firestore.codec.v1.EnumEncoding.ENUM_ENCODING_NAME.getNumber()) {
      output.writeEnum(3, enumAs_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeBool(4, omitWhenDefault_);
    }
    if (kind_ != com.codebinge.firestore.codec.v1.Kind.KIND_UNSPECIFIED.getNumber()) {
      output.writeEnum(5, kind_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (skip_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, skip_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, name_);
    }
    if (enumAs_ != com.codebinge.firestore.codec.v1.EnumEncoding.ENUM_ENCODING_NAME.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, enumAs_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, omitWhenDefault_);
    }
    if (kind_ != com.codebinge.firestore.codec.v1.Kind.KIND_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, kind_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.codebinge.firestore.codec.v1.Field)) {
      return super.equals(obj);
    }
    com.codebinge.firestore.codec.v1.Field other = (com.codebinge.firestore.codec.v1.Field) obj;

    if (getSkip()
        != other.getSkip()) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (enumAs_ != other.enumAs_) return false;
    if (hasOmitWhenDefault() != other.hasOmitWhenDefault()) return false;
    if (hasOmitWhenDefault()) {
      if (getOmitWhenDefault()
          != other.getOmitWhenDefault()) return false;
    }
    if (kind_ != other.kind_) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SKIP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSkip());
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + ENUM_AS_FIELD_NUMBER;
    hash = (53 * hash) + enumAs_;
    if (hasOmitWhenDefault()) {
      hash = (37 * hash) + OMIT_WHEN_DEFAULT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getOmitWhenDefault());
    }
    hash = (37 * hash) + KIND_FIELD_NUMBER;
    hash = (53 * hash) + kind_;
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.codebinge.firestore.codec.v1.Field parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.codebinge.firestore.codec.v1.Field parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.codebinge.firestore.codec.v1.Field parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.codebinge.firestore.codec.v1.Field parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.codebinge.firestore.codec.v1.Field parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.codebinge.firestore.codec.v1.Field parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.codebinge.firestore.codec.v1.Field parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.codebinge.firestore.codec.v1.Field parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.codebinge.firestore.codec.v1.Field parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.codebinge.firestore.codec.v1.Field parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.codebinge.firestore.codec.v1.Field parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.codebinge.firestore.codec.v1.Field parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.codebinge.firestore.codec.v1.Field prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code codebinge.firestore.codec.v1.Field}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:codebinge.firestore.codec.v1.Field)
      com.codebinge.firestore.codec.v1.FieldOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.codebinge.firestore.codec.v1.Options.internal_static_codebinge_firestore_codec_v1_Field_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.codebinge.firestore.codec.v1.Options.internal_static_codebinge_firestore_codec_v1_Field_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.codebinge.firestore.codec.v1.Field.class, com.codebinge.firestore.codec.v1.Field.Builder.class);
    }

    // Construct using com.codebinge.firestore.codec.v1.Field.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      skip_ = false;
      name_ = "";
      enumAs_ = 0;
      omitWhenDefault_ = false;
      kind_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.codebinge.firestore.codec.v1.Options.internal_static_codebinge_firestore_codec_v1_Field_descriptor;
    }

    @java.lang.Override
    public com.codebinge.firestore.codec.v1.Field getDefaultInstanceForType() {
      return com.codebinge.firestore.codec.v1.Field.getDefaultInstance();
    }

    @java.lang.Override
    public com.codebinge.firestore.codec.v1.Field build() {
      com.codebinge.firestore.codec.v1.Field result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.codebinge.firestore.codec.v1.Field buildPartial() {
      com.codebinge.firestore.codec.v1.Field result = new com.codebinge.firestore.codec.v1.Field(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.codebinge.firestore.codec.v1.Field result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.skip_ = skip_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.enumAs_ = enumAs_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.omitWhenDefault_ = omitWhenDefault_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.kind_ = kind_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.codebinge.firestore.codec.v1.Field) {
        return mergeFrom((com.codebinge.firestore.codec.v1.Field)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.codebinge.firestore.codec.v1.Field other) {
      if (other == com.codebinge.firestore.codec.v1.Field.getDefaultInstance()) return this;
      if (other.getSkip() != false) {
        setSkip(other.getSkip());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.enumAs_ != 0) {
        setEnumAsValue(other.getEnumAsValue());
      }
      if (other.hasOmitWhenDefault()) {
        setOmitWhenDefault(other.getOmitWhenDefault());
      }
      if (other.kind_ != 0) {
        setKindValue(other.getKindValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              skip_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              enumAs_ = input.readEnum();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              omitWhenDefault_ = input.readBool();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              kind_ = input.readEnum();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean skip_ ;
    /**
     * <pre>
     * Never encoded.
     * </pre>
     *
     * <code>bool skip = 1;</code>
     * @return The skip.
     */
    @java.lang.Override
    public boolean getSkip() {
      return skip_;
    }
    /**
     * <pre>
     * Never encoded.
     * </pre>
     *
     * <code>bool skip = 1;</code>
     * @param value The skip to set.
     * @return This builder for chaining.
     */
    public Builder setSkip(boolean value) {

      skip_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Never encoded.
     * </pre>
     *
     * <code>bool skip = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSkip() {
      bitField0_ = (bitField0_ & ~0x00000001);
      skip_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <pre>
     * Stored-name override. Exists only for adopting an existing collection;
     * the default is the proto field name verbatim (§1).
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Stored-name override. Exists only for adopting an existing collection;
     * the default is the proto field name verbatim (§1).
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Stored-name override. Exists only for adopting an existing collection;
     * the default is the proto field name verbatim (§1).
     * </pre>
     *
     * <code>string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Stored-name override. Exists only for adopting an existing collection;
     * the default is the proto field name verbatim (§1).
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Stored-name override. Exists only for adopting an existing collection;
     * the default is the proto field name verbatim (§1).
     * </pre>
     *
     * <code>string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int enumAs_ = 0;
    /**
     * <pre>
     * Default: encode enum values as their name string (§4).
     * </pre>
     *
     * <code>.codebinge.firestore.codec.v1.EnumEncoding enum_as = 3;</code>
     * @return The enum numeric value on the wire for enumAs.
     */
    @java.lang.Override public int getEnumAsValue() {
      return enumAs_;
    }
    /**
     * <pre>
     * Default: encode enum values as their name string (§4).
     * </pre>
     *
     * <code>.codebinge.firestore.codec.v1.EnumEncoding enum_as = 3;</code>
     * @param value The enum numeric value on the wire for enumAs to set.
     * @return This builder for chaining.
     */
    public Builder setEnumAsValue(int value) {
      enumAs_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Default: encode enum values as their name string (§4).
     * </pre>
     *
     * <code>.codebinge.firestore.codec.v1.EnumEncoding enum_as = 3;</code>
     * @return The enumAs.
     */
    @java.lang.Override
    public com.codebinge.firestore.codec.v1.EnumEncoding getEnumAs() {
      com.codebinge.firestore.codec.v1.EnumEncoding result = com.codebinge.firestore.codec.v1.EnumEncoding.forNumber(enumAs_);
      return result == null ? com.codebinge.firestore.codec.v1.EnumEncoding.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Default: encode enum values as their name string (§4).
     * </pre>
     *
     * <code>.codebinge.firestore.codec.v1.EnumEncoding enum_as = 3;</code>
     * @param value The enumAs to set.
     * @return This builder for chaining.
     */
    public Builder setEnumAs(com.codebinge.firestore.codec.v1.EnumEncoding value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000004;
      enumAs_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Default: encode enum values as their name string (§4).
     * </pre>
     *
     * <code>.codebinge.firestore.codec.v1.EnumEncoding enum_as = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearEnumAs() {
      bitField0_ = (bitField0_ & ~0x00000004);
      enumAs_ = 0;
      onChanged();
      return this;
    }

    private boolean omitWhenDefault_ ;
    /**
     * <pre>
     * Default true: omit singular scalar fields holding their default value (§6).
     * Set false where an index or security rule depends on the field existing.
     *
     * Explicit presence is required. The intended default is true, and a proto3
     * implicit-presence bool would not serialize `false`, leaving "set to false"
     * indistinguishable from "not set".
     * </pre>
     *
     * <code>optional bool omit_when_default = 4;</code>
     * @return Whether the omitWhenDefault field is set.
     */
    @java.lang.Override
    public boolean hasOmitWhenDefault() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * Default true: omit singular scalar fields holding their default value (§6).
     * Set false where an index or security rule depends on the field existing.
     *
     * Explicit presence is required. The intended default is true, and a proto3
     * implicit-presence bool would not serialize `false`, leaving "set to false"
     * indistinguishable from "not set".
     * </pre>
     *
     * <code>optional bool omit_when_default = 4;</code>
     * @return The omitWhenDefault.
     */
    @java.lang.Override
    public boolean getOmitWhenDefault() {
      return omitWhenDefault_;
    }
    /**
     * <pre>
     * Default true: omit singular scalar fields holding their default value (§6).
     * Set false where an index or security rule depends on the field existing.
     *
     * Explicit presence is required. The intended default is true, and a proto3
     * implicit-presence bool would not serialize `false`, leaving "set to false"
     * indistinguishable from "not set".
     * </pre>
     *
     * <code>optional bool omit_when_default = 4;</code>
     * @param value The omitWhenDefault to set.
     * @return This builder for chaining.
     */
    public Builder setOmitWhenDefault(boolean value) {

      omitWhenDefault_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Default true: omit singular scalar fields holding their default value (§6).
     * Set false where an index or security rule depends on the field existing.
     *
     * Explicit presence is required. The intended default is true, and a proto3
     * implicit-presence bool would not serialize `false`, leaving "set to false"
     * indistinguishable from "not set".
     * </pre>
     *
     * <code>optional bool omit_when_default = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearOmitWhenDefault() {
      bitField0_ = (bitField0_ & ~0x00000008);
      omitWhenDefault_ = false;
      onChanged();
      return this;
    }

    private int kind_ = 0;
    /**
     * <pre>
     * Overrides the encoding inferred from the proto type.
     * </pre>
     *
     * <code>.codebinge.firestore.codec.v1.Kind kind = 5;</code>
     * @return The enum numeric value on the wire for kind.
     */
    @java.lang.Override public int getKindValue() {
      return kind_;
    }
    /**
     * <pre>
     * Overrides the encoding inferred from the proto type.
     * </pre>
     *
     * <code>.codebinge.firestore.codec.v1.Kind kind = 5;</code>
     * @param value The enum numeric value on the wire for kind to set.
     * @return This builder for chaining.
     */
    public Builder setKindValue(int value) {
      kind_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Overrides the encoding inferred from the proto type.
     * </pre>
     *
     * <code>.codebinge.firestore.codec.v1.Kind kind = 5;</code>
     * @return The kind.
     */
    @java.lang.Override
    public com.codebinge.firestore.codec.v1.Kind getKind() {
      com.codebinge.firestore.codec.v1.Kind result = com.codebinge.firestore.codec.v1.Kind.forNumber(kind_);
      return result == null ? com.codebinge.firestore.codec.v1.Kind.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Overrides the encoding inferred from the proto type.
     * </pre>
     *
     * <code>.codebinge.firestore.codec.v1.Kind kind = 5;</code>
     * @param value The kind to set.
     * @return This builder for chaining.
     */
    public Builder setKind(com.codebinge.firestore.codec.v1.Kind value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000010;
      kind_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Overrides the encoding inferred from the proto type.
     * </pre>
     *
     * <code>.codebinge.firestore.codec.v1.Kind kind = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearKind() {
      bitField0_ = (bitField0_ & ~0x00000010);
      kind_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:codebinge.firestore.codec.v1.Field)
  }

  // @@protoc_insertion_point(class_scope:codebinge.firestore.codec.v1.Field)
  private static final com.codebinge.firestore.codec.v1.Field DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.codebinge.firestore.codec.v1.Field();
  }

  public static com.codebinge.firestore.codec.v1.Field getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Field>
      PARSER = new com.google.protobuf.AbstractParser<Field>() {
    @java.lang.Override
    public Field parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Field> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Field> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.codebinge.firestore.codec.v1.Field getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

