// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: codebinge/firestore/codec/v1/options.proto
// Protobuf Java Version: 4.33.3

package com.codebinge.firestore.codec.v1;

/**
 * Protobuf enum {@code codebinge.firestore.codec.v1.Kind}
 */
@com.google.protobuf.Generated
public enum Kind
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * Infer from the proto type. The default for every field.
   * </pre>
   *
   * <code>KIND_UNSPECIFIED = 0;</code>
   */
  KIND_UNSPECIFIED(0),
  /**
   * <pre>
   * string -&gt; DocumentReference. Requires the codec to hold a Firestore
   * instance; the one place this codec is not dependency-free.
   * </pre>
   *
   * <code>KIND_REFERENCE = 1;</code>
   */
  KIND_REFERENCE(1),
  /**
   * <pre>
   * A project's own lat/lng message -&gt; GeoPoint (§3.3). Not needed for
   * google.type.LatLng, which is recognized automatically. The annotated
   * message must have exactly two double fields named `latitude` and
   * `longitude`.
   * </pre>
   *
   * <code>KIND_GEO_POINT = 2;</code>
   */
  KIND_GEO_POINT(2),
  /**
   * <pre>
   * uint64/fixed64 -&gt; Integer rather than String, keeping the field ordered
   * and queryable. Throws at encode time above 2^63-1 (§2.1).
   * </pre>
   *
   * <code>KIND_UNSIGNED_AS_INTEGER = 3;</code>
   */
  KIND_UNSIGNED_AS_INTEGER(3),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 3,
      /* suffix= */ "",
      "Kind");
  }
  /**
   * <pre>
   * Infer from the proto type. The default for every field.
   * </pre>
   *
   * <code>KIND_UNSPECIFIED = 0;</code>
   */
  public static final int KIND_UNSPECIFIED_VALUE = 0;
  /**
   * <pre>
   * string -&gt; DocumentReference. Requires the codec to hold a Firestore
   * instance; the one place this codec is not dependency-free.
   * </pre>
   *
   * <code>KIND_REFERENCE = 1;</code>
   */
  public static final int KIND_REFERENCE_VALUE = 1;
  /**
   * <pre>
   * A project's own lat/lng message -&gt; GeoPoint (§3.3). Not needed for
   * google.type.LatLng, which is recognized automatically. The annotated
   * message must have exactly two double fields named `latitude` and
   * `longitude`.
   * </pre>
   *
   * <code>KIND_GEO_POINT = 2;</code>
   */
  public static final int KIND_GEO_POINT_VALUE = 2;
  /**
   * <pre>
   * uint64/fixed64 -&gt; Integer rather than String, keeping the field ordered
   * and queryable. Throws at encode time above 2^63-1 (§2.1).
   * </pre>
   *
   * <code>KIND_UNSIGNED_AS_INTEGER = 3;</code>
   */
  public static final int KIND_UNSIGNED_AS_INTEGER_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Kind valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static Kind forNumber(int value) {
    switch (value) {
      case 0: return KIND_UNSPECIFIED;
      case 1: return KIND_REFERENCE;
      case 2: return KIND_GEO_POINT;
      case 3: return KIND_UNSIGNED_AS_INTEGER;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Kind>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Kind> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Kind>() {
          public Kind findValueByNumber(int number) {
            return Kind.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.codebinge.firestore.codec.v1.Options.getDescriptor().getEnumTypes().get(0);
  }

  private static final Kind[] VALUES = values();

  public static Kind valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private Kind(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:codebinge.firestore.codec.v1.Kind)
}

