// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: codebinge/firestore/codec/v1/options.proto
// Protobuf Java Version: 4.33.3

package com.codebinge.firestore.codec.v1;

@com.google.protobuf.Generated
public final class Options extends com.google.protobuf.GeneratedFile {
  private Options() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 3,
      /* suffix= */ "",
      "Options");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(com.codebinge.firestore.codec.v1.Options.field);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public static final int FIELD_FIELD_NUMBER = 50000;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      com.codebinge.firestore.codec.v1.Field> field = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.codebinge.firestore.codec.v1.Field.class,
        com.codebinge.firestore.codec.v1.Field.getDefaultInstance());
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_codebinge_firestore_codec_v1_Field_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_codebinge_firestore_codec_v1_Field_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n*codebinge/firestore/codec/v1/options.p" +
      "roto\022\034codebinge.firestore.codec.v1\032 goog" +
      "le/protobuf/descriptor.proto\"\310\001\n\005Field\022\014" +
      "\n\004skip\030\001 \001(\010\022\014\n\004name\030\002 \001(\t\022;\n\007enum_as\030\003 " +
      "\001(\0162*.codebinge.firestore.codec.v1.EnumE" +
      "ncoding\022\036\n\021omit_when_default\030\004 \001(\010H\000\210\001\001\022" +
      "0\n\004kind\030\005 \001(\0162\".codebinge.firestore.code" +
      "c.v1.KindB\024\n\022_omit_when_default*b\n\004Kind\022" +
      "\024\n\020KIND_UNSPECIFIED\020\000\022\022\n\016KIND_REFERENCE\020" +
      "\001\022\022\n\016KIND_GEO_POINT\020\002\022\034\n\030KIND_UNSIGNED_A" +
      "S_INTEGER\020\003*@\n\014EnumEncoding\022\026\n\022ENUM_ENCO" +
      "DING_NAME\020\000\022\030\n\024ENUM_ENCODING_NUMBER\020\001:S\n" +
      "\005field\022\035.google.protobuf.FieldOptions\030\320\206" +
      "\003 \001(\0132#.codebinge.firestore.codec.v1.Fie" +
      "ldB$\n com.codebinge.firestore.codec.v1P\001" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        });
    internal_static_codebinge_firestore_codec_v1_Field_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_codebinge_firestore_codec_v1_Field_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_codebinge_firestore_codec_v1_Field_descriptor,
        new java.lang.String[] { "Skip", "Name", "EnumAs", "OmitWhenDefault", "Kind", });
    field.internalInit(descriptor.getExtension(0));
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
